### ISSUE TITLE
OpenAPI `/doc` path not found

### ISSUE THREAD

**Issue by igorbrites** [AzBuilder/terrakube#1005]
### Bug description 🐞

According to [this page](https://docs.terrakube.io/api/getting-started#terrakube-open-api-specification), there's a `/doc` path to get to OpenAPI definition, though it's getting 404s (without the token it gives 401). I see the option is enabled on the [`application.properties`](https://github.com/AzBuilder/terrakube/blob/main/api/src/main/resources/application.properties#L26) file, so I have no idea how to get to the path.

### Steps to reproduce

- Deploy Terrakube using the Helm Chart;
- Call `https://terrakube-api.my-domain.com/doc`

### Expected behavior

Get the OpenAPI definition to import it on Postman, as the repository ones are outdated.

### Example

```bash
❯ curl https://terrakube.my-domain.com/doc -i -H 'Authorization: Bearer <REDACTED>'
HTTP/2 404 
vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers
x-content-type-options: nosniff
x-xss-protection: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
strict-transport-security: max-age=31536000 ; includeSubDomains
x-frame-options: DENY
content-type: application/json
date: Mon, 24 Jun 2024 13:47:48 GMT

{"timestamp":"2024-06-24T13:47:48.284+00:00","status":404,"error":"Not Found","path":"/doc"}
```

**Comment by alfespa17** [comment]
I am not sure why the endpoint is not working, you could check the URL:

https://docs.terrakube.io/api/methods

You can find most endpoint information there and the jsonapi is quite simple

**Comment by igorbrites** [comment]
Right now I'm doing just that, though I want to import it all on Postman to be easier. I can create everything by hand there, but as OpenAPI is an option I prefer to use it.

**Comment by alfespa17** [comment]
I found the issue elide version 6 was using the following as you can see [here](https://elide.io/pages/guide/v6/13-swagger.html) 

```yaml
elide:
  swagger:
    path: /doc
    enabled: true
    version: "1.0"
```

But we have migrated to version 7 that should use the following like explained [here](https://elide.io/pages/guide/v7/13-openapi.html)

```yaml
elide:
  api-docs:
    enabled: true
    path: /doc
    version: openapi_3_0
```

**Comment by alfespa17** [comment]
You can find the json spec here @igorbrites 

https://gist.github.com/alfespa17/785a36879a79ac5c3b79d7150a71c2d1

**Comment by igorbrites** [comment]
Amazing! Thanks @alfespa17!
