### ISSUE TITLE
Login button not responding in Terrakube UI

### ISSUE THREAD

**Issue by Shubham-Jawkar1** [AzBuilder/terrakube#1016]
### Bug description 🐞

The login button on the Terrakube UI is not responding when clicked. This issue occurs on both Minikube and Kubernetes platforms.

### Steps to reproduce

Steps:
1. Deploy Terrakube using Helm chart on Minikube/Kubernetes.
2. Access the Terrakube login UI.
3. Click the login button.

### Expected behavior

The login button should authenticate the user and redirect to the dashboard.

### Anything else?

I am following below information to deploy terrakube on minikube/K8s using Helm chart
https://docs.terrakube.io/getting-started/deployment/minikube

**Comment by alfespa17** [comment]
Check your browser error and make sure you updated tour DNS records
