### ISSUE TITLE
DEX google Failed to authenticate: google: could not retrieve groups: could not list groups

### ISSUE THREAD

**Issue by rchekhina** [AzBuilder/terrakube#1045]
### Bug description 🐞

I have following the documentation [](https://docs.terrakube.io/getting-started/user-management/google-cloud-identity)
but when I try to login with my google email I have this error:

Internal Server Error
Failed to authenticate: google: could not retrieve groups: could not list groups: Get "https://admin.googleapis.com/admin/directory/v1/groups?alt=json&pageToken=&prettyPrint=false&userKey=reynald%40mycompany.com": oauth2: cannot fetch token: 403 Forbidden Response: { "error": "access_denied", "error_description": "Requested client not authorized." }

### Steps to reproduce

following doc https://docs.terrakube.io/getting-started/user-management/google-cloud-identity

**Comment by alfespa17** [comment]
You need to grant this scope to the service account `https://www.googleapis.com/auth/admin.directory.group.readonly`, you can read more information here:

https://dexidp.io/docs/connectors/google/
