### ISSUE TITLE
Helm install terrakube-dex deployment didnt has volumemount for /etc/secrets/gcp-credentials.json

### ISSUE THREAD

**Issue by rchekhina** [AzBuilder/terrakube#1046]
### Bug description 🐞

When I deploy terrakube with helm the secret terrakube-dex-secrets is created and the volume is present on the terrakube-dex deployment but there is no volumemount for this this secret

### Steps to reproduce

do the installation with helm and look the volumemounts on the terrakube-dex deployment:
it is :
        volumeMounts:
        - mountPath: /etc/dex
          name: config
          readOnly: true
          
 and should be something like this:
 
         volumeMounts:
        - mountPath: /etc/dex
          name: config
          readOnly: true
        - mountPath: /etc/secrets/gcp-credentials.json
          name: gcp-credentials
          readOnly: true
          subPath: gcp-credentials

**Comment by alfespa17** [comment]
This is not really a bug you need to mount that file inside dex to make it work
