### ISSUE TITLE
Possible to include token ID in the response to create

### ISSUE THREAD

**Issue by stanleyz** [AzBuilder/terrakube#1086]
### Feature description 💡

The token API returns only token, which is fine if people uses the UI, but when we create token programatically, it's hard to index them without the unique ID, yet there doesn't seems another combination in the database that could uniquely identify a token except the ID, for example hard to write a Terraform resource to manage tokens.

https://github.com/AzBuilder/terrakube/blob/150824d031394c3f5ef1d552c7887ccca55525fe/api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenController.java#L36

**Comment by alfespa17** [comment]
If you decode the token you will see the id in the "kid" property inside the json if I remember correctly.

https://github.com/AzBuilder/terrakube/blob/150824d031394c3f5ef1d552c7887ccca55525fe/api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenService.java#L59

https://github.com/AzBuilder/terrakube/blob/150824d031394c3f5ef1d552c7887ccca55525fe/api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenService.java#L71

Another option will be to just include the id in the response. If anyone would like to help with this, all pull request are welcome.

**Comment by stanleyz** [comment]
Thanks @alfespa17 for pointing out the direction. It turns out the JPA generates a new UUID when saving after the JWT is generated, I've raised a PR to fix this. Feel free to update if you need to.
