### ISSUE TITLE
terraform cli speculative plan is not working for a private ssh git workspace

### ISSUE THREAD

**Issue by rajnekkanti** [AzBuilder/terrakube#1118]
### Bug description 🐞

Terraform cli speculative plan doesn't show intended changes for a private ssh git vcs workspace. The only time terraform cli shows desired plan changes when you did git commit and push to configured branch on VCS workspace. Terraform working directory is a folder in repo. The repo has multiple terraform folders. 
├── dev
├── prod
└── stage

Each folder structure is simple and doesn't use any local modules
├── backend.tf
├── main.tf
├── outputs.tf
├── provider.tf
├── variables.tf
└── versions.tf

Terrakube version: 2.21.1
Terrakube runs in EKS 1.27 cluster

### Steps to reproduce

1. Create a workspace
    Iac - Terraform
    workflow - version control workflow
    version control provider - SSH Git
    Execution Mode: Remote
    Default template when doing a git push to the repository: No selection
   Executor agent to run the job: Default

### Expected behavior

terraform cli speculative plan should show desired plan for locally changes and won't need to do git commit and push to configured workspace branch

### Anything else?

Is there a documentation with example on how to use VCS workflow and CLI workflow together?
Is there a troubleshooting documentation on how to retrieve a zip file when ran cli plan?

**Comment by alfespa17** [comment]
You can check the following:

https://github.com/AzBuilder/terrakube/issues/1015#issuecomment-2194946580

The above should work for VCS driven workspaces but for the ones that are connected using SSH I don't think that will work I never tested the feature with SSH connected workspaces

**Comment by rajnekkanti** [comment]
@alfespa17 thanks for the reply. Yes, backend config defined and still don't work. We had to use SSH method since Terrakube has no option for Bitbucket Server. Will this be supported in near future? Thanks!

**Comment by alfespa17** [comment]
> @alfespa17 thanks for the reply. Yes, backend config defined and still don't work. We had to use SSH method since Terrakube has no option for Bitbucket Server. Will this be supported in near future? Thanks!

There is an open issue about that

https://github.com/AzBuilder/terrakube/issues/612

**Comment by rajnekkanti** [comment]
Seems Bitbucket Server support is not in near road map. Can this be implemented in Q3? or fix this for generic private git SSH?

**Comment by alfespa17** [comment]
> Seems Bitbucket Server support is not in near road map. Can this be implemented in Q3? or fix this for generic private git SSH?

I will try to fix the issue with ssh I guess it wont be a huge change, maybe I can do it this week before we release version 2.22.0

**Comment by rajnekkanti** [comment]
Hi @alfespa17, thanks for the fix. I see https://github.com/AzBuilder/terrakube/releases/tag/2.22.0 is out now but doesn't seem new helm chart (https://github.com/AzBuilder/terrakube-helm-chart/tags) published with this version. Do we know when will new chart be published?

**Comment by alfespa17** [comment]
I still have to update the helm chart with the new version but you can override the version of the deployment using something like this:

```
api:
  version: "2.22.0"

executor:
  version: "2.22.0"

registry:
  version: "2.22.0"

ui:
  version: "2.22.0"
```
