### ISSUE TITLE
lower the permission required for creation of tags

### ISSUE THREAD

**Issue by stanleyz** [AzBuilder/terrakube#1145]
### Feedback

The tags are quite useful and in UI there is a way to tag workspace directly without going to organisation settings, but the tag is set to require superuser for any update/create option, possible to lower it to something like:

* create is allowed by teams who can manage workspaces, 
*  update and delete are restricted to superuser

**Comment by alfespa17** [comment]
hello @stanleyz 

You can type the "tag" in this part and just press "enter" to add a new one.

![image](https://github.com/user-attachments/assets/c9d0e842-443e-4773-b6f6-cd5552ea0449)

Once you type enter you should see the new values here.

![image](https://github.com/user-attachments/assets/40c8826d-a653-48b9-95bf-15c9ace251d8)

**Comment by alfespa17** [comment]
We didn't put any restriction to create tags in this part of the code as you can see here, so if you are authenticated and have access to the org you should be able to put some tags there.

https://github.com/AzBuilder/terrakube/blob/6f9a248cfe47a9ecb508cfe62846861c67ad5fe6/api/src/main/java/org/terrakube/api/rs/tag/Tag.java#L18

Is different for example from this part of the code that has some restriccions using [elide permissions](https://elide.io/pages/guide/v7/03-security.html#:~:text=new%20SecurityContext.-,Permission%20Annotations,-The%20permission%20annotations)

https://github.com/AzBuilder/terrakube/blob/6f9a248cfe47a9ecb508cfe62846861c67ad5fe6/api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java#L30

**Comment by stanleyz** [comment]
ah, yes. you are right. Somehow the tag on workspaces doesn't work on my local test instance, I'll take a look.

I was probably looking at globalvar but talking about tags.
