### ISSUE TITLE
"Invalid run ID" error when applying Plan file

### ISSUE THREAD

**Issue by ehuizar1028** [AzBuilder/terrakube#1166]
### Bug description 🐞

When running `terraform plan -out myPlan.tfplan`, then running `terraform apply myPlan.tfplan` - the following errors outputs

`Error: couldn't load the provided path as either a local plan file (zip: not a valid zip file) or a saved cloud plan ("invalid run ID")`

This looks like an issue possibly with the way terraform creates a cloud plan, or the way terrakube processes the cloud plan. When attempting to run this, I turn on debugging on terraform and view the logs in Terrakube, and I see no connection attempts to the Terrakube API. 

Although, if I tweak the plan output to use a run_id with a `run` prefix (ie: `run_id: "run-50"`) the request does follow through to the API, I can see the error in the logs `Failed to convert value of type 'java.lang.String' to required type 'int'`

So this tells me that either the terraform binary does not like the ID format, Terrakube is not processing the format correctly, or both. 

For more context, I am attempting to integrate Atlantis with Terrakube, and this seems to be the only flaw so far that I found during the integration. Atlantis uses these plan files, so the integration is broken at the point of apply (although plans do work)

I have tried with various versions of Terraform just in case it's a versioning issue. 

### Steps to reproduce

terraform {
  cloud {YOUR CLOUD CONFIG HERE}
  workspaces = {YOUR WORKSPACE CONFIG HERE}
}

resource "null_resource" "test" {
  triggers = {
    value = "it works!"
  }
}

run commands
terraform plan -out myPlan.tfplan
terraform apply myPlan.tfplan

### Expected behavior

Should apply smoothly.

**Comment by alfespa17** [comment]
I guess that if you go to the workspace settings and change the execution mode to "local" it should work because terraform only uploads the state to Terrakube.

If you use the "remote" execution that will require some work because that will require us to implement some missing method or add some missing logic or properties to the API responses

**Comment by ehuizar1028** [comment]
@alfespa17 thanks! yes we planned on  trying local execution, but we have plans to use self-hosted agents once this is fixed.

**Comment by alfespa17** [comment]
I partially fix this, now when running the plan the file will have the correct information.

```
{"remote_plan_format":1,"run_id":"run-116","hostname":"terrakube-api.minikube.net"}
```

I will check next week maybe I can see the require missing logic to run the apply from terraform/tofu CLI

**Comment by alfespa17** [comment]
I created a new release where this feature is available if anyone would like to test it

[2.23.0-beta.1](https://github.com/AzBuilder/terrakube/releases/tag/2.23.0-beta.1)
