### ISSUE TITLE
When running multiple jobs simultaneously, the execution gets mixed up.

### ISSUE THREAD

**Issue by hohoonsong** [AzBuilder/terrakube#1170]
### Bug description 🐞

When triggering a job through the UI, if multiple jobs are open in the browser, the "WORKSPACE_ARCHIVE" in local storage can get mixed up, leading to the wrong job being executed. When triggering a job through the UI, the API should be called by parsing the current tab's URL rather than relying on the value in local storage.

### Steps to reproduce

1. Open multiple workspaces in a single browser.
2. Trigger multiple workspaces without refreshing.

### Expected behavior

The correct job for each workspace should be executed.

**Comment by alfespa17** [comment]
Fixed in #1267
