### ISSUE TITLE
Environment Variable Character Limit

### ISSUE THREAD

**Issue by tthrone-atomic** [AzBuilder/terrakube#1208]
### Bug description 🐞

When creating an environment variable to enable ephemeral executors, we receive an error from the API. 

`{"errors":[{"detail":"ERROR: value too long for type character varying(32)"}]}`

It appears the global (and likely the workspace) environment variables have a small character limit. Too small to apply the required variable for enabling ephemeral executors.

### Steps to reproduce

1. Create global variable "TERRAKUBE_ENABLE_EPHEMERAL_EXECUTOR" with value "1"
2. Click "Save Global Variable"
3. Observe the form is stuck and there is a network error to the organizations "globalvar" endpoint.

### Expected behavior

Global variable to be accepted accepting 1000+ characters in name (OS limits are very big, I don't see a reason this should be restrictively small).

**Comment by alfespa17** [comment]
Hello @tthrone-atomic 

As a workaround you can add TERRAKUBE_ENABLE_EPHEMERAL_EXECUTOR at workspace level, that should work

![image](https://github.com/user-attachments/assets/a3e844c1-9899-4d8b-be5f-550e8edbf430)

I will create a pull request to change the size for the global variables

**Comment by alfespa17** [comment]
By the way it is working correctly at workspace level because the size is 64 characters

https://github.com/AzBuilder/terrakube/blob/974f15f7acb060df1b4c7d112fce9774a9a83c68/api/src/main/resources/db/changelog/local/changelog-2.21.0-gcp-dynamic.xml#L10
