### ISSUE TITLE
publishing provider via api not working 404

### ISSUE THREAD

**Issue by khaounen** [AzBuilder/terrakube#1244]
### Bug description 🐞

Hi @alfespa17 and thank you for the detailed documentation you added to publish a private provider https://github.com/AzBuilder/docs/blob/main/user-guide/private-registry/using-providers.md

I've tried it today but I'm getting a 404 error, not sure from where comes this error 

```code
user@MacBook-Pro-de-Test terrakube-helm-chart % curl -XPOST https://terrakube-api.awnen.com/organizations/140206a1-b498-4a04-840c-ed1e3c8cdf37/provider -H "Content-Type: application/vnd.api+json" -H "Authorization: Bearer xxxxxxx" -d '{
    "data": {
        "type": "provider",
        "attributes": {
          "name": "random",
          "description": "random provider"
        }
    }
}'
{"timestamp":"2024-08-30T14:23:30.391+00:00","status":404,"error":"Not Found","path":"/organizations/140206a1-b498-4a04-840c-ed1e3c8cdf37/provider"}
````
### Steps to reproduce

Go to user settings -> create an api token and generate API TOKEN to call the api 

Create an organization 

Create provider inside organization

```code
curl -XPOST https://terrakube-api.awnen.com/organizations/<PASTE ORGANISATION ID HERE>/provider -H "Content-Type: application/vnd.api+json" -H "Authorization: Bearer  <PASTE GENERATED API TOKEN>" -d '{
    "data": {
        "type": "provider",
        "attributes": {
          "name": "random",
          "description": "random provider"
        }
    }
}'

```

### Expected behavior

return code status code `200` or `201`maybe?

### Anything else?

I tried to check in the @RestController classes in the api project to find the provider endpoint but couldn't find it? maybe it was moved somewhere else? or removed completely?

**Comment by alfespa17** [comment]
Hello @khaounen the correct path is

`https://terrakube-api.awnen.com/api/v1/organizations/140206a1-b498-4a04-840c-ed1e3c8cdf37/provider`

**Comment by alfespa17** [comment]
By the way you didnt find any `RestController` because for some part of the code we are using [elide](https://elide.io/) so we only define the database entity and the framework takes care of generating all the CRUD endpoints

**Comment by khaounen** [comment]
Thank you again for your quick reply I'm getting "Unknow Collection Organization" in the response now,
Is this because of the organization ID I copied from the URL?
This is the the URL to access my org https://terrakube-ui.awnen.com/organizations/140206a1-b498-4a04-840c-ed1e3c8cdf37/workspaces

So I used `140206a1-b498-4a04-840c-ed1e3c8cdf37` as organization ID, isn't this correct?

```code
curl -XPOST https://terrakube-api.awnen.com/api/v1/organizations/140206a1-b498-4a04-840c-ed1e3c8cdf37/provider -H "Content-Type: application/vnd.api+json" -H "Authorization: Bearer xxxxxx" -d '{
    "data": {
        "type": "provider",
        "attributes": {
          "name": "random",
          "description": "random provider"
        }
    }
}'
{"errors":[{"detail":"Unknown collection organizations"}]}
```

**Comment by alfespa17** [comment]
It is `organization` not `organizations` in the path

**Comment by khaounen** [comment]
Oh my bad! its fixed but looks like the user I'm connecting with (member of TERRAKUBE_ADMIN) doesn't have the right to create the provider in the organization

```code
{"errors":[{"detail":"CreatePermission Denied"}]}
```
Maybe another group needed for this?

**Comment by alfespa17** [comment]
> TERRAKUBE_ADMIN

The TERRAKUBE_ADMIN group can only manage teams and create organization inside Terrakube,

If you want to use that team to manage workspace, providers, modules, etc you will have to add that team to the teams organization setting.

You can follow this:

https://docs.terrakube.io/user-guide/organizations/team-management

**Comment by khaounen** [comment]
Ok great! thank you again, I'm closing my ticket as there is no bug from the api side, its more from the post I was doing, thank you again, I'll check the doc and give it a try later
