### ISSUE TITLE
Workspace viewer role

### ISSUE THREAD

**Issue by KamranBiglari** [AzBuilder/terrakube#1332]
### Feature description 💡

Is it possible to add a feature to have viewer role for workspace?
I want to have a team with least permission to just view and read the state without writing/modifying or execute.

OTF has this feature: https://docs.otf.ninja/latest/rbac/#permissions

**Comment by alfespa17** [comment]
Hello @KamranBiglari 

If you add a team and you `unselect all options` and just click save it will be like a reader role, I think that should work for you

![image](https://github.com/user-attachments/assets/0a63a248-3b5a-401c-a69c-94fa129316c5)

**Comment by alfespa17** [comment]
From Terrakube 2.23.0-beta.3 there is a new permission called "Manage State"

![image](https://github.com/user-attachments/assets/3510afad-555f-49ec-9e0f-38f28caaee90)

Once disable you wont be able to see the state in the UI.

![image](https://github.com/user-attachments/assets/6bb2a555-ea4c-4b95-8ed4-98ce0ba96001)

**Comment by alfespa17** [comment]
Additionally if you disable "Manage State" all options will be disabled in this page

![image](https://github.com/user-attachments/assets/e2e76886-a50b-4120-a78e-06ec8da4b297)

**Comment by alfespa17** [comment]
I am closing this issue, in the in version 2.24.0 you can disable job execution and see the state using the following.

![image](https://github.com/user-attachments/assets/afb7fdd4-a01d-4267-9061-2b6c098fd5b8)
