### ISSUE TITLE
Resources and Outputs not showing in workspace UI using 2.23.0

### ISSUE THREAD

**Issue by WladyX** [AzBuilder/terrakube#1342]
### Bug description 🐞

I seem to be missing the resources 
![CleanShot 2024-09-29 at 16 53 51@2x](https://github.com/user-attachments/assets/2d0f3765-7beb-46e1-bd5a-edfe859efbbc)

### Steps to reproduce

- installed TK with helm, but used custom psql & custom minio & moved everything to existing secrets

### Expected behavior

I should be able to see the resources

### Anything else?

I have tried tf destroy & tf apply, they just don't show up.
This happens for a custom repo also.
The state is ok and I can see the resources in the State tab, but nothing under resources & output.
Nothing relevant (from what I can tell) in the logs.
Anything I can do to debug this?
Thank you for this nice tool, looks very promising at first glance.

**Comment by alfespa17** [comment]
Hello @WladyX what terrakube version are you using?

**Comment by alfespa17** [comment]
I just tested and you are right I cant see the resources, not sure why, I will have to check

![image](https://github.com/user-attachments/assets/57818ed7-b975-49bd-b850-c166a18afcf2)

**Comment by alfespa17** [comment]
Hello @stanleyz, can you help me with this issue? I found the following when I was checking

It is related to the feature you added some days ago https://github.com/AzBuilder/terrakube/pull/1313.

This line return the correct values.
https://github.com/AzBuilder/terrakube/blob/bf837243f82e3a3e760e26cb295262d05ee39e25/ui/src/domain/Workspaces/Details.jsx#L385

Example:

```
{
    "manageState": true,
    "manageWorkspace": true,
    "manageModule": true,
    "manageProvider": true,
    "manageVcs": true,
    "manageTemplate": true
}
```

It is showing the correct values from this particular team.

![image](https://github.com/user-attachments/assets/5a7e95da-367e-4e91-a2d1-4f35a4503b34)

Checking in this line, the value for "manageState" is always false

https://github.com/AzBuilder/terrakube/blob/bf837243f82e3a3e760e26cb295262d05ee39e25/ui/src/domain/Workspaces/Details.jsx#L1722

If I hard coded the value to "true" just for testing I can see all the values in the UI.

![image](https://github.com/user-attachments/assets/a86f7103-18ed-4ceb-a088-541714fd23f5)

![image](https://github.com/user-attachments/assets/b65dd620-a3b7-4f87-9729-ccac61f9cf37)

**Comment by alfespa17** [comment]
Hello @WladyX  this issue is fixed in version 2.23.1.

**Comment by WladyX** [comment]
Great work, thank you @alfespa17 !

**Comment by stanleyz** [comment]
> Hello @stanleyz, can you help me with this issue? I found the following when I was checking

Sorry, didn't check my email until now. Thanks for picking to up @alfespa17 , sorry about that.
