### ISSUE TITLE
update docs about executor provider cache

### ISSUE THREAD

**Issue by WladyX** [AzBuilder/terrakube#1343]
### Feature description 💡

Would be nice if the executor could cache the providers, aws for example takes a lot of time to install.

**Comment by alfespa17** [comment]
Hello @WladyX I think you can add the following configuration:

https://developer.hashicorp.com/terraform/cli/config/config-file#provider-plugin-cache

Setting the environment variable inside the workspace settings or using global variables in the organization and finally mount some volume to the container for the folder `plugin-cache`

```
TF_PLUGIN_CACHE_DIR="/home/cnb/.terraform.d/plugin-cache"
```

By the way I didnt test the above but I think it might work

**Comment by alfespa17** [comment]
Yeah I will add some comment in the docs, after that I will close this one

**Comment by alfespa17** [comment]
Documentation is added @WladyX 

https://docs.terrakube.io/user-guide/workspaces/provider-cache
