### ISSUE TITLE
Workspace lock description

### ISSUE THREAD

**Issue by iam-take** [AzBuilder/terrakube#1358]
### Feature description 💡

It would be great if we could set a description when enabling the lock on a workspace to give context to the team why a workspace is locked. Perhaps this description can be shown as well in the error shown by Terraform to the end user.

**Comment by alfespa17** [comment]
I can add the lock description to the UI in the workspace overview but I don't think I can add the description to the terraform error because the message from terraform CLI is not really showing the message error from the API response

For example, terraform shows the following:

```shell
user@pop-os:~/git/simple-terraform$ terraform plan
╷
│ Error: Error acquiring the state lock
│ 
│ Error message: workspace already locked (lock ID: "simple/locked-local")
│ Lock Info:
│   ID:        b624d3b4-c763-fe4c-8c7e-2bac7ff6220b
│   Path:      
│   Operation: OperationTypePlan
│   Who:       user@pop-os
│   Version:   1.5.7
│   Created:   2024-09-04 19:10:17.557721232 +0000 UTC
│   Info:      
│ 
│ 
│ Terraform acquires a state lock to protect the state from being written
│ by multiple users at the same time. Please resolve the issue above and try
│ again. For most commands, you can disable locking with the "-lock=false"
│ flag, but this is not recommended.
```

But the message from the API response is the below.

```json
{
    "errors": [
        {
            "status": "409",
            "title": "conflict",
            "detail": "Unable to lock workspace. The workspace is already locked."
        }
    ]
}
```

**Comment by iam-take** [comment]
> I can add the lock description to the UI in the workspace overview but I don't think I can add the description to the terraform error because the message from terraform CLI is not really showing the message error from the API response
> 
> For example, terraform shows the following:
> 
> ```shell
> user@pop-os:~/git/simple-terraform$ terraform plan
> ╷
> │ Error: Error acquiring the state lock
> │ 
> │ Error message: workspace already locked (lock ID: "simple/locked-local")
> │ Lock Info:
> │   ID:        b624d3b4-c763-fe4c-8c7e-2bac7ff6220b
> │   Path:      
> │   Operation: OperationTypePlan
> │   Who:       user@pop-os
> │   Version:   1.5.7
> │   Created:   2024-09-04 19:10:17.557721232 +0000 UTC
> │   Info:      
> │ 
> │ 
> │ Terraform acquires a state lock to protect the state from being written
> │ by multiple users at the same time. Please resolve the issue above and try
> │ again. For most commands, you can disable locking with the "-lock=false"
> │ flag, but this is not recommended.
> ```
> 
> But the message from the API response is the below.
> 
> ```json
> {
>     "errors": [
>         {
>             "status": "409",
>             "title": "conflict",
>             "detail": "Unable to lock workspace. The workspace is already locked."
>         }
>     ]
> }
> ```

I see, I would already be happy if we have a description in the portal :)

**Comment by juan-vg** [comment]
Just to provide some TFC context:

While it's true the lock reason is displayed in the TFC UI when you navigate to Locking section, it's displayed nowhere else. As @alfespa17 pointed, even the CLI is not displaying it.
![imagen](https://github.com/user-attachments/assets/6d0db5c1-2f3b-4ac9-a6c8-b6febb3eb071)

On top, the lock reason can only be provided to TFC by the API. I've found no way of doing so through the UI.

**Comment by alfespa17** [comment]
> Just to provide some TFC context:
> 
> While it's true the lock reason is displayed in the TFC UI when you navigate to Locking section, it's displayed nowhere else. As @alfespa17 pointed, even the CLI is not displaying it. ![imagen](https://private-user-images.githubusercontent.com/17771395/382828206-6d0db5c1-2f3b-4ac9-a6c8-b6febb3eb071.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Mzc4MTcsIm5iZiI6MTczMDczNzUxNywicGF0aCI6Ii8xNzc3MTM5NS8zODI4MjgyMDYtNmQwZGI1YzEtMmYzYi00YWM5LWE2YzgtYjZmZWJiM2ViMDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE2MjUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMWU3OGJkNzQ2YjFhNWRkNjk4Y2ExMzE3YmRlZDEwOTk4NGZlNGZmN2UwNjU4OGU3NTExYTQxMGM0ZDQzMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dnVhKFPpk_HOQVntnlAN53SpM9Nkbf6cun-S0A7v96M)
> 
> On top, the lock reason can only be provided to TFC by the API. I've found no way to do so through the UI.

This is what I am planning to do, put some message in the UI that shows the lock reason
