### ISSUE TITLE
Workspace view remains filtered after changing screens but no filter text is shown

### ISSUE THREAD

**Issue by iam-take** [AzBuilder/terrakube#1359]
### Bug description 🐞

If you filter the workspaces in the UI and change the screen to another page any page the filtering stays active. However the filter text is disappeared but active. Pressing enter again will reset the filter and shows all workspaces. It is mostly confusing that the filter is active but now showing. 

![image](https://github.com/user-attachments/assets/a7155499-f294-4b21-a989-887cac4b8349)
In this example you can see I have no filter text but only 2 workspaces showing. However this organization has a lot more workspaces present.

### Steps to reproduce

* Filter the workspace view
* Go to another page in Terrakube 
* Go back to the workspace view
* Filter remains active

### Expected behavior

Filter to be either gone after changing pages in Terrakube or the filter text to be shown. I would prefer myself that the filter is reset.

**Comment by Avinashs7** [comment]
Can you assign this to me!
Also could you please add the hacktoberfest tag

**Comment by alfespa17** [comment]
> Can you assign this to me! Also could you please add the hacktoberfest tag

done @Avinashs7

**Comment by Avinashs7** [comment]
Hello @alfespa17 
I have raised a PR but it has failed in build jammy, I have no idea about it
So, did I mess up something or do I have to raise new PR.

**Comment by Avinashs7** [comment]
Hello @alfespa17 
It is showing some error in build, do I have to raise new PR

**Comment by alfespa17** [comment]
> Hello @alfespa17 It is showing some error in build, do I have to raise new PR

Dont worry, I will check the PR tomorrow, I guess it was the sonar cloud analysis but that thing always fails for external contributors

**Comment by Avinashs7** [comment]
@alfespa17 Thanks for the clarification.
