### ISSUE TITLE
missing state diagram on local runs

### ISSUE THREAD

**Issue by WladyX** [AzBuilder/terrakube#1362]
### Bug description 🐞

If i run a workspace locally in the runs I see a dummy state uploaded title, but the issue is that in the states for that run the diagram is empty, the code is there, but no diagram.
![CleanShot 2024-10-04 at 08 28 53@2x](https://github.com/user-attachments/assets/ab96d526-c77d-46b5-af4f-40fa36efcdd4)

### Steps to reproduce

- clone sample_simple repo
- set the workspace to execute locally
- update tf code to connect to terrakube
- run tf apply
- check state diagram for that run

### Expected behavior

We should be able to see the diagram for locally execution, since the code is there and TK has access to the state so that it can render it.

### Anything else?

Thank you for sharing this cool tool!

**Comment by alfespa17** [comment]
Hello @WladyX 

If you are using the test data, the sample_simple workspace is a "VCS workspace"

![image](https://github.com/user-attachments/assets/dc065c50-ecd7-4c1f-88df-7df0c2c15627)

If you want to use the CLI to run terraform locally you need to us a "CLI driven workflow"

![image](https://github.com/user-attachments/assets/b8e07a5c-0948-41e2-a082-fedaa594c26e)

I tested with a CLI driven workflow using local execution and I can see the diagram

![image](https://github.com/user-attachments/assets/7deb503f-54ec-4090-96d9-922208129372)

**Comment by WladyX** [comment]
Yeah, i know that, but you can use the CLI for VCS workspaces also, like in this issue https://github.com/AzBuilder/terrakube/issues/661, right?
That's what I am doing, running a CLI workflow on a VCS workflow (with local execution), which works, except for the diagram part.

**Comment by alfespa17** [comment]
> Yeah, i know that, but you can use the CLI for VCS workspaces also, like in this issue #661, right? That's what I am doing, running a CLI workflow on a VCS workflow (with local execution), which works, except for the diagram part.

You can use it but just for running the `terraform plan`

**Comment by WladyX** [comment]
it works for me:
```
cat main.tf
terraform {
  backend "remote" {
    hostname     = "terrakube-api.example.com"
    organization = "simple"
    workspaces {
      name = "sample_simple"
    }
  }
}

# This resource will destroy (potentially immediately) after null_resource.next
resource "null_resource" "previous" {}

module "time_module" {
  source = "./module"
}

resource "time_sleep" "wait_30_seconds" {

  depends_on = [null_resource.previous]

  create_duration = local.time
}

# This resource will create (at least) 30 seconds after null_resource.previous
resource "null_resource" "next" {
  depends_on = [time_sleep.wait_30_seconds]
}

output "creation_time" {
  value = time_sleep.wait_30_seconds.create_duration
}
```
```
tofu apply                                                                                                                  6.677s
module.time_module.random_integer.time: Refreshing state... [id=5]
null_resource.previous: Refreshing state... [id=5852691201331156757]
time_sleep.wait_30_seconds: Refreshing state... [id=2024-09-29T13:52:39Z]
null_resource.next: Refreshing state... [id=4607145691712263326]

No changes. Your infrastructure matches the configuration.

OpenTofu has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

creation_time = "5s"
```

which is great :)

**Comment by alfespa17** [comment]
Not sure if we can call that a bug or a feature XD , because what I added in https://github.com/AzBuilder/terrakube/issues/661 is support for [speculative plans](https://developer.hashicorp.com/terraform/cloud-docs/run/remote-operations#speculative-plans) so you can check the possible changes using the CLI before doing a push to the repository.


In TFC when you have a VCS workspace  like this

![image](https://github.com/user-attachments/assets/67ca712f-cc65-45e3-8c2e-f39e4c447b64)

you will get the following when running a apply

```
λ terraform apply
╷
│ Error: Apply not allowed for workspaces with a VCS connection
│
│ A workspace that is connected to a VCS requires the VCS-driven workflow to ensure that the VCS remains the single
│ source of truth.
╵
```

You can only execute a plan like:
```

λ terraform plan
Running plan in HCP Terraform. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/alfespa17/simple-terraform/runs/run-sWog3YTpBrM4mzq1

Waiting for the plan to start...

Terraform v1.9.7
on linux_amd64
Initializing plugins and modules...

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.next will be created
  + resource "null_resource" "next" {
      + id = (known after apply)
    }

  # null_resource.previous will be created
  + resource "null_resource" "previous" {
      + id = (known after apply)
    }

  # time_sleep.wait_30_seconds will be created
  + resource "time_sleep" "wait_30_seconds" {
      + create_duration = (known after apply)
      + id              = (known after apply)
    }

  # module.time_module.random_integer.time will be created
  + resource "random_integer" "time" {
      + id     = (known after apply)
      + max    = 5
      + min    = 1
      + result = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + creation_time = (known after apply)
  + fake_data     = {
      + data     = "Hello World"
      + resource = {
          + resource1 = "fake"
        }
    }

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if
you run "terraform apply" now.

```

I guess I will have to add some missing property in the Terrakube API to show the same error from TFC when trying to run a apply

`Apply not allowed for workspaces with a VCS connection`

**Comment by WladyX** [comment]
Leave it as a feature please :)
Maybe add a feature toggle in the workspace settings, like `Allow remote apply`.

**Comment by alfespa17** [comment]
> Leave it as a feature please :) Maybe add a feature toggle in the workspace settings, like `Allow remote apply`.

I don't think this could be a feature because in the end it when you are using a VCS workflow the GIT repository should be the single source of truth, for now I will just close this one because the state it is showing correctly when you are using the VCS and CL I workflow correctly

**Comment by WladyX** [comment]
> I don't think this could be a feature because in the end it when you are using a VCS workflow the GIT repository should be the single source of truth, for now I will just close this one because the state it is showing correctly when you are using the VCS and CL I workflow correctly

Fair enough, thank you @alfespa17 !

**Comment by joshbooks** [comment]
> > Leave it as a feature please :) Maybe add a feature toggle in the workspace settings, like `Allow remote apply`.
> 
> I don't think this could be a feature because in the end it when you are using a VCS workflow the GIT repository should be the single source of truth, for now I will just close this one because the state it is showing correctly when you are using the VCS and CL I workflow correctly

Any chance the saved plan could be enabled without allowing apply? My use case is trying to use terravision, which uses the saved plan as its input. Any chance there's a workaround for this case where I need to save the plan output but not for apply purposes?

**Comment by alfespa17** [comment]
> > > Leave it as a feature please :) Maybe add a feature toggle in the workspace settings, like `Allow remote apply`.
> > 
> > 
> > I don't think this could be a feature because in the end it when you are using a VCS workflow the GIT repository should be the single source of truth, for now I will just close this one because the state it is showing correctly when you are using the VCS and CL I workflow correctly
> 
> Any chance the saved plan could be enabled without allowing apply? My use case is trying to use terravision, which uses the saved plan as its input. Any chance there's a workaround for this case where I need to save the plan output but not for apply purposes?

Hello @joshbooks I guess you can get the plan file sending a request to

`GET /api/v1/workspace/{workspaceId}/job/{jobId}`

There is a property `terraformPlan` that you can use to download the file
