### ISSUE TITLE
Missing ARM64 support in some Terrakube Docker image tags

### ISSUE THREAD

**Issue by ilkerispir** [AzBuilder/terrakube#1364]
### Bug description 🐞

Hello @alfespa17, @jcanizalez , 

Description:
According to the [Terrakube documentation](https://docs.terrakube.io/updates#arm64-support-for-terrakube-images), multi-arch support, including ARM64, is available for Terrakube images. However, not all image tags seem to have ARM64 support, as observed in the Docker repository. For example, the 2.23.2 tag only lists linux/amd64. Could you please confirm if ARM64 support is missing for this and other tags, and if so, when it will be available?

Steps to Reproduce:

Go to the Terrakube API Server image repository.
Check the tags (e.g., [2.23.2](https://hub.docker.com/r/azbuilder/api-server/tags)).
Only linux/amd64 is available in some tags, even though ARM64 support is expected.
Expected Behavior:
The tags should include multi-arch support, specifically for linux/arm64 as mentioned in the documentation.

Additional Information:

Docker Tag: 2.23.2
Compressed Size: 292.05 MB
OS/ARCH: linux/amd64

![image](https://github.com/user-attachments/assets/8231e1a4-e8a4-4a93-a626-411930b64f57)

### Steps to reproduce

-

### Expected behavior

-

### Example repository

-

### Anything else?

-

**Comment by alfespa17** [comment]
The build for arm64 failed

https://github.com/AzBuilder/terrakube/actions/runs/11166932411

Maybe @jcanizalez can check when he has some free time.

**Comment by ilkerispir** [comment]
Hello @alfespa17,

I created a PR about this issue. Could you please review it when you're available? As the error message says, there is no space on the disk, so I added caching for Maven packages.

PR: https://github.com/AzBuilder/terrakube/pull/1365

**Comment by alfespa17** [comment]
Image are now available @ilkerispir 

![image](https://github.com/user-attachments/assets/b1de6880-bf6c-47f1-b988-497082ba41aa)
