### ISSUE TITLE
Update Jedis Client from 4.4.8 to version 5.X

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#1390]
### Feature description 💡

We have been using jedis client 4.4.8 but we need to change the code to use version 5.X

### Anything else?

N/A

**Comment by dawidmalina** [comment]
@alfespa17 i was able to update Jedis to 5.1.5 without any code changes. All tests are successful and no issues running locally built docker images. Can you share what kind of code changes you have in mind?

**Comment by alfespa17** [comment]
Hello @dawidmalina I long long time ago when I developed the log streaming for the `CLI driven workflow` I was not able to use version 5.X because that version didnt include some methods that I was using in version 4.X, recently I received some pulll request that change that logic maybe for that feature maybe that fixed the initial issue that I had and I never had the time to check if updating to a newer version was working correctly

**Comment by dawidmalina** [comment]
Thanks for the background. Feel free to check that update on your end as I definitely did not covered all advanced features.
