### ISSUE TITLE
Issue when displaying plan

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1394]
### Bug description 🐞

When I run a plan without any aws configuration set up i get a dirty plan.

![image](https://github.com/user-attachments/assets/1435e813-d014-4e81-9c07-a8fa4a41c2fb)

### Steps to reproduce

Plan this file without AWS configuration
```
terraform {
  cloud {
    organization = "simple"
    hostname = "your-endpoint"

    workspaces {
      name = "yes"
    }
  }
}
#
provider "aws" {
  region  = "eu-west-1"
}

resource "aws_s3_bucket" "test" {
   bucket = "test_terrakube"
}

# This resource will destroy (potentially immediately) after null_resource.next
resource "null_resource" "previous" {}

resource "time_sleep" "wait_5_seconds" {
  depends_on = [null_resource.previous]

  create_duration = "5s"
}

# This resource will create (at least) 30 seconds after null_resource.previous
resource "null_resource" "next" {
  depends_on = [time_sleep.wait_5_seconds]
}
```

**Comment by alfespa17** [comment]
Just to clarify you are referring to this characters right?

![image](https://github.com/user-attachments/assets/0146f6d9-7cc2-4892-ad25-6d42aa95581c)

**Comment by BenjaminDecreusefond** [comment]
I'm referring to the order of the output plan, I don't know if it is wanted but it seems like a bug to me ? It seems like the output of the error and the normal output are mixed up together

**Comment by alfespa17** [comment]
> I'm referring to the order of the output plan, I don't know if it is wanted but it seems like a bug to me ? It seems like the output of the error and the normal output are mixed up together

I faced something similar when I was using an external redis in some test a while ago, are you using the internal or external redis?

**Comment by BenjaminDecreusefond** [comment]
Internal redis ! Everything is internal :)

**Comment by alfespa17** [comment]
> Internal redis ! Everything is internal :)

It never failed for me like that using the internal components, I will check maybe I can find something but I am not sure if I Will be able to replicate your issue

**Comment by BenjaminDecreusefond** [comment]
I had 0 set up on my executor and just added a provider aws and it failed like that

**Comment by stanleyz** [comment]
I am facing same issue, thinking to raise a PR to redirect error output stream to standard output instead of separating them, normal application including Terraform works by putting the error at the end of the standard output.
