### ISSUE TITLE
Bitbucket repo Webhook connection URL with repeated "https"

### ISSUE THREAD

**Issue by isbig5** [AzBuilder/terrakube#1397]
### Bug description 🐞

Hey guys, i would like to report a bug (dont know if its really a bug, but looks like it)

I'm doing some tests here to finally get rid of terrraform cloud and use terrakube on its place.

When i was setting up my new workspace and attaching the VCS (Bitbucket) to it, i was asking myself why the new commits werent appearing, when i saw this at the webhook section:

When i edited it and removed the repeated https it started working.
I checked some other repos i work with (that are linked to tf cloud, and it creates it normally)

![image](https://github.com/user-attachments/assets/f86165f4-586f-47cd-bca2-7e8a3e240021)

I was using latest version at this time (2.23.2), did a full database wipe and then downgraded to 2.22.0, to check if it was a specific problem of the latest version, but looks like it wasn't.
I'm using the docker compose version of terrakube on an EC2 machine. (I can't use them on kubernetes because i want terrakube to manage/edit/remove my clusters)

### Steps to reproduce

Create a new workspace and put bitbucket as its VCS

### Expected behavior

I expected the correct URL, without repeated https://

**Comment by alfespa17** [comment]
Hello @isbig5I saw something similar some time ago because the docker compose environment variable in the example was wrong. Check this PR

https://github.com/AzBuilder/terrakube/pull/796/files

**Comment by isbig5** [comment]
@alfespa17 Thanks! I changed what you told me and it worked fine.
