### ISSUE TITLE
The States of Workspaces are not active in version 2.23.2.

### ISSUE THREAD

**Issue by ByungsamKong** [AzBuilder/terrakube#1398]
### Bug description 🐞

Previously, when using version 2.22.0, the States of the Workspaces were active, and I could view the states. However, after upgrading to version 2.23.2, the States are no longer active. As a result, I am unable to run terraform init for the affected Workspaces.
![bug_1](https://github.com/user-attachments/assets/8f025a34-eea0-4131-bf13-9d6c27118ce8)
![bug_2](https://github.com/user-attachments/assets/fec80b37-73c2-4d1c-9b12-7641cf1f55b1)

### Steps to reproduce

I performed an upgrade from version 2.22.0 to 2.23.2 using Helm.

**Comment by hohoonsong** [comment]
It is not bug.
I found that team permission for manage state was disabled.

**Comment by ByungsamKong** [comment]
Thanks for letting me know.
