### ISSUE TITLE
Ability to use default AWS Config File for Backend Override

### ISSUE THREAD

**Issue by ehuizar1028** [AzBuilder/terrakube#1411]
### Feature description 💡

I am using AWS Vault Sidecar Injector to inject dynamic credentials into terrakube. We are not able to use static defined credentials. The Vault Sidecar is able to inject the access key/secret key into `~/.aws.config` and the API component is able to read the S3 bucket fine.

The Executor is still attempting to use the access keys defined from the environment variable (`AwsTerraformStateAccessKey`). And it looks like I cannot use IAM Roles bound to the pod due to the Java AWS SDK version (it wouldnt work anyways due to this override). 

Can we add a conditional that allows to NOT use the access keys in the 2 lines below (this would allow terraform to default to either the pod IAM role once the SDK is updated, or default to use the `~/.aws.config` file for my usecase. )

https://github.com/AzBuilder/terrakube/blob/main/executor/src/main/java/org/terrakube/executor/plugin/tfstate/aws/AwsTerraformStateImpl.java#L76-L77

**Comment by alfespa17** [comment]
By the way I think it will be a nice addition to use the backend override without the access key  now that terrakube support [dynamic credentials](https://docs.terrakube.io/user-guide/workspaces/dynamic-provider-credentials/aws-dynamic-provider-credentials) for AWS the provider authentication

**Comment by ehuizar1028** [comment]
@alfespa17 I can test it if you create publish a some development tagged image.

**Comment by alfespa17** [comment]
> @alfespa17 I can test it if you publish a development tagged image.

Sounds good to me, I will try to add the change later today
