### ISSUE TITLE
Question regarding terrakube official documentation

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1412]
### Feedback

Hi !

Sorry for coming back to you again, I have a silly question regarding Terrakube documentation. I see that there is two different section for storage on the documentation
- One for https://docs.terrakube.io/getting-started/deployment/storage-backend
- One for https://docs.terrakube.io/getting-started/deployment/database-backend

I'm wondering if we need to set up both of these. If I set the postgresql db for the API will the workspaces states be stored in the DB or I do need to set up the storage back-end as well. 

Also if the storage-backend stores workspace's backend, what is the default location for workspace state when the storage-backend is not set up ?

In fact, what's the actual difference between `Storage backend` and `Database backend` ?
Regards !

**Comment by alfespa17** [comment]
I hope this can answer your question:

We use it for 2 different purposes.

`Storage backend` is used to save all the terraform state file, terraform logs files, terraform state history files, terraform modules zip files.

`Database backend` is used to save the information about workspaces, jobs, modules, teams, etc

**Comment by BenjaminDecreusefond** [comment]
Ok thanks for your feedback !
