### ISSUE TITLE
Issues with private registry github app

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1431]
### Feedback

Hi!

We are trying to set up the private registry with a github app and we are facing issue regarding the app.
We followed this [https://docs.terrakube.io/user-guide/vcs-providers/github-app](doc) to create the VCS provider with the following parameter
- We named the app Terrakube (OrganizationName)
- Set the home page url to our api url endpoint
- set the correct privilege for the app
- generated the private key and put it into terrakube with the correct pkcs8 format
- and allowed it on all our repos

we then followed this [https://docs.terrakube.io/user-guide/private-registry/publishing-private-modules](documentation) to set up the module. We set the following parameter
- github url to the repo that stores the modules
- set a prefix tag for the repo
- base path for the module is /modules/mymodule/
When we validate the config it creates the module with the version already present, however when we create a new tag version it is never taken into account by the module and never appear in the UI and we keep having this log in the API logs
```
2024-10-18T18:18:00.242Z  INFO 1 --- [ryBean_Worker-2] o.terrakube.api.rs.module.GitTagsCache   : vcs using GITHUB
2024-10-18T18:18:00.242Z ERROR 1 --- [ryBean_Worker-2] o.t.a.plugin.scheduler.module.CacheJob   : Updating module index for Weezevent/database/aws
2024-10-18T18:18:00.242Z ERROR 1 --- [ryBean_Worker-2] o.t.a.plugin.scheduler.module.CacheJob   : Cannot invoke "org.terrakube.api.rs.vcs.GitHubAppToken.getToken()" because "gitHubAppToken" is null
``` 

It is very strange and we have trouble identifying where it could come from ?
Do you have any clue for us please ? 

Regards ! :)

**Comment by alfespa17** [comment]
Did you install the app in your github organization?

**Comment by BenjaminDecreusefond** [comment]
Yep we did ! We give it privileges to all repositories

**Comment by alfespa17** [comment]
Did you use command for the private key?

`openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in my-terrakube-app.private-key.pem -out pkcs8.key`

**Comment by BenjaminDecreusefond** [comment]
yep we did ! and put the output key from pkcs8.key into the terrakube VCS provider

**Comment by alfespa17** [comment]
Can you create a workspace using the github app and run a plan just to check if the connection is working correctly?

**Comment by BenjaminDecreusefond** [comment]
I just created a VCS workspace, set default path as / in the repository, there is no terraform at the root of the repository but I suppose it tells us that the vcs connection is working correctly ?

**Comment by alfespa17** [comment]
> I just created a VCS workspace, set default path as / in the repository, there is no terraform at the root of the repository but I suppose it tells us that the vcs connection is working correctly ?

Use some folder that has some terraform file, run a `plan `and it should fail but you should be able to see some terraform related error because of some missing parameters related or something like that.

**Comment by BenjaminDecreusefond** [comment]
Just performed what you asked ! I have no issues and the plan display successfully !
<img width="1134" alt="Screenshot 2024-10-18 at 21 38 24" src="https://github.com/user-attachments/assets/63ddc590-0e86-407b-b558-81c8b08ed201">

**Comment by alfespa17** [comment]
Can you try creating a module again?

**Comment by alfespa17** [comment]
I think maybe Terrakube generates the github token correctly when you create a workspace, after creating one workspace your modules creation should work.

I guess there is some logic missing to generate the token if you create a module right after the VCS connection is created

**Comment by alfespa17** [comment]
Just to clarify @BenjaminDecreusefond , module creation is working fine after you tested the workspace creation, right?

**Comment by BenjaminDecreusefond** [comment]
The module creation was working fine before the workspace creation. The issue that I had and that i still have is that now, my module is created on Terrakube with all tags present on the repository. However, if now I push a new tag, Terrakube will never see and don't update the tag list. 
Maybe I can try using a oauth app ?

**Comment by alfespa17** [comment]
XD now I get it sorry

You won't be able to see new tags immediately there is an internal job that refresh tags every five or three minutes

**Comment by BenjaminDecreusefond** [comment]
Oh ! 

It's been 4 hours 😅

**Comment by alfespa17** [comment]
It is related to this issue from some time ago

https://github.com/AzBuilder/terrakube/issues/479#issuecomment-1712316376

**Comment by BenjaminDecreusefond** [comment]
Do you think the error
```
2024-10-18T20:06:00.181Z  INFO 1 --- [ryBean_Worker-9] o.terrakube.api.rs.module.GitTagsCache   : vcs using GITHUB
2024-10-18T20:06:00.182Z ERROR 1 --- [ryBean_Worker-9] o.t.a.plugin.scheduler.module.CacheJob   : Updating module index for Weezevent/certificate/aws
2024-10-18T20:06:00.182Z ERROR 1 --- [ryBean_Worker-9] o.t.a.plugin.scheduler.module.CacheJob   : Cannot invoke "org.terrakube.api.rs.vcs.GitHubAppToken.getToken()" because "gitHubAppToken" is null
2024-10-18T20:06:00.182Z  INFO 1 --- [ryBean_Worker-9] o.terrakube.api.rs.module.GitTagsCache   : vcs using GITHUB
2024-10-18T20:06:00.182Z ERROR 1 --- [ryBean_Worker-9] o.t.a.plugin.scheduler.module.CacheJob   : Updating module index for Weezevent/database/aws
2024-10-18T20:06:00.182Z ERROR 1 --- [ryBean_Worker-9] o.t.a.plugin.scheduler.module.CacheJob   : Cannot invoke "org.terrakube.api.rs.vcs.GitHubAppToken.getToken()" because "gitHubAppToken" is null
```
could have an incidence ?

**Comment by alfespa17** [comment]
Hey @stanleyz do you have any idea about this one? it looks related to the changes related to github app in this class

https://github.com/AzBuilder/terrakube/blob/14a48ca003928a7a6f431d6de18c641fa3607103/api/src/main/java/org/terrakube/api/rs/module/GitTagsCache.java#L181

It looks like a bug but I am not sure

**Comment by BenjaminDecreusefond** [comment]
Happy to help if needed ! :)

**Comment by alfespa17** [comment]
> Happy to help if needed ! :)

By the way using oAuth app should work for you as a work around

**Comment by BenjaminDecreusefond** [comment]
Yep, thank you I think that's what we're going to do for now !

**Comment by BenjaminDecreusefond** [comment]
Great ! I can confirm you it works like a charm with Oauth app ! thanks you very much !

**Comment by BenjaminDecreusefond** [comment]
Btw not sure if it is normal but during debugging I tried to click on the `edit client` button in the VCS providers tab of organization but it seems like nothing happens. I check in the network tab and when I click the button no call are being made so I wonder if this button has been implemented ?
<img width="1388" alt="Screenshot 2024-10-19 at 00 51 51" src="https://github.com/user-attachments/assets/dd59aee3-5e87-433e-98a2-50103a0955fd">
this one ! :)

**Comment by alfespa17** [comment]
> Btw not sure if it is normal but during debugging I tried to click on the `edit client` button in the VCS providers tab of organization but it seems like nothing happens. I check in the network tab and when I click the button no call are being made so I wonder if this button has been implemented ? <img alt="Screenshot 2024-10-19 at 00 51 51" width="1388" src="https://private-user-images.githubusercontent.com/180167280/378028037-dd59aee3-5e87-433e-98a2-50103a0955fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyOTMxOTgsIm5iZiI6MTcyOTI5Mjg5OCwicGF0aCI6Ii8xODAxNjcyODAvMzc4MDI4MDM3LWRkNTlhZWUzLTVlODctNDMzZS05OGEyLTUwMTAzYTA5NTVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQyMzA4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWM2ZGM4MmZmZGY1NTQwYmRlMzZmODJlMzVmOThhNTAxMTIwN2M4N2VkYTlkNWE4YTMxMjBmODA4OThkNjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DrM9qAkevO4ogauhIOf6HEx4XrIZkB6KRCetvLd6itA"> this one ! :)

FYI https://github.com/AzBuilder/terrakube/issues/1096

**Comment by stanleyz** [comment]
> Hey @stanleyz do you have any idea about this one? it looks related to the changes related to github app in this class
> 
> https://github.com/AzBuilder/terrakube/blob/14a48ca003928a7a6f431d6de18c641fa3607103/api/src/main/java/org/terrakube/api/rs/module/GitTagsCache.java#L181
> 
> It looks like a bug but I am not sure

looks like so, will take a look later.

**Comment by BenjaminDecreusefond** [comment]
> > Btw not sure if it is normal but during debugging I tried to click on the `edit client` button in the VCS providers tab of organization but it seems like nothing happens. I check in the network tab and when I click the button no call are being made so I wonder if this button has been implemented ? <img alt="Screenshot 2024-10-19 at 00 51 51" width="1388" src="https://private-user-images.githubusercontent.com/180167280/378028037-dd59aee3-5e87-433e-98a2-50103a0955fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyOTMxOTgsIm5iZiI6MTcyOTI5Mjg5OCwicGF0aCI6Ii8xODAxNjcyODAvMzc4MDI4MDM3LWRkNTlhZWUzLTVlODctNDMzZS05OGEyLTUwMTAzYTA5NTVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQyMzA4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWM2ZGM4MmZmZGY1NTQwYmRlMzZmODJlMzVmOThhNTAxMTIwN2M4N2VkYTlkNWE4YTMxMjBmODA4OThkNjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DrM9qAkevO4ogauhIOf6HEx4XrIZkB6KRCetvLd6itA"> this one ! :)
> 
> FYI #1096

Ah ok I didn't know sorry !
