### ISSUE TITLE
Question regarding storage backend on s3

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1446]
### Feedback

Hi ! 

We have configured an s3 storage backend for our states and we see that states are stored behind their id like `/organizationId/workspaceId`. This is quite complicated for us to determine which state is it because we need to go to the UI to find corresponding state etc...

Is it possible to change the path to use workspace names instead ? And I think in a more general feedback when looking at Drift detection feature here
![image](https://github.com/user-attachments/assets/e1d30850-53a6-43c0-8b80-4520a462d9f0)
It would be nice to have the name displayed rather than the Id so that we can identify immediately who is drifting. I checked on the OPA repository and it looks like only the organizationId and workspaceId are available in context :/ 

Regards !

**Comment by alfespa17** [comment]
Check this comment.

https://github.com/AzBuilder/terrakube-extensions/pull/31#issuecomment-1943705896

**Comment by BenjaminDecreusefond** [comment]
thanks !
