### ISSUE TITLE
Question regarding agent pools

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1448]
### Feedback

Hi ! 

We have a question regarding the agent pools in Terrakube. For instance, as of now we have a self hosted executor configured with an IRSA with correct privileges to apply on our AWS accounts. However, as every workspace are running on the executor technically if a staging workspace want to apply on production, it is allowed to do so. I'd like to know if there's a design in terrakube for executor where we can split that logic so workspaces created in staging env for instance would not be allowed to apply in production ?

Regards

**Comment by alfespa17** [comment]
I am not sure if I understand your question but you can select which executor will execute the job

![image](https://github.com/user-attachments/assets/8f200da0-7114-4d94-9e61-676726178d10)

**Comment by BenjaminDecreusefond** [comment]
Yep you got it ! Not sure how we can add more custom agents ? Should we increase the number of replicas ? And how is the name set ? :)

**Comment by alfespa17** [comment]
You need to use the API directly there is no UI to add an agent

https://github.com/AzBuilder/terrakube/pull/770

**Comment by BenjaminDecreusefond** [comment]
And so multiple agents run on the same executor ?

**Comment by alfespa17** [comment]
> And so multiple agents run on the same executor ?

The job will only run in the "executor agent" that you select, but each executor agent can run many jobs at the same time from different workspaces
