### ISSUE TITLE
Storage backend for states using name instead of id

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1454]
### Feedback

Hi ! 

We have a question regarding storage backend using s3 buckets. We see that for modules its using the name however, when storing the states for workspaces it's using the id. This approach is kind of limited as if our Terrakube installation is down and we need to apply some resources we can't find the state of the concerned source code since it's all hidden behind workspace ids. Is there a way to change how it is stored ?

Regards

**Comment by alfespa17** [comment]
There is no way to change that logic
