### ISSUE TITLE
Run speculative plans on terrakube

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1456]
### Feedback

Hi ! 

I was wondering if it was possible to run [speculative plans](https://developer.hashicorp.com/terraform/cloud-docs/run/remote-operations#speculative-plans) on PR in the same way TFE does ?

regards ! :)

**Comment by alfespa17** [comment]
I think this is what your are looking

https://github.com/AzBuilder/terrakube/pull/644

**Comment by BenjaminDecreusefond** [comment]
Actually what I mean is, let's say I have a VCS workspace. What I'd like is that when folders that are watched by the workspace are updated in a PR from github it runs automatically a speculative plan in Terrakube to be able to preview changes before effectively merging the PR.

**Comment by alfespa17** [comment]
Right now that is not supported, if you want to run a plan you will hace to add the pipeline and use the logic from the above issues to show it

**Comment by BenjaminDecreusefond** [comment]
Ok, thank you !
