### ISSUE TITLE
Null value in column "workspace_id" of relation "job" violates not-null constraint

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1499]
### Bug description 🐞

If you define a tree structure as follow:
```
├── modules
│   └── bucket
│       ├── main.tf
├── staging
│   ├── backend.tf
│   ├── main.tf
│   ├── providers.tf
```

And you refer to the module in modules from the main.tf in `staging/main.tf` terrakube plan will crash as follow:
```
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

The remote workspace is configured to work with configuration at
/projects/04_my_project/staging/ relative to the target repository.

OpenTofu will upload the contents of the following directory,
excluding files or directories as defined by a .terraformignore file
at /Users/myuser/Repositories/my-repo/.terraformignore (if it is present),
in order to capture the filesystem context the remote workspace expects:
    /Users/myuser/Repositories/myrepo

There was an error connecting to the remote backend. Please do not exit
OpenTofu to prevent data loss! Trying to restore the connection...

Still trying to restore the connection... (3s elapsed)
```

### Steps to reproduce

- Create the above file structure
- Create a VCS workspace which working directory points to the staging folder
- In production folder make sure to refer the module stored in `../modules/my-module`
- Run terraform plan

### Expected behavior

It should at least display an error rather than making the API pod crash.

**Comment by alfespa17** [comment]
Hello @BenjaminDecreusefond can you share how you put the `working directory` in the UI?

**Comment by BenjaminDecreusefond** [comment]
Hello @alfespa17 !
Like this ! /projects/04_my_project/staging/

**Comment by alfespa17** [comment]
> Hello @alfespa17 ! Like this ! /projects/04_my_project/staging/

I think it should be "/staging" the working dir is relattive to your git repository structure

**Comment by BenjaminDecreusefond** [comment]
I tried both ! But it doesn't work !

**Comment by BenjaminDecreusefond** [comment]
@alfespa17  Did you try to use your submodules from the module ? From module, you use the source
`source= ../submodule/module1` It's how I got it crashing

**Comment by alfespa17** [comment]
It is also working for me @BenjaminDecreusefond using the following

https://github.com/AzBuilder/terrakube-docker-compose/blob/test/module/main.tf

![image](https://github.com/user-attachments/assets/67bfc610-6247-4bbb-811a-69ac04213a0c)


```shell
λ terraform plan -destroy
Running plan in HCP Terraform. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://8080-azbuilder-terrakube-gtre69uxgz6.ws-us116.gitpod.io/app/simple/terrakube-docker-compose/runs/run-5

Waiting for 1 run(s) to finish before being queued...

***************************************
Initializing Terrakube Job 5 Step 85ffb3ff-1a6a-4f76-a788-44cad682b9ca
Running Terraform 1.9.8


***************************************
Running Terraform Init:
Initializing the backend...

Successfully configured the backend "local"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing modules...
- time_module in ../submodule/module1
Initializing provider plugins...
- Finding latest version of hashicorp/random...
- Installing hashicorp/random v3.6.3...
- Installed hashicorp/random v3.6.3 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!
***************************************
Running Terraform PLAN
***************************************
random_integer.time: Refreshing state... [id=4]
module.time_module.random_integer.time: Refreshing state... [id=4]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # random_integer.time will be destroyed
  - resource "random_integer" "time" {
      - id     = "4" -> null
      - max    = 5 -> null
      - min    = 1 -> null
      - result = 4 -> null
    }

  # module.time_module.random_integer.time will be destroyed
  - resource "random_integer" "time" {
      - id     = "4" -> null
      - max    = 5 -> null
      - min    = 1 -> null
      - result = 4 -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.

Changes to Outputs:
  - output_time = 4 -> null

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
```

Using the UI

![image](https://github.com/user-attachments/assets/d3b58d38-d63d-47e4-adac-a1bddea77528)

**Comment by alfespa17** [comment]
By the way if you can create a really simple public repository that I can use to make it crash I will be happy to help

**Comment by BenjaminDecreusefond** [comment]
Yep ! I'll try to send you an example tomorrow ! :)

**Comment by BenjaminDecreusefond** [comment]
Can you show me the main.tf you used in your module/ please ? @alfespa17

**Comment by alfespa17** [comment]
You can check all the source code here

https://github.com/AzBuilder/terrakube-docker-compose/blob/test/module/main.tf

**Comment by BenjaminDecreusefond** [comment]
What you can do is the following:
Put the module inside a subdirectory for instance TEST dir (As a reminder I had a depths of two when it crashed). You can do the same for the submodule. So you would end up with both module and submodules inside the directory TEST. Then you can set the workspace directory to point to the root of the TEST directory. Try to run a plan it should crash, at least i had this behavior. And you can also try after to set the correct directory for the workspace I also had the crash. I had this file structure when it crashed

projects/
    ├──myprojects
         ├── modules
          │   └── bucket
          │       ├── main.tf
         ├── staging
          │   ├── backend.tf
          │   ├── main.tf
          │   ├── providers.tf

**Comment by alfespa17** [comment]
I tried and it is working for me with the following

![image](https://github.com/user-attachments/assets/c16e09f0-59f2-4fdc-843c-4311d79256d5)

![image](https://github.com/user-attachments/assets/3442acb4-61c8-47fc-b1de-c3cb69d8dcfd)

Not sure how you made the API crash.

**Comment by BenjaminDecreusefond** [comment]
Hey @alfespa17 !

In my case the submodule directory was also nested ! I think in your example you can put in in the nested1 folder ! :)

**Comment by alfespa17** [comment]
> Hey @alfespa17 !
> 
> In my case the submodule directory was also nested ! I think in your example you can put it in the nested1 folder ! :)

I dont think that is the issue It will work

**Comment by BenjaminDecreusefond** [comment]
Well that's the set up I had. What is the workspace path ?

**Comment by alfespa17** [comment]
> Well that's the set up I had. What is the workspace path ?

![image](https://github.com/user-attachments/assets/974fb16a-0035-4c4e-a11b-57ecd60080d7)

**Comment by BenjaminDecreusefond** [comment]
When it crashed i had the following set up:
Same structure as you with folder nested in 2 folder. The module was nested with one depth. And wether I set the working directory of the workspace to module/nest1 or module/nest1/nest2 I had the API crashing

**Comment by alfespa17** [comment]
I am closing this issue not sure there is a way to reproduce your error.

I also tested with this and it worked

![image](https://github.com/user-attachments/assets/23855204-384e-4317-9da2-676d8d75ccf0)


![image](https://github.com/user-attachments/assets/452657d6-0b07-4026-b39c-250e4499acfb)

**Comment by BenjaminDecreusefond** [comment]
That's really strange and annoying! hopefully we wont run into it again !

Thank you anyway !

**Comment by BenjaminDecreusefond** [comment]
Hey @alfespa17 !

We got the issue again ! And I think I found why ! Actually is it not linked to the path of the module but to the API resource ! When launching the plan we have the following error 
```
16:20:20[10.415s][1][migrate_projects]$ tofu plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

The remote workspace is configured to work with configuration at
/projects/my_projectrelative to the target repository.

OpenTofu will upload the contents of the following directory,
excluding files or directories as defined by a .terraformignore file
at /xxx/.terraformignore (if it is present),
in order to capture the filesystem context the remote workspace expects:
    /xxx

There was an error connecting to the remote backend. Please do not exit
OpenTofu to prevent data loss! Trying to restore the connection...

Still trying to restore the connection... (3s elapsed)
Still trying to restore the connection... (5s elapsed)
Still trying to restore the connection... (8s elapsed)
Still trying to restore the connection... (12s elapsed)
Still trying to restore the connection... (18s elapsed)
^C
Interrupt received.
Please wait for OpenTofu to exit or data loss may occur.
Gracefully shutting down...

```

And right before the API pod crashes, we see the following log
```
2024-11-21T15:27:32.437Z  INFO 1 --- [ryBean_Worker-6] o.terrakube.api.rs.module.GitTagsCache   : vcs using GITHUB
2024-11-21T15:27:32.887Z  INFO 1 --- [ryBean_Worker-6] o.terrakube.api.rs.module.GitTagsCache   : vcs using GITHUB
2024-11-21T15:27:33.320Z  INFO 1 --- [ryBean_Worker-6] o.terrakube.api.rs.module.GitTagsCache   : vcs using GITHUB
2024-11-21T15:27:33.807Z  INFO 1 --- [ryBean_Worker-6] o.terrakube.api.rs.module.GitTagsCache   : vcs using GITHUB
2024-11-21T15:27:34.235Z  INFO 1 --- [ryBean_Worker-6] o.terrakube.api.rs.module.GitTagsCache   : vcs using GITHUB
2024-11-21T15:27:34.629Z  INFO 1 --- [nio-8080-exec-1] o.t.a.plugin.state.RemoteTfeController   : Uploading Id a0b41bdf-a3d3-4962-bd60-b6318ac44e29 file
2024-11-21T15:27:34.629Z  INFO 1 --- [nio-8080-exec-1] o.t.a.p.s.aws.AwsStorageTypeServiceImpl  : context file: content/a0b41bdf-a3d3-4962-bd60-b6318ac44e29/terraformContent.tar.gz
Terminating due to java.lang.OutOfMemoryError: Java heap space
```

So it should be easy to fix by increasing the limit but just letting you know this happens (I think for pretty big plans ?)

**Comment by alfespa17** [comment]
You can use the following env variable `JAVA_TOOL_OPTIONS` to customize the JVM params

It will be something like this:

```yaml
api:
  env:
  - name: JAVA_TOOL_OPTIONS
    value: "-Xms6144m -Xmx6144m -XX:NewSize=256m -XX:MaxNewSize=356m -XX:PermSize=256m -XX:MaxPermSize=356m"
```

I dont remember the exact parameters but you can google it.

**Comment by BenjaminDecreusefond** [comment]
Yep sure that's what I've done ! Do you think there's a way to prevent this in the Terrakube app code ? It was not easy to trouble shot
