### ISSUE TITLE
Bug when using configMap with ephemeral agents

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1528]
### Bug description 🐞

Hi !

Following the [PR](https://github.com/AzBuilder/terrakube/pull/1505) I implemented, it appears that the configMap is not mounted on the job when it's running. I've set the `TERRAKUBE_ENABLE_EPHEMERAL_EXECUTOR`, `EPHEMERAL_CONFIG_MAP_NAME`, `EPHEMERAL_CONFIG_SERVICE_ACCOUNT` and the `EPHEMERAL_CONFIG_MAP_MOUNT_PATH` but no volumes are mounted. I tripled check the new code I added but it seem correct to me and I'm having hard time to trouble shot where it comes from. 

I'm still trying to figure out what is happening, if you have any ideas I'd be happy to hear ! 

thanks !

### Steps to reproduce

Try to run an EPHEMERAL_JOB with the parameter above, no volume are mounted on the ephemeral job's container.

**Comment by alfespa17** [comment]
> Hello @alfespa17 !
> 
> Do I have good understanding of these [values](https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java#L20) by setting workspace environment variables like ? ![Screenshot 2024-11-12 at 18 00 00](https://private-user-images.githubusercontent.com/180167280/385384194-c7d2d92f-7f22-4911-bf14-d9db01698c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzQ5MjksIm5iZiI6MTczMTQzNDYyOSwicGF0aCI6Ii8xODAxNjcyODAvMzg1Mzg0MTk0LWM3ZDJkOTJmLTdmMjItNDkxMS1iZjE0LWQ5ZGIwMTY5OGMyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxODAzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTI5ODU4OWEwODkxMjkyM2E0MThhN2I0NWMwM2QyODgxOGZlNDNjMzQyNGVkZmNhMzMzY2ZlMjFjMWFkM2E1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1CboFHhzHVCCKCjeX88lUjnpXDmELoy0WmpsaMxmCro) Or we do need to use them differently ? From what i can see in the `kubectl describe job-<job_id>`
> 
> ```
> Containers:
>   job-376:
>     Environment:
>       EphemeralFlagBatch:           true
>       EphemeralJobData:   data
>       AWS_STS_REGIONAL_ENDPOINTS:   regional
>       AWS_DEFAULT_REGION:          my-region
>       AWS_REGION:                   my-region
>       AWS_ROLE_ARN:                 my-role
>       AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
> 
> Volumes:
>   aws-iam-token:
>     Type:                    Projected (a volume that contains injected data from multiple sources)
>     TokenExpirationSeconds:  86400
>   kube-api-access-46wdc:
>     Type:                    Projected (a volume that contains injected data from multiple sources)
>     TokenExpirationSeconds:  3607
>     ConfigMapName:           kube-root-ca.crt
>     ConfigMapOptional:       <nil>
>     DownwardAPI:             true
> ```
> 
> No environment variables like `EPHEMERAL_CONFIG_MAP_NAME` are set so maybe I misunderstood something ?
> 
> Regards!

Did you update the value in ExecutorEphemeralImage???

**Comment by alfespa17** [comment]
From you logic here, I think it should work

https://github.com/AzBuilder/terrakube/blob/3114c2bf9fd768120216cf4aa5f5aaccb227e599/api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java#L88

You only need to add the environment values EPHEMERAL_CONFIG_MAP_NAME and EPHEMERAL_CONFIG_MAP_MOUNT_PATH

**Comment by BenjaminDecreusefond** [comment]
> > Hello @alfespa17 !
> > Do I have good understanding of these [values](https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java#L20) by setting workspace environment variables like ? ![Screenshot 2024-11-12 at 18 00 00](https://private-user-images.githubusercontent.com/180167280/385384194-c7d2d92f-7f22-4911-bf14-d9db01698c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzQ5MjksIm5iZiI6MTczMTQzNDYyOSwicGF0aCI6Ii8xODAxNjcyODAvMzg1Mzg0MTk0LWM3ZDJkOTJmLTdmMjItNDkxMS1iZjE0LWQ5ZGIwMTY5OGMyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxODAzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTI5ODU4OWEwODkxMjkyM2E0MThhN2I0NWMwM2QyODgxOGZlNDNjMzQyNGVkZmNhMzMzY2ZlMjFjMWFkM2E1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1CboFHhzHVCCKCjeX88lUjnpXDmELoy0WmpsaMxmCro) Or we do need to use them differently ? From what i can see in the `kubectl describe job-<job_id>`
> > ```
> > Containers:
> >   job-376:
> >     Environment:
> >       EphemeralFlagBatch:           true
> >       EphemeralJobData:   data
> >       AWS_STS_REGIONAL_ENDPOINTS:   regional
> >       AWS_DEFAULT_REGION:          my-region
> >       AWS_REGION:                   my-region
> >       AWS_ROLE_ARN:                 my-role
> >       AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
> > 
> > Volumes:
> >   aws-iam-token:
> >     Type:                    Projected (a volume that contains injected data from multiple sources)
> >     TokenExpirationSeconds:  86400
> >   kube-api-access-46wdc:
> >     Type:                    Projected (a volume that contains injected data from multiple sources)
> >     TokenExpirationSeconds:  3607
> >     ConfigMapName:           kube-root-ca.crt
> >     ConfigMapOptional:       <nil>
> >     DownwardAPI:             true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No environment variables like `EPHEMERAL_CONFIG_MAP_NAME` are set so maybe I misunderstood something ?
> > Regards!
> 
> Did you update the value in ExecutorEphemeralImage???

Yep ! I'm using this config for the API
```
api:
  defaultDatabase: false
  loadSampleData: false
  serviceAccountName: ${svc_name}
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  - name: JAVA_OPTS
    value: "-Xmx512m -XX:MaxMetaspaceSize=1024m"
  - name: ExecutorEphemeralNamespace
    value: terrakube
  - name: ExecutorEphemeralImage
    value: azbuilder/executor:2.24.0-beta.5
  - name: ExecutorEphemeralSecret
    value: terrakube-executor-secrets
```

**Comment by alfespa17** [comment]
Workspace environment variables

**Comment by alfespa17** [comment]
Did you try killing the API pod?

**Comment by BenjaminDecreusefond** [comment]
I didn't fix it :/

**Comment by alfespa17** [comment]
> I didn't fix it :/

Try checking the Kubernetes job specification using kubectl maybe you can find what is missing there

**Comment by BenjaminDecreusefond** [comment]
Figured it out ! Actually need to set the API to the same image as the executor ! thanks !
