### ISSUE TITLE
Is there a way to prevent set maximum memory limits ?

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1577]
### Feedback

Hi ! 

We are currently moving our production repositories to Terrakube and hence creating many workspaces (currently around 30 and we plan to have around x10 times). In order to detect drift on our entire infrastructure we scheduled a drift template to each workspace at the same time. For now it runs around 30 jobs at the same time and it seems like Terrakube really doesn't like it since it makes the application crash. I was wondering if there was any way to limit the number of concurrent job running on Terrakube or any way to avoid that kind of behavior ?

Regards !

**Comment by alfespa17** [comment]
Which pod is crashing?

**Comment by alfespa17** [comment]
> It's the API due to the lack of resource available on the node due to the number of concurrent jobs started

Maybe you can increase the API replicas and set the resource limits for the API 

https://github.com/AzBuilder/terrakube-helm-chart?tab=readme-ov-file#example-api

**Comment by BenjaminDecreusefond** [comment]
Would you advise to increase a single pod capacity or add several API pods ?

**Comment by alfespa17** [comment]
> Would you advise to increase a single pod capacity or add several API pods ?

I think setting the Api resource limits and have more than 1 replica could work but you will have to experiment, and maybe if you can schedule the jobs in different moments in time that will help

**Comment by BenjaminDecreusefond** [comment]
I tried to schedule drift at different moments ! Hopefully that will help ! I also added a garbage collector to the JVM params as it could help cleaning resources. Thanks for your help !

**Comment by alfespa17** [comment]
The schedule API endpoint support quartz expression to define the time when a job will be triggered 

You could also use this page to create the expression that best works for you.

https://freeformatter.com/cron-expression-generator-quartz.html


### Example 
Something like this to trigger the job every 3 hours at minute 15

![image](https://github.com/user-attachments/assets/894ad48a-648d-4bc4-97e7-ee6f155bd1b1)

```
POST /api/v1/workspace/{workspaceId}/schedule
{
  "data": {
    "type": "schedule",
    "attributes": {
      "cron": "0 0 15/3 ? * * *",
      "templateReference": "{{templateId}}"
    }
  }
}
```
