### ISSUE TITLE
Variables should show description

### ISSUE THREAD

**Issue by juan-vg** [AzBuilder/terrakube#1619]
### Feature description 💡

Currently variables can have a description, but it's only displayed when editing the variable. However, I believe it could be useful to display this description just under the variable name (workspace variables, global variables, variable collections, ...).

**Comment by alfespa17** [comment]
Maybe adding something like a tooltip could work

**Comment by juan-vg** [comment]
This is how TFC shows it (under the name)
![imagen](https://github.com/user-attachments/assets/bcbcd945-1455-4d97-8dca-dc41277a261d)
