### ISSUE TITLE
VCS-Linked Workspaces Don't Block CLI-Driven Applies

### ISSUE THREAD

**Issue by fishfacemcgee** [AzBuilder/terrakube#1639]
### Bug description 🐞

When running `terraform apply` from the command line for a Workspace configured for VCS, the apply runs as though the workspace were a CLI one. Running into this with Terrakube 2.24.0 and Terraform CLI 1.7.5

### Steps to reproduce

1. Create VCS workspace (for additional context, the VCS connector I'm using is a GitHub app as opposed to OAuth)
2. Set up codebase that interacts with that workspace
3. Run `terraform apply`

### Expected behavior

A message similar (or identical) to this is displayed instead

```
╷
│ Error: Apply not allowed for workspaces with a VCS connection
│
│ A workspace that is connected to a VCS requires the VCS-driven workflow to ensure that the VCS remains the single source of truth.
╵
```

**Comment by alfespa17** [comment]
The missing property inside the workspace response in this part of the code could be the issue:

https://github.com/AzBuilder/terrakube/blob/75ec5a616386698dba3488d8f538156f822928c3/api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java#L84

Related to this part of the code inside the terraform cli code:
https://github.com/hashicorp/terraform/blob/337bf8e11b75dff87509455cabee60b023dd586e/internal/cloud/backend_apply.go#L40

**Comment by alfespa17** [comment]
The response should include something like this from what I can see [here](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/workspaces)

![image](https://github.com/user-attachments/assets/372166df-618a-424e-9c57-75175d2f9ae9)

**Comment by alfespa17** [comment]
The info is comming from this part of the code inside the go-tfe

https://github.com/hashicorp/go-tfe/blob/98975f447700482a79e4d7d177cd406ff8132f1d/workspace.go#L204

**Comment by alfespa17** [comment]
Done @fishfacemcgee, it was an easy fix
