### ISSUE TITLE
Removing VCS from GUI with connected workspaces doesn't result in error message GUI

### ISSUE THREAD

**Issue by iam-take** [AzBuilder/terrakube#1666]
### Bug description 🐞

When you are removing a VCS Provider in the GUI and this VCS is still connected to workspace(s) nothing happens. You do not see an error and the VCS is not removed. Which is good ofcourse however feedback with the reason why this isn't possible would be much appreciated. 

What I did now is open the developer tools to see the response when clicking the button

### Steps to reproduce

1. Create VCS Provider
2. Connect it to a workspace
3. Remove VCS Provider 
4. No error message will be shown.

**Comment by alfespa17** [comment]
I guess adding a message here could work at least to show there is an error while deleting

https://github.com/AzBuilder/terrakube/blob/f296e0efd26aa6337e399bad1d1f47246c123f38/ui/src/domain/Modules/Details.jsx#L194

I will test next week
