### ISSUE TITLE
Module registry not updating anymore 

### ISSUE THREAD

**Issue by iam-take** [AzBuilder/terrakube#1667]
### Bug description 🐞

Since a few days our modules in the registry arn't updating anymore. At first I thought it might have been a issue with the VCS provider configuration ( token expired or something like that) we created a new provider moved the modules to use this provider but still no success. It updated the first time but stops working after that. 

We've also restarted the AKS cluster to check if this would help anything but it doesn't.

Environment information:
Azure Kubernetes
Azure DevOps as the VCS Provider,
Azure Storage Account as storage Backend
Azure SQL Server as our SQL Server / Database. 

It's currently only the updating feature that isn't working we haven't tested adding any new modules though. 

Digging into the API logs we do find the following error, but we now have no clue if this is related (we do think it is) but it's unclear how we can fix this. 

Help would be much appriciated. 

```
28/12/2024, 06:35:46
terrakube-api-pod
2024-12-28T05:35:46.718Z INFO 1 --- [_MisfireHandler] o.s.s.quartz.LocalDataSourceJobStore : Handling 1 trigger(s) that missed their scheduled fire-time.

28/12/2024, 06:35:46
terrakube-api-pod
2024-12-28T05:35:46.721Z ERROR 1 --- [_MisfireHandler] o.s.s.quartz.LocalDataSourceJobStore : Error retrieving the misfired trigger: DEFAULT.TerrakubeV2_ModuleRefresh

28/12/2024, 06:35:46
terrakube-api-pod
org.quartz.JobPersistenceException: Couldn't retrieve trigger: No record found for selection of Trigger with key: 'DEFAULT.TerrakubeV2_ModuleRefresh' and statement: SELECT * FROM QRTZ_CRON_TRIGGERS WHERE SCHED_NAME = 'schedulerFactoryBean' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?

28/12/2024, 06:35:46
terrakube-api-pod
at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1522) ~[quartz-2.5.0.jar:2.5.0]

28/12/2024, 06:35:46
terrakube-api-pod
at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:972) ~[quartz-2.5.0.jar:2.5.0]

28/12/2024, 06:35:46
terrakube-api-pod
at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3147) ~[quartz-2.5.0.jar:2.5.0]

28/12/2024, 06:35:46
terrakube-api-pod
at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3877) ~[quartz-2.5.0.jar:2.5.0]

28/12/2024, 06:35:46
terrakube-api-pod
at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3896) ~[quartz-2.5.0.jar:2.5.0]

28/12/2024, 06:35:46
terrakube-api-pod
Caused by: java.lang.IllegalStateException: No record found for selection of Trigger with key: 'DEFAULT.TerrakubeV2_ModuleRefresh' and statement: SELECT * FROM QRTZ_CRON_TRIGGERS WHERE SCHED_NAME = 'schedulerFactoryBean' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?

28/12/2024, 06:35:46
terrakube-api-pod
at org.quartz.impl.jdbcjobstore.CronTriggerPersistenceDelegate.loadExtendedTriggerProperties(CronTriggerPersistenceDelegate.java:108) ~[quartz-2.5.0.jar:2.5.0]

28/12/2024, 06:35:46
terrakube-api-pod
at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTrigger(StdJDBCDelegate.java:1800) ~[quartz-2.5.0.jar:2.5.0]

28/12/2024, 06:35:46
terrakube-api-pod
at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1519) ~[quartz-2.5.0.jar:2.5.0]

``` 

### Steps to reproduce

Unkown

**Comment by alfespa17** [comment]
I will try to replicate it looks like it is related to the quartz library that we are using

**Comment by alfespa17** [comment]
When Terrakube starts a new API pod it will run the module refresh as you can see the logs inside the following part.

```
2024-12-28T15:23:58.960Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Run module index scan
2024-12-28T15:23:58.961Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Create Schedule Module Refresh: DEFAULT.TerrakubeV2_ModuleRefresh_f301ccb3-b7dd-42ce-9dfa-ddcce17d8905
2024-12-28T15:24:00.136Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Disable Old Module Refresh
2024-12-28T15:24:00.642Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : jobDetail is null false
2024-12-28T15:24:00.643Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Delete Old Quartz Job
2024-12-28T15:24:02.743Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Reschedule with new frequency
2024-12-28T15:24:02.744Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Create Schedule Job Trigger DEFAULT.TerrakubeV2_ModuleRefresh
```

Automatically it will create a schedule job that refresh the module tags every 3 minutes by default using the following configuration, that configuration can be overridden using the env variable `ModuleCacheSchedule`

https://github.com/AzBuilder/terrakube/blob/f296e0efd26aa6337e399bad1d1f47246c123f38/api/src/main/resources/application.properties#L183

In the database you can check the following table to see the schedule jobs `select * from [dbo].[QRTZ_TRIGGERS]`, the module refresh job will look like the following and you can check the job name "TerrakubeV2_ModuleRefresh" and you could also check "NEXT_FIRE_TIME" or "PREV_FIRE_TIME" and use something like [epoc converter](https://www.epochconverter.com/) to see the date

![image](https://github.com/user-attachments/assets/244aecdd-f329-4c82-9800-2696ccc5b921)

You could also check running `SELECT TOP (1000) * FROM [dbo].[QRTZ_CRON_TRIGGERS]` and see the quartz expression for the module tag refresh like this:

![image](https://github.com/user-attachments/assets/bebbcc2a-8d41-4500-b18f-9e7a126315eb)

When the module refresh job is running it will do a for each in this part of the code to refresh the modules

https://github.com/AzBuilder/terrakube/blob/f296e0efd26aa6337e399bad1d1f47246c123f38/api/src/main/java/org/terrakube/api/plugin/scheduler/module/CacheJob.java#L24

Inside the loop there is a message to show if the process has any error in this part of the code.

https://github.com/AzBuilder/terrakube/blob/f296e0efd26aa6337e399bad1d1f47246c123f38/api/src/main/java/org/terrakube/api/plugin/scheduler/module/CacheJob.java#L29

https://github.com/AzBuilder/terrakube/blob/f296e0efd26aa6337e399bad1d1f47246c123f38/api/src/main/java/org/terrakube/api/plugin/scheduler/module/CacheJob.java#L30

So if you don't see any error like "Updating module index for gcp/vm/google" maybe the job is not even running for some reason (not sure why) this will show you

![image](https://github.com/user-attachments/assets/5dd7eaaa-3bb1-4c03-8cad-7343aff7e5b1)

You could check `SELECT * FROM [dbo].[QRTZ_JOB_DETAILS] where description in ('ModuleRefreshV1', 'ModuleRefreshStartup')`

![image](https://github.com/user-attachments/assets/df38e77a-a487-4794-8693-69a862a10da3)

The row where description is `ModuleRefreshV1` is the one that will run every 3 minutes, the other jobs where description are like`TerrakubeV2_ModuleRefresh_XXXX` were the jobs that were execute  on the API startup

Not sure if this can help you debugging, maybe you  can find more information about the error.

By the way this is the data that I had in my test database.


### QRTZ_CRON_TRIGGERS

SCHED_NAME | TRIGGER_NAME | TRIGGER_GROUP | CRON_EXPRESSION | TIME_ZONE_ID
-- | -- | -- | -- | --
schedulerFactoryBean | TerrakubeV2_InactiveJobs | DEFAULT | 0 */5 * ? * * | Etc/UTC
schedulerFactoryBean | TerrakubeV2_ModuleRefresh | DEFAULT | 0 */3 * ? * * | Etc/UTC


### QRTZ_TRIGGERS

SCHED_NAME | TRIGGER_NAME | TRIGGER_GROUP | JOB_NAME | JOB_GROUP | DESCRIPTION | NEXT_FIRE_TIME | PREV_FIRE_TIME | PRIORITY | TRIGGER_STATE | TRIGGER_TYPE | START_TIME | END_TIME | CALENDAR_NAME | MISFIRE_INSTR | JOB_DATA
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
schedulerFactoryBean | TerrakubeV2_InactiveJobs | DEFAULT | TerrakubeV2_InactiveJobs | DEFAULT | InactiveJobsV1 | 1735400700000 | 1735400400000 | 5 | WAITING | CRON | 1735399437000 | 0 |   | 0 |  
schedulerFactoryBean | TerrakubeV2_ModuleRefresh | DEFAULT | TerrakubeV2_ModuleRefresh | DEFAULT | ModuleRefreshV1 | 1735400700000 | 1735400520000 | 5 | WAITING | CRON | 1735399442000 | 0 |   | 0 |  

### QRTZ_JOB_DETAILS
SCHED_NAME | JOB_NAME | JOB_GROUP | DESCRIPTION | JOB_CLASS_NAME | IS_DURABLE | IS_NONCONCURRENT | IS_UPDATE_DATA | REQUESTS_RECOVERY
-- | -- | -- | -- | -- | -- | -- | -- | --
schedulerFactoryBean | TerrakubeV2_ModuleRefresh | DEFAULT | ModuleRefreshV1 | org.terrakube.api.plugin.scheduler.module.CacheJob | True | False | False | False
schedulerFactoryBean | TerrakubeV2_ModuleRefresh_30a461e3-22a6-4149-8182-4e407783536a | DEFAULT | ModuleRefreshStartup | org.terrakube.api.plugin.scheduler.module.CacheJob | True | False | False | False
schedulerFactoryBean | TerrakubeV2_ModuleRefresh_ebeaf3a9-5007-4030-a24f-1079d5be6eb5 | DEFAULT | ModuleRefreshStartup | org.terrakube.api.plugin.scheduler.module.CacheJob | True | False | False | False
schedulerFactoryBean | TerrakubeV2_ModuleRefresh_eec6f9f2-ae98-4885-9a39-9e6909c95b4b | DEFAULT | ModuleRefreshStartup | org.terrakube.api.plugin.scheduler.module.CacheJob | True | False | False | False
schedulerFactoryBean | TerrakubeV2_ModuleRefresh_f301ccb3-b7dd-42ce-9dfa-ddcce17d8905 | DEFAULT | ModuleRefreshStartup | org.terrakube.api.plugin.scheduler.module.CacheJob | True | False | False | False

**Comment by alfespa17** [comment]
By the way you error says

`No record found for selection of Trigger with key: 'DEFAULT.TerrakubeV2_ModuleRefresh' and statement: SELECT * FROM QRTZ_CRON_TRIGGERS WHERE SCHED_NAME = 'schedulerFactoryBean' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?`

Maybe the row is missing

**Comment by iam-take** [comment]
Thanks for your help @alfespa17  i've checked the tables and I do see some data in there. It still contains some jobs for VCS providers which most likely are already removed. Could this be the reason why we see these messages in the logs? 

I am not sure if we can safely remove the rows from the table?

**Comment by iam-take** [comment]
Thinking of it doesn't make sense for the vcs jobs to generate the error message for the module refresh. So I think it's unrelated. 

I am a bit puzzled about the question marks in the query statement of the error when I run the query it doesn't work. Are those placeholders of some kind?

**Comment by iam-take** [comment]
Correction you are right the line is missing in the QRTZ_CRON_TRIGGERS table I will add it manually and see if this fixes it.

**Comment by iam-take** [comment]
I've readded the line with the details you provided and it works again. I will keep monitoring it the upcoming days. 
Still amazed that the line was removed from the database but very happy we could resolve it so quick :) 

Would it be worth to document a bit in the Wiki about the schedule(s)? I would be happy to write a bit down with the information I have currently. Might be helpfull for all to understand how this mechanism works and where to start with the troubleshooting.

**Comment by alfespa17** [comment]
> I've readded the line with the details you provided and it works again. I will keep monitoring it the upcoming days. Still amazed that the line was removed from the database but very happy we could resolve it so quick :)
> 
> Would it be worth to document a bit in the Wiki about the schedule(s)? I would be happy to write a bit down with the information I have currently. Might be helpfull for all to understand how this mechanism works and where to start with the troubleshooting.

I am glad that it wok.

I can add something in the documentation about how the scheduling work in the next days.

To be honest I am not really sure how the row was removed maybe some bug in quartz because all tables that starts with `QRTZ_` are managed by the quartz library, Terrakube does not update any of those directly.

For now I will close the issue feel free to reopen it if you see the same issue again
