### ISSUE TITLE
Workspace Actions

### ISSUE THREAD

**Issue by jcanizalez** [AzBuilder/terrakube#272]
### Feature description 💡

**Workspace actions** will allow customers to extend the Terraform state to another level.
Right now Terrakube creates a diagram based on the Terraform State:

<img width="610" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/27365102/196769974-3df65d1d-66af-446b-b1d8-f4abcf6bb299.png">

However the idea is to provide useful actions to each resource directly from the Terrakube ui. Example:
- Restart a web app 
- Open the resource in the azure portal or AWS console
- View the resource logs using open telemetry
- Access the grafana dashboard to monitor the resource

When the user select a resource in the diagram, and if the resource has a **workspace action** defined they will see the button to perform the action.
A drawer will appear on the right side with information about the resource and the defined **workspaces actions** on the resource 
<img width="517" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/27365102/196770164-dedb0d06-fe4e-4c18-87f9-7141bc4e1109.png">

**Workspace Actions** are reusables pieces of code written in nodejs that can be share between the community. This can be shared via a registry or via a github repo. Nodejs has SDKs for the main cloud providers, so there will be unlimited possibilities of what you can define using . The function will receive a parameter context with all the variables inside the workspace, the global variables and with the information from the state for the specific resource selected. So the information in the terraform state will be useful to get the resource id and perform an action in that resource.

Then a customer can import the workspace action inside Terrakube.
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2278">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'}
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; min-height: 15.0px}
p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px}
table.t1 {border-collapse: collapse}
td.td1 {border-style: solid; border-width: 1.0px 1.0px 1.0px 1.0px; border-color: #9a9a9a #9a9a9a #9a9a9a #9a9a9a; padding: 1.0px 5.0px 1.0px 5.0px}
</style>
</head>
<body>
<p class="p1">A new endpoint will allow to define actions inside the organization</p>
<p class="p2"><br></p>
<p class="p1">The following is an example of the table</p>
<p class="p1">Action Name: will be the name of the action that will appear in the UI button</p>
<p class="p1">Icon: Should be a SVG definition , this image will appear in the UI button</p>
<p class="p1">Function:<span class="Apple-converted-space">&nbsp; </span>A nodes functions that implement the logic to be executed when the action is triggered</p>
<p class="p1">Resource Type: The resource to apply this action.<span class="Apple-converted-space">&nbsp;</span></p>

Action name | Icon | Function | Action Type | Resource type
-- | -- | -- | -- | --
Restart Webapp | <SVG> | //nodejs logic here | UI | azurerm_app_service
View in Azure | <SVG> | open( ‘https://portal.azure', function (err) {   if ( err ) throw err;     }); | UI | azurerm_%
Check logs |   | //nodejs logic to check status here | Scheduled | azurerm_%

</body>
</html>

**Comment by jcanizalez** [comment]
Ideas:
- We can implement a proxy in the backend, that can execute calls to other APIs


```
   public ResponseEntity<String> callApi(@RequestBody ProxyRequest proxyRequest) {
            String url = proxyRequest.getUrl();
            HttpMethod method = HttpMethod.valueOf(proxyRequest.getMethod().toUpperCase());
            HttpEntity<String> requestEntity = new HttpEntity<>(proxyRequest.getBody());
            
            ResponseEntity<String> response = restTemplate.exchange(url, method, requestEntity, String.class);
            return ResponseEntity.ok(response.getBody());
    }

```

- Then from the UI action. We can perform the operations. We will send a context with all the terraform state data

const response = await fetch('/api/proxy/call', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          url: `https://api.azure.com/vm/restart/${context.id}`, // The actual API endpoint
          method: 'POST',
          body: JSON.stringify({ vmId: context.id }), // If the API expects a body
        }),
      });

- UI actions can loaded from the database dynamically.
- Sensitive values like credentials can be injected by the Backend API

**Comment by alfespa17** [comment]
Maybe you can use the dex openid-configuration endpoint and use it as a federated credential in Azure so you dont have to authenticate or use any kind of credentials and you can just send the API request directly
