### ISSUE TITLE
Error deploying using example 1 helm chart

### ISSUE THREAD

**Issue by erick-prosimo** [AzBuilder/terrakube#297]
### Bug description 🐞

Example 1 for Azure using the helm chart will fail due to not having any database credentials assigned. If you add those and re-run you will now hit this error:

`Error: INSTALLATION FAILED: template: terrakube/templates/secrets-registry.yaml:17:26: executing "terrakube/templates/secrets-registry.yaml" at <.Values.registry.properties.DexClientId>: nil pointer evaluating interface {}.DexClientId
helm.go:84: [debug] template: terrakube/templates/secrets-registry.yaml:17:26: executing "terrakube/templates/secrets-registry.yaml" at <.Values.registry.properties.DexClientId>: nil pointer evaluating interface {}.DexClientId
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.4.0/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_arm64.s:1263
`

### Steps to reproduce

Fill in required values in example 1 for Azure: https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/AzureAuthentication-Example1.md and try to deploy using helm chart.

**Comment by alfespa17** [comment]
Thank you for reporting the bug @erick-prosimo, let me check the example and fix it

**Comment by alfespa17** [comment]
Hello @erick-prosimo I have created a PR to fix the issue in the helm chart.
https://github.com/AzBuilder/terrakube-helm-chart/pull/41

I also updated the version in the example to 2.10.0 so you can update your values.yaml when running the helm install.

Let me know if you face any other issue I will be glad to help

**Comment by erick-prosimo** [comment]
Thank you for the quick response! I tested with the updates you made, and it worked. Thanks again!

**Comment by alfespa17** [comment]
By the way if you are using the example 1 the database will be deleted every time the pod restart because it is using the internal in memory database (H2), for testing that is ok but you can setup a postgresql, sql azure and mysql if you need a persistent database.

**Comment by erick-prosimo** [comment]
Got it, thank you. I will likely use Azure SQL DB. Are there any suggestions for the SKU size?

**Comment by alfespa17** [comment]
You dont need a big database for Terrakube, you can start with a small SQL Azure with 5 or 10 DTU and you will be fine.

**Comment by alfespa17** [comment]
I will close this issue. 

Feel free to open a new one if you find any new problem or a request feature if you have any suggestion to make terrakube better.
