### ISSUE TITLE
Initial login does not take you to organization

### ISSUE THREAD

**Issue by erick-prosimo** [AzBuilder/terrakube#304]
### Bug description 🐞

The initial logon takes you to an empty organization: 
![image](https://user-images.githubusercontent.com/100948345/216488882-15fa2529-ae33-402b-9ac0-b26db5110824.png)

### Steps to reproduce

Login to Terrakube

### Expected behavior

If a user is only assigned to a single organization when they login they should be directed to that organization without requiring any additional input. If there are multiple organizations a feature enhancement could be to assign a "default" organization.

**Comment by jcanizalez** [comment]
Will be released in version 2.11.0
