### ISSUE TITLE
UI templates

### ISSUE THREAD

**Issue by jcanizalez** [AzBuilder/terrakube#307]
### Feature description 💡

Allow to extend the Workspaces UI using the existing Templates.
Currently  using templates each organization can customize their workflow, but could be useful if based in the steps results we can define a ui template. Some uses cases:

- Improved UI for plan and apply

![image](https://user-images.githubusercontent.com/27365102/216707705-4e09af72-0775-4e2d-bd46-8e9ef44a8908.png)

- Infracost details in the step
<img width="493" alt="image" src="https://user-images.githubusercontent.com/27365102/216708281-af0b9a67-03c2-4ab3-baf0-8fde3a1f5e03.png">

**Comment by alfespa17** [comment]
This sounds pretty cool, I think you can use the context API and the Opa extensions to handle something like this
