### ISSUE TITLE
State migrate

### ISSUE THREAD

**Issue by klinux** [AzBuilder/terrakube#369]
### Bug description 🐞

I've configured the backend, and point to terrakube, terraform notify that need to migrate, evertythig is ok, but the state file don't appear in the bucket.

### Steps to reproduce

* Change the backend in the existent terraform stack
* Run terraform init -migrate-state
* The migrate terminate successfully 
* The log of terrakube-api show the state file base64 encoded
* The state file does never appear in the bucket
* Try run terraform plan and the remote excution says that will be create all stack again

### Expected behavior

I think that state migrate needs to respected, to make the move from terraform cloud easier.

**Comment by alfespa17** [comment]
Hello @klinux, thank you for reporting the issue.

I will have to check the terraform-cli code to see how it managed the "init -migrate-state" and implement the methods inside the terrakube api. 

I think this is something we could include for the next terrakube version.

**Comment by alfespa17** [comment]
Quick update I was able to implement "terraform init -migrate-storage" using the "local storage" in this PR:

https://github.com/AzBuilder/terrakube/pull/371

I tested in GITPOD and it looks like it is working fine, I just had to implement the following method:

https://developer.hashicorp.com/terraform/cloud-docs/api-docs/state-versions

I will add support for the other backend storage types like azure, gcp, aws and minio in the next couples of days.

**Comment by alfespa17** [comment]
Hello @klinux .

"terraform init -migrate-state" will be supported from version 2.13.0, we will release it by the end of this month.

It will support all the storage backends (azure, gcp, aws and minio)

**Comment by klinux** [comment]
Thank you @alfespa17 it's very important to us, we'll back to our tests when the version was released.

**Comment by klinux** [comment]
Yes, let me try here

**Comment by klinux** [comment]
Yes, it works like a charm now, thank you, sorry for the late message.

**Comment by klinux** [comment]
@alfespa17 Hi, I'm migrating a state from my projects, and the state is big,about 250KB, and I receiving this error:

```
terrakube-api-fdf7b58f6-d2d6c terrakube-api 2023-07-01 00:25:42.191 ERROR 1 --- [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Illegal base64 character 2b] with root cause
terrakube-api-fdf7b58f6-d2d6c terrakube-api
terrakube-api-fdf7b58f6-d2d6c terrakube-api java.lang.IllegalArgumentException: Illegal base64 character 2b
terrakube-api-fdf7b58f6-d2d6c terrakube-api     at java.base/java.util.Base64$Decoder.decode0(Unknown Source) ~[na:na]
terrakube-api-fdf7b58f6-d2d6c terrakube-api     at java.base/java.util.Base64$Decoder.decode(Unknown Source) ~[na:na]
terrakube-api-fdf7b58f6-d2d6c terrakube-api     at java.base/java.util.Base64$Decoder.decode(Unknown Source) ~[na:na]
terrakube-api-fdf7b58f6-d2d6c terrakube-api     at org.terrakube.api.plugin.state.RemoteTfeService.createWorkspaceState(RemoteTfeService.java:265) ~[classes/:2.14.0]
```

**Comment by alfespa17** [comment]
Hello @klinux what terrakube version are you using? What terraform version? Helm chart version?

**Comment by klinux** [comment]
Hello @alfespa17 

Sorry for the incomplete message:

Terrakube: 2.14.0
Terraform: 1.4.4
Helm chart: 3.5.1

**Comment by klinux** [comment]
@alfespa17 

I created a custom image here, with RemoteTfeService.java in the line 265.

I create this patch:
![Screenshot_808](https://github.com/AzBuilder/terrakube/assets/941051/21c2d5d4-9b31-4e33-97e4-b1d8068ce6e9)

And migration works.

Do you think that this makes sense?

Thank you

**Comment by alfespa17** [comment]
Hello @klinux 
It looks like we were using the wrong decoder, would you like to send the PR with the fix So we can create a new image :)

**Comment by klinux** [comment]
I created https://github.com/AzBuilder/terrakube/pull/425

If it is util, please, let me know :)

**Comment by alfespa17** [comment]
Hello @klinux, thank you for your contribution 

Here is the new release:
https://github.com/AzBuilder/terrakube/releases/tag/2.14.1
