### ISSUE TITLE
Existing Dex Server

### ISSUE THREAD

**Issue by sergiofteixeira** [AzBuilder/terrakube#393]
### Feature description 💡

Hello,

Possible to use an already existing dex server? couldnt find any documentation on it.

**Comment by alfespa17** [comment]
Hello @sergiofteixeira , I think it will work but it will require some adjustments in the helm chart. I can add the change I don't think it will require too much effort

**Comment by alfespa17** [comment]
Hello @sergiofteixeira I did an small change in the helm chart, you could use the following when creating your values.yaml

```yaml
....
dex:
  enabled: false
  config:
    issuer: https://yourcustomissuer.com

ingress:
  dex:
     enabled: false
´´´

**Comment by sergiofteixeira** [comment]
thank you so much @alfespa17 for the quick response.

**Comment by alfespa17** [comment]
It will work with helm chart 3.5.1 by the way
