### ISSUE TITLE
Using private module failed with: No changes

### ISSUE THREAD

**Issue by klinux** [AzBuilder/terrakube#402]
### Bug description 🐞

I'm trying to run with private module following the terrakube documentation: 
https://docs.terrakube.org/user-guide/private-registry/using-private-modules

And always get the same result:
```
Terrakube Remote Plan Execution

**********
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

### Steps to reproduce

In the new installation try the GCP sample deployed and get the result pointed above

Where I'm trying to use the module in the registry:
**network**
And running plan with these variables:
```
module "network" { 
  source = "terrakube-reg.----.----/gcp/network/google" 
  version = "v7.0.0" 

  project_id   = "platform-infra-production-0e9a"
  network_name = "default2"

  routes = [
    {
      name              = "egress-internet"
      description       = "route through IGW to access internet"
      destination_range = "0.0.0.0/0"
      tags              = "egress-inet"
      next_hop_internet = "true"
    }
  ]
}
```
Executing simple test, like https://docs.terrakube.org/user-guide/workspaces/cli-driven-workflow, the execution plan run successfully. Only using private registry this error happens.

In the executor logs, there's no error, the result is the same, with GCP credential or not.
```
2023-06-06T01:07:06.235188793Z [threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Downloading terraform version 1.2.3 architecture amd64 Type Linux
2023-06-06T01:07:06.235287544Z [threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - terraform_1.2.3_linux_amd64.zip already exists
2023-06-06T01:07:06.651770236Z [ForkJoinPool-1-worker-26] INFO org.terrakube.executor.service.logs.LogsConsumer - 
2023-06-06T01:07:06.652748766Z [ForkJoinPool-1-worker-26] INFO org.terrakube.executor.service.logs.LogsConsumer - No changes. Your infrastructure matches the configuration.
2023-06-06T01:07:06.653279086Z [ForkJoinPool-1-worker-26] INFO org.terrakube.executor.service.logs.LogsConsumer - 
2023-06-06T01:07:06.655364686Z [ForkJoinPool-1-worker-26] INFO org.terrakube.executor.service.logs.LogsConsumer - Terraform has compared your real infrastructure against your configuration
[ForkJoinPool-1-worker-26] INFO org.terrakube.executor.service.logs.LogsConsumer - and found no differences, so no changes are needed.
```

### Expected behavior

Execute the module with variables configured

**Comment by alfespa17** [comment]
Hello @klinux 

I think I was able to reproduce and fix your issue, you could check this PR with more detail information
https://github.com/AzBuilder/terrakube/pull/403

I also open one additional issue because the logs are not shown completely in the terminal when using the remote state backend.
https://github.com/AzBuilder/terrakube/issues/404

The logs are shown correctly only in the UI.

The fix will be released later this month, but you could test the fix in version 2.14.0-beta.2

**Comment by klinux** [comment]
I'm trying the version 2.14.0-beta.2

But the result is the same:

```
Waiting for the plan to start...

Terrakube Remote Plan Execution



No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```
I'm doing something wrong?

**Comment by alfespa17** [comment]
Can you provide an example step by step?
Did you update all there version parameters in the helm chart for each component rigth?

**Comment by klinux** [comment]
There's the steps that I made:

1 - Replace all version tag in helm values to 2.14.0-beta.2, as in the image
[
![Screenshot_791](https://github.com/AzBuilder/terrakube/assets/941051/67ca67ca-e2a9-43f2-a16b-1b995b03fa0d)
](url)
2 - Remove .terraform and .terraform.lock.hcl and remove all states in the bucket (clean setup)
3 - Run **terraform plan**

And the result is the same, how can I put the servers in debug mode?

Thank you

**Comment by alfespa17** [comment]
could you check executor componet logs? 
you should be able to see the files that are added to the job context like this:

```bash
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Adding file /home/gitpod/.terraform-spring-boot/executor/d9b58bd3-f3fc-4056-a026-1163297e80a8/8fad46d8-8e47-4ad4-bd3f-35e512700fb3/.terraform.lock.hcl to workspace context
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Adding file /home/gitpod/.terraform-spring-boot/executor/d9b58bd3-f3fc-4056-a026-1163297e80a8/8fad46d8-8e47-4ad4-bd3f-35e512700fb3/backend.tf to workspace context
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Adding file /home/gitpod/.terraform-spring-boot/executor/d9b58bd3-f3fc-4056-a026-1163297e80a8/8fad46d8-8e47-4ad4-bd3f-35e512700fb3/main.tf to workspace context
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Untar completed successfully!
```

Internally the terraform CLI is uploading a file "tar.gz", you should be able to find that file in your storage backend
![image](https://github.com/AzBuilder/terrakube/assets/4461895/2f0051ea-8e9c-4739-8ef1-ed00373d85ff)

That file contains all the files that terrakube will run.

What storage backend are you using with terrakube?

You could enable debug adding the environment variable LOGGING_LEVEL_ROOT=DEBUG, but I dont think you will get much information because most of the debug information is using "INFO" level in the logs

**Comment by klinux** [comment]
@alfespa17
Thank you, it's working now, I don't know what is the relation, but, after recreate Github VCS the **terraform plan** it's running now:

```terraform
Waiting for the plan to start...

Terrakube Remote Plan Execution



Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.network.module.routes.google_compute_route.route["egress-internet"] will be created
  + resource "google_compute_route" "route" {
      + description            = "route through IGW to access internet"
      + dest_range             = "0.0.0.0/0"
      + id                     = (known after apply)
      + name                   = "egress-internet"
```
Thank you
