### ISSUE TITLE
Custom terrakube executor 

### ISSUE THREAD

**Issue by thatsk** [AzBuilder/terrakube#430]
### Feature description 💡

Need to create a Custom Terrakube executor container which has predefined binaries so that I don't need to define it in custom templates.
any documentation on how do build custom terrakube executor

**Comment by alfespa17** [comment]
You could check this script

https://github.com/AzBuilder/terrakube/blob/main/scripts/build/terrakubeBuild.sh

**Comment by thatsk** [comment]
Perfect thanks thats what i am looking at :)

**Comment by alfespa17** [comment]
Another option is to fork the repository and change the GitHub action Workflow here adding other dependencies

https://github.com/AzBuilder/terrakube/blob/main/.github/workflows/release.yml#L56
