### ISSUE TITLE
Keep Repository Structure 

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#431]
### Feature description 💡

When cloning a repository, keep the same folder structure when running a job inside an specific folder, instead of just copy the foldar that is specified in the workspace definition, this is usefull when you are using files outside of your workspace folder definition.

**Comment by AppliNH** [comment]
Hi @alfespa17 ! Any updates for this? 
Perhaps it could be less costly to update the `terraformPlan` default extension to allow the users to make use of the `chdir` argument instead?

**Comment by alfespa17** [comment]
Thanks for the idea @AppliNH, that could be an option. Let me check if that idea can help to make the change easier I will try to fix this in the following days and maybe release a beta so you can test it
