### ISSUE TITLE
No more terraform resources after a local terraform plan

### ISSUE THREAD

**Issue by totti339** [AzBuilder/terrakube#443]
### Bug description 🐞

Hi,

I just deployed Terrakube (2.14.1) and I'm noticing something I think is a bug.

I had a working workspace (linked to bitbucket with plan and apply working), but as soon as I trigger a terraform plan from my computer the workspace meet a bug where it still sees the state but not my terraform code resulting in a plan where terraform want to remove all my resources present in the state. It looks like the git pull isn't working anymore.

### Steps to reproduce

- Create a VCS Workspace
- Plan and Apply and eveythring will go well
- On your local computer set your terraform backend to use Terrakube
```
terraform {
  backend "remote" {
    hostname = "8080-azbuilder-terrakube-q8aleg88vlc.ws-us92.gitpod.io"
    organization = "migrate-org"

    workspaces {
      name = "migrate-state"
    }
  }
}
```
- Run a plan

**Comment by alfespa17** [comment]
Hello @totti339 

If you are using the remote state feature when you are creating the workspace you should use "CLI-drive workflow" not the VCS 

![image](https://github.com/AzBuilder/terrakube/assets/4461895/95f88911-acf4-4d62-abac-abe611c8ed16)

**Comment by totti339** [comment]
Hi @alfespa17,

thanks for answer. But if I do that my workflow won't trigger when change are made in the VCS repository right ? (pull request, merge). Could we have both workflow working ?
