### ISSUE TITLE
azure devops

### ISSUE THREAD

**Issue by georgegil** [AzBuilder/terrakube#444]
### Feedback

I am trying to add an Azure Devops git url (which does not end in .git??) for a workspace, i keep getting this issue "'source' does not match pattern (empty)|(((git|ssh|http(s)?)|(git@\[\\w.\]+))(:(//)?)(\[\\w.@:/-~\]+)(.git)(/)?)"

my URL is https://tenant@dev.azure.com/tenant/project/_git/aws-s3-logging-deploy

is there a guide on how ADO URL's should be formatted?

**Comment by alfespa17** [comment]
This looks like a bug in the UI

**Comment by georgegil** [comment]
adding it via API should work, right?

**Comment by alfespa17** [comment]
Yes, if you use the API it should work.

I will check if I can fix that regex validation.

**Comment by alfespa17** [comment]
This issue was fixed in version 2.14.2, now repository ending in .git is optional in the UI
