### ISSUE TITLE
Ability to set workspace to 'local' execution mode

### ISSUE THREAD

**Issue by jderieg** [AzBuilder/terrakube#451]
### Feature description 💡

Currently, terrakube only supports 'remote' execution mode. We run all our jobs in Github, but would like to use Terrakube to store the backend data, workspaces, etc. In order to do that we need to be able to set execution mode to 'local' on a workspace.

**Comment by alfespa17** [comment]
I think I got this working with the local storage pluging, I will implement AWS,Azure and GCP storage in the following days

**Comment by alfespa17** [comment]
This feature will be available by the end of the month in version 2.15.0

For now it can be tested using the beta version

```
api:
  version: "2.15.0-beta.2"
```
