### ISSUE TITLE
UI refreshes to workspace 'overview' constantly

### ISSUE THREAD

**Issue by jderieg** [AzBuilder/terrakube#458]
### Feedback

When using the UI, if I'm in the Workspace view looking at a particular workspace, if I go to any other tab than 'workspace', after about 5 to 10 seconds, the UI refreshes and reverts back to the 'overview' tab. I've tried this in a couple different browsers (Brave, Opera), and it does the same thing.

**Comment by alfespa17** [comment]
This is a bug maybe @jcanizalez could check when he has some free time
