### ISSUE TITLE
OpenTofu Support

### ISSUE THREAD

**Issue by kunalsingthakur** [AzBuilder/terrakube#492]
### Feature description 💡

As terraform licensing changed are we moving towards opentf ?

**Comment by kunalsingthakur** [comment]
https://opentf.org/

**Comment by alfespa17** [comment]
Hello @kunalsingthakur 

Terrakube is compatible with the new BSL license as you can see [here](https://github.com/orgs/AzBuilder/discussions/467).

We will add support for opentf once there is an stable version and they expose an opentf index that we can use to donwload the opentf binary.

I was thinking that maybe we can support both, or maybe add some kind of flag so you can select which one to use, but it is just some idea.

**Comment by alfespa17** [comment]
Hello @kunalsingthakur I added tofu support from version 2.19.0-beta.5 if you would like to test, all feedback is welcome and more information can be found in the PR #675
