### ISSUE TITLE
Ability to create Team Tokens

### ISSUE THREAD

**Issue by ruankr** [AzBuilder/terrakube#494]
### Feature description 💡

Would it be possible to have the ability to create Team Tokens added like [TF Cloud](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/team-tokens) ?

We often call terraform from pipelines and as such need a shared way to access the Terrakube API's rather than have it pinned to individuals. Team tokens would resolve this so would be quite beneficial if possible.

**Comment by jderieg** [comment]
+1. This would be super useful for us as well.
For now we worked around it by creating a service account bound to the team (we use Github Auth for login), logging in as that user and creating an API token specifically to share. But having the ability to just create a token through Terrakube would be much easier.

**Comment by alfespa17** [comment]
This looks interesting and I dont think it should be to difficult to implement at least to add the API endpoint to get the team token and for a second phase add the UI component.

**Comment by alfespa17** [comment]
Hello @ruankr  @jderieg 

I added support to generate a token for a particular team in these [PR](https://github.com/AzBuilder/terrakube/issues/494) maybe you can take a look when you have some time, all feedback and suggestion are welcome.
