### ISSUE TITLE
Terraform state too large for Terrakube to handle

### ISSUE THREAD

**Issue by jderieg** [AzBuilder/terrakube#496]
### Bug description 🐞

We were in the process of migrating all our state files out of terraform cloud to Terrakube, and hit this bug. Upon trying to push a particular state file (the file itself is 844k and has 15510 lines in the file) to Terrakube, we receive the following error:

`Failed to persist state: error uploading state: 413 Request Entity Too Large`

I don't seem to be able to find any log output related to this in the api pod for Terrakube, so not sure where this error is coming from.

### Steps to reproduce

`terraform state push <large state file.tfstate>`

### Expected behavior

The state file should be pushed successfully to Terrakube. This works fine on smaller state files.

**Comment by alfespa17** [comment]
Hello @jderieg.

I think this could be a spring-boot request size limit, let me check official documentation and check the default value.

Regards.

**Comment by alfespa17** [comment]
@jderieg I was checking the spring documentation, it looks like the limit is 1MB and 10 MB as you can see below.

![image](https://github.com/AzBuilder/terrakube/assets/4461895/4142ff47-bbf0-43d3-9637-278715bbffe9)

But you mention that you didn't see anything in the API logs.

What about the k8s ingress pod? 
Which ingress are you using?

For example if you are using nginx ingress it will return 413 error if the request size is to big according to [this](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#custom-max-body-size).

**Comment by jderieg** [comment]
I'll check the ingress logs and see if I can find any errors. We are using ingress-nginx as our ingress.

**Comment by jderieg** [comment]
Yes! That was the issue. Thanks for helping me track that down.
The error thrown in the ingress container was:
`client intended to send too large body`

I added the following line to my ingress annotations in my yaml for the Terrakube helm chart:

`nginx.ingress.kubernetes.io/proxy-body-size: "10m"`

I set it to 10m to match the Max Request Size that you sent me for the spring.servlet.multipart.max-request-size in the Terrakube code.

I tested and was able to upload my largest state file to Terrakube. Thanks again!
We can close this issue.

**Comment by alfespa17** [comment]
Cool @jderieg , I am glad that it work! :+1:

**Comment by stobias123** [comment]
FWIW I'm still seeing this with nginx configurations. I've got some state files larger than 10m.

**Comment by alfespa17** [comment]
Maybe you can set a bigger value like:

nginx.ingress.kubernetes.io/proxy-body-size: "15m"

**Comment by alfespa17** [comment]
And if you want to change the default value in spring maybe you could add the following environment variable in your helm chart:

```yaml
api:
  env:
  - name: JAVA_TOOL_OPTIONS
    value: "-Dspring.servlet.multipart.max-file-size=15MB -Dspring.servlet.multipart.max-request-size=15MB"
```

By the way I didn't test the above but I think it could work

Reference: 
https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.web
https://paketo.io/docs/howto/java/#configure-the-jvm-at-runtime

**Comment by stobias123** [comment]
I had tried a bigger proxy body size annotation :) I had also tried setting spring upload sizes via env var, but that didn't work either.

Turns out I needed to set `JAVA_TOOL_OPTIONS` as described. Thanks!!

**Comment by alfespa17** [comment]
I am glad that it work @stobias123  👍
