### ISSUE TITLE
Forget user for the Docker-compose image

### ISSUE THREAD

**Issue by dguevara-alianza** [AzBuilder/terrakube#508]
### Bug description 🐞

On the docker-Compose file for local development, forget set the user and get an error.

pull access denied for api-server, repository does not exist or may require 'docker login'

image: api-server:2.16.0-beta.1
https://github.com/AzBuilder/terrakube/blob/c45f09dca0ff08782843b097402c983dd5920710/docker-compose/docker-compose.yaml#L4

To fix it, set the user
image: azbuilder/api-server:2.16.0-beta.1

### Steps to reproduce

docker up -d

pull access denied for api-server, repository does not exist or may require 'docker login'

**Comment by alfespa17** [comment]
I was doing some local testing a few days ago, it looks like I committed the file with the wrong name, let me fix this

**Comment by alfespa17** [comment]
Hello @dguevara-alianza 

I fixed the issue with the docker compose it should work now when using

```bash
 docker-compose up
```
