### ISSUE TITLE
Failed state push to Terrakube

### ISSUE THREAD

**Issue by jderieg** [AzBuilder/terrakube#521]
### Bug description 🐞

I'm attempting to migrate a state file from our old system to Terrakube. I have the state file local on my machine, and I run a `terraform state push ~/localstatefile`. This works for all the other state files I have tried previously, but on one in particular, I'm getting an error. 
The terraform state push command completes successfully without error, but if I look in Terrakube at the state file, it looks like this:
![2023-10-04_10-29](https://github.com/AzBuilder/terrakube/assets/63372114/b95c984c-db0a-46ec-b3f0-d20b24836dec)

I'm not even sure what that error is referring to as there are not any forEach statements used in the terraform code I'm trying to upload the state for. Maybe that's a Java error? I looked in the logs for the API server, I don't see any errors at all during that upload. It just logs that it created the state file.

I checked the state file that I'm trying to upload locally, it looks fine.

### Steps to reproduce

I have reproduced this by deleting the workspace and trying again on a fresh one. I get the same error.

### Expected behavior

State file is uploaded to Terrakube like all the other states we have migrated.

**Comment by jderieg** [comment]
One additional note on this: I went and checked the backend storage, and the state file actually _did get uploaded_ to the S3 storage. That's why terraform didn't throw an error. So the problem seems to be with Terrakube reading the state file successfully.

**Comment by alfespa17** [comment]
Hello @jderieg what terraform version is using your old state? 
I think it could be the logic that we use to create a visual representation for the state in the UI.

**Comment by jderieg** [comment]
This particular state last ran using Terraform version 1.3.4.

**Comment by alfespa17** [comment]
I think this is an issue in the UI, if you open the console you should see the state. Something like this:

![image](https://github.com/AzBuilder/terrakube/assets/4461895/6f18fac4-b8a1-4f88-b1ea-b57a760dbe77)

It is using this part of the code
https://github.com/AzBuilder/terrakube/blob/main/ui/src/domain/Workspaces/States.jsx#L65

After it shows the state in the console it will try to build the following diagram.
![image](https://github.com/AzBuilder/terrakube/assets/4461895/09bcdb85-bb8d-4cad-9d58-66f8062a89d2)

To build the diagram it will basically loop inside the state json for the "resources", "child_modules" and "child_modules.resources" in this part of the code

https://github.com/AzBuilder/terrakube/blob/main/ui/src/domain/Workspaces/States.jsx#L79
https://github.com/AzBuilder/terrakube/blob/main/ui/src/domain/Workspaces/States.jsx#L99

Maybe you could compare your JSON state and see which "foreach" logic is failing.

I hope this can help you.

**Comment by jderieg** [comment]
@alfespa17 
I went and checked in the console, and I'm still not sure why it's failing for this state, although I did verify that the full state file is there in the backend storage and I can call it successfully from terraform. So you're right, it is strictly a UI error.
In the console under 'states.jsx', I see it parse all 16 resources in this  particular state. I'm not sure what would be causing the code to throw that error. I wonder if it's because there are multiple child modules?
This particular state has:
7 resources under the root
3 child modules: one with 5 resources, one with 3 resources, and one with a single resource

The only other thing that I see that could potentially be causing the loop to break is that one of the submodules has some values marked 'sensitive'.
![2023-10-05_10-58](https://github.com/AzBuilder/terrakube/assets/63372114/0a9f507c-bef5-4579-8307-6ea1016fe1bc)

Maybe the code doesn't know what to do with that and fails. Just a hypothesis.

I do see that you did a PR that will still show the state file if the diagram fails, so that's a good workaround for us for now. Thanks!

**Comment by jderieg** [comment]
@alfespa17 I just tested. Your fix actually also made it so the diagram worked as well on this particular state, so that's great! Still not sure what caused it in the first place, haha! But all is well now, and the state file shows up properly in the UI along with the diagram. Thanks again for your help!
