### ISSUE TITLE
Registry objects not removed from S3 on deletion

### ISSUE THREAD

**Issue by jderieg** [AzBuilder/terrakube#523]
### Bug description 🐞

I have created several test modules on the Terrakube Registry and later deleted them. After deletion, the objects for the deleted module persist in our S3 bucket that Terrakube uses for storage.
If a module is completely removed from Terrakube, it seems like it should also be removed completely from S3 or whatever backend storage is being used.

### Steps to reproduce

Create module in Registry in Terrakube.
Delete module through UI
Look in storage - the module objects still exist.

### Expected behavior

Objects in storage should get deleted when a module is deleted in Terrakube

**Comment by alfespa17** [comment]
Partially fixed by 

https://github.com/AzBuilder/terrakube/pull/538

Azure/GCP will be added later
