### ISSUE TITLE
Unable to plan/apply using shared workspace from UI

### ISSUE THREAD

**Issue by RobyDev91** [AzBuilder/terrakube#530]
### Bug description 🐞

When try to launch a plan from UI on a workspace that has to retrieve the tfstate from a shared workspace, terrakube api fails with the following error:
[terrakube-api-issue.txt](https://github.com/AzBuilder/terrakube/files/12883939/terrakube-api-issue.txt)

On the UI ( and the executor k8s pod logs ) shown the following issue ( workspace configured with **v1.5.7** ):

��� Error: Failed to read organization "myorganization" at host terrakube-api.mydomain.it
��� 
���   with data.terraform_remote_state.main,
���   on main.tf line 23, in data "terraform_remote_state" "main":
���   23: data "terraform_remote_state" "main" {
��� 
��� The "remote" backend encountered an unexpected error while reading the
��� organization settings: 500 Internal Server Error

It works using a terraform cli ( **v1.0.5** ) with this sequence:
- terraform login terrakube-api.mydomain.com
- terraform init
- terraform plan

### Steps to reproduce

Login to terrakube-ui.mydomain.com
Create an Organization: myorganization
Create 2 workspaces named terrakube-test-1 and terrakube-test-2
Configure workspace terrakube-test-1 with an output variable that will be used later on terrakube-test-2 workspace
Configure workspace terrakube-test-2 in order to read the remote state of terrakube-test-1
Use the remote output variable on the template on workspace terrakube-test-2
Perform a plan/apply on terrakube-test-1
Perform a plan/apply on terrakube-test-2

### Expected behavior

plan/apply on terrakube-test-2 from the UI works as for the terraform cli.

### Example repository

Please see attached file used for this example
[main_example.zip](https://github.com/AzBuilder/terrakube/files/12884159/main_example.zip)
Note:
The 2 files must be used in two different workspaces

### Anything else?

The error seems to be raised by a missing token or unrecognized user

**Comment by alfespa17** [comment]
Hello @RobyDev91 What terraform version are you using?

**Comment by RobyDev91** [comment]
> Hello @RobyDev91 What terraform version are you using?

Hi @alfespa17, 
I'm using terraform 1.5.7 ( configured on the UI workspace )
Performing the test locally as described in the issue, it works but I used terraform cli v1.0.5

**Comment by alfespa17** [comment]
Some days ago I created this [PR](https://github.com/AzBuilder/terrakube/pull/510) that add some validation when you are using the remote/cloud block backend.

It will work correctly if you are using the local execution mode because the local terraform CLI send a token with the correct groups that you got from the terraform login command

But if you are using just the UI it will run a remote execution internally and it is using the internal token that does not include the groups, I will add some small validation to fix this issue.

**Comment by alfespa17** [comment]
I will create a hotfix so you can test @RobyDev91 

Terrakube version 2.16.4  will fix it
