### ISSUE TITLE
Add support for setting minutes along with days in PAT generation

### ISSUE THREAD

**Issue by sigurdurf** [AzBuilder/terrakube#535]
### Feature description 💡

With the addition of team "personal access tokens" it might be good to increase granularity when it comes to token expiry. Sometimes I'd like to create "one off" tokens for a team and keeping that token active for 1 day seems like a long time for these types of tokens.

**Comment by alfespa17** [comment]
Hello @sigurdurf 

This does not require a lot of work, I just need to add some logic to this part of the code

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenService.java#L65

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/plugin/token/pat/PatService.java#L50

I will try to add it during the following days when I have some free time
