### ISSUE TITLE
CORs problem with docker-compose deployment

### ISSUE THREAD

**Issue by mzupan** [AzBuilder/terrakube#545]
### Bug description 🐞

Just trying to play around with the docker-compose env and getting a CORS failed error when setting up a new org

<img width="1432" alt="Screenshot 2023-10-18 at 3 36 29 PM" src="https://github.com/AzBuilder/terrakube/assets/205373/6711bedf-0923-422f-a502-31f1c9b29460">

### Steps to reproduce

happens when I run

```
docker-compose up
```
Then login and access

http://terrakube-ui:3000/organizations/create

### Expected behavior

I expect to create an org

**Comment by alfespa17** [comment]
Hello @mzupan 

I was testing the docker compose and I am not facing that issue.

![image](https://github.com/AzBuilder/terrakube/assets/4461895/2b13b965-283c-4fa8-8c3a-a25389de7125)

**Comment by alfespa17** [comment]
Did you update any parameter in the docker compose file?
