### ISSUE TITLE
GitLab VCS provider should work with self-hosted GitLab

### ISSUE THREAD

**Issue by btpier** [AzBuilder/terrakube#582]
### Feature description 💡

When creating a GitLab VCS provider, the user should have the opportunity to input the URL of their GitLab instance/API. The same is true when editing an already existing provider.

**Comment by alfespa17** [comment]
Hello @btpier 

I think we could add a new field for the hostname when you create a VCS connection but not sure if that could be enough and we dont have a way to test it because we dont have a self-hosted instance.

If you would like to contribute to the code or help us to test it all help is welcome.

**Comment by alfespa17** [comment]
VCS types are define in the following ENUM.

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/rs/vcs/VcsType.java

To add a new field for the VCS entity we only need to modify the following class.

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/rs/vcs/Vcs.java

Add the new field for hostname or any other new parameter in the database scripts.

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/resources/db/changelog/changelog.xml

The terrakube endpoint that get the Gitlab/Github/Bitbucket/Azure Devops token is the following class.

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/plugin/vcs/controller/CallbackController.java

And the gitlab logic to get the token is in this class.

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/plugin/vcs/TokenService.java#L69

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/plugin/vcs/provider/gitlab/GitLabTokenService.java

If you would like to contribute all pull request are welcome :)

**Comment by alfespa17** [comment]
I open a new issue to add support for self hosted VCS providers #590, 

I already update the code with the changes to support self hosted Gitlab, if anyone is interested in testing the new feature please add a comment in #590
