### ISSUE TITLE
Using VCS and SSH connections together for the same workspace

### ISSUE THREAD

**Issue by ilkerispir** [AzBuilder/terrakube#640]
### Feature description 💡

Hello @alfespa17, @jcanizalez;

I would like to briefly summarize what I need. While creating the Workspace, I connected the Terraform repo to Terrakube via the VCS GitHub App. However, in the Terraform repo, the private module pulls my modules by making an SSH connection to the repo. Unfortunately, this is not available in the current Terrakube structure, you have to choose one of the two. However, this is available in Terraform Cloud. Is it possible to add this feature to Terrakube?

For example Terraform Cloud screenshots:
![image](https://github.com/AzBuilder/terrakube/assets/37123041/89c70d5f-c70a-46e6-95d4-40b81008dc26)
![image](https://github.com/AzBuilder/terrakube/assets/37123041/4fc69c04-93ec-4c47-a273-9c6cc7bf295c)

**Comment by alfespa17** [comment]
I think I can add this feature without a big change in the code, I will try to add it in the following days

**Comment by ilkerispir** [comment]
Thank you very much, @alfespa17
