### ISSUE TITLE
Modules in a private Github repository

### ISSUE THREAD

**Issue by piernijenhuis** [AzBuilder/terrakube#646]
### Feedback

Hi,

I am trying to migrate our Terraform Enterprise environment to Terrakube. I am having difficulties to publish our own modules to the private registry. The resources are located on a github repository with private access. The VCS provider is connected succesfully to this Github repository but the modules can't be loaded. On the console of the API pod i see a message "https://github.com/{{my-module-path}}.../info/refs/service=git-upload-package not found : not found."

When i temporary change the Github repository to public visibility the module is loaded without issues. But we don't want the repository to be public available.

Am i doing something wrong or is this expected behaviour?

**Comment by alfespa17** [comment]
When you firts create the github vcs connection there is a window where grant access to the github application, I guess your modules are inside a github organization so did you grant access to repositories in your github organization or just for your personal github repositories?

**Comment by piernijenhuis** [comment]
@alfespa17 You are completely right. By accident i granted them permissions to my own repositories instead of the ones of the organization. After modifiyng my setup everything works as expected. Thanks for pointing me in the good direction!
