### ISSUE TITLE
Allow modules from subfolder of private monorepo

### ISSUE THREAD

**Issue by cfsnate** [AzBuilder/terrakube#653]
### Feature description 💡

Would like to be able to register modules that exist within a subfolder of an existing monorepo instead of requiring their own repository per module. These can be versioned with Tags similar to what is done on the registry at Scalr.

**Comment by alfespa17** [comment]
Hello @cfsnate not sure how Scalr works, can you show a little example? so we can understand better how it could work

**Comment by cfsnate** [comment]
Totally, sorry for assuming!

In the Scalr module registry, you have options for the repo, module root, and tag prefix. This allows you to have all your modules within a monorepo and specify the path to each one. Then updates are managed by tags.

![CleanShot 2023-12-29 at 10 47 49](https://github.com/AzBuilder/terrakube/assets/72530590/e2eea68a-0985-4422-840d-7acddec35940)

![CleanShot 2023-12-29 at 10 47 54](https://github.com/AzBuilder/terrakube/assets/72530590/1fe02592-fb2e-4f4d-b79d-99cf79246e7b)

This would be awesome to see in terrakube!

**Comment by cfsnate** [comment]
correct, here's an example.

monorepo/terraform/modules/terraform-vsphere-vm-linux

Then managing the versioning with tags.

![CleanShot 2023-12-29 at 11 47 30](https://github.com/AzBuilder/terrakube/assets/72530590/487438b3-8a7f-4784-9ffb-5c2bc6ec048e)

![CleanShot 2023-12-29 at 11 49 54](https://github.com/AzBuilder/terrakube/assets/72530590/992ca001-c73e-4602-94c7-3e6081c914be)

![CleanShot 2023-12-29 at 11 50 00](https://github.com/AzBuilder/terrakube/assets/72530590/a1bd337f-fd83-4d13-a250-d36a44e7978a)

**Comment by alfespa17** [comment]
Thank you @cfsnate, I think I understand the idea now, I will try to add it in the following weeks.

**Comment by alfespa17** [comment]
It took me sometime but I was able to add the feature @cfsnate, it will be available for next version 2.20.0 that we will release next week, you can find more information in the above pull request
