### ISSUE TITLE
Storing access token in local storage instead of session storage

### ISSUE THREAD

**Issue by ilkerispir** [AzBuilder/terrakube#664]
### Feature description 💡

Hello @alfespa17, @jcanizalez; 

As far as I see You store various tokens, such as access tokens, in session storage. The disadvantage of this situation is that I have to log in from the beginning with every new tab. Can we store this token information in cookies instead? In this way, when we close the browser or open Terrakube in a new tab, the session does not end and we do not have to switch to the login page all the time.

![image](https://github.com/AzBuilder/terrakube/assets/37123041/908f60db-40ac-480e-a115-d2299be0a202)

**Comment by alfespa17** [comment]
I have no idea how to fix that, I am not good in React, if anyone would like to help with this issue all help and pull request are welcome.

**Comment by ilkerispir** [comment]
@alfespa17, I can handle it.

**Comment by alfespa17** [comment]
Do you want me to assign you the issue?

**Comment by ilkerispir** [comment]
@alfespa17 yes, please.

**Comment by ilkerispir** [comment]
@alfespa17, I created PR for this issue. Could you please review my PR when you're available?

PR: https://github.com/AzBuilder/terrakube/pull/666

**Comment by alfespa17** [comment]
FIxed in https://github.com/AzBuilder/terrakube/pull/666

**Comment by ilkerispir** [comment]
@alfespa17, first of all, thank you for reviewing and migrating my PR. Could you please deploy a new beta release?

**Comment by alfespa17** [comment]
It will be ready in a few minutes

https://github.com/AzBuilder/terrakube/actions/runs/7454626226
