### ISSUE TITLE
Terrakube Registry support for OpenTofu

### ISSUE THREAD

**Issue by jderieg** [AzBuilder/terrakube#669]
### Feature description 💡

Hi guys,
OpenTofu finally has a Stable release out (1.6.0), and I was testing it out this morning. Terrakube seems to be perfectly fine with it, until I try to reference something in our Terrakube Registry using `tofu plan`. Then I get the following error:
![2024-01-10_11-10](https://github.com/AzBuilder/terrakube/assets/63372114/8893dfb5-2639-4923-b929-b900f2438ffa)

If I switch back to `terraform plan` it works fine accessing the Terrakube registry.
Wondering if you know why the Terrakube registry might be throwing that error.
I don't see any error output in the registry or api pods in Terrakube either.

I realize the OpenTofu stable release just came out today, and I know this probably isn't your top priority, that's why I put this under the 'enhancement' label. Low priority. Thanks guys!

**Comment by alfespa17** [comment]
Thank you @jderieg I will start checking how to integrate tofu now there is a stable release, it will take some weeks but I will add support

**Comment by alfespa17** [comment]
It looks like it is related to this.

https://opentofu.org/docs/internals/module-registry-protocol/#download-source-code-for-a-specific-module-version

We only support X-Terraform-Get in the http response headers and terrakube return 200 but we should return 204, if we return 200 tofu is expecting a JSON response .

It will be an easy fix.

**Comment by alfespa17** [comment]
We only need to change this part of the code.

https://github.com/AzBuilder/terrakube/blob/df56b30882c983902ca1ad2bb5012c89ee6bdb93/registry/src/main/java/org/terrakube/registry/controller/ModuleWebServiceImpl.java#L54

**Comment by alfespa17** [comment]
Hello @jderieg  I added tofu support from version 2.19.0-beta.5 if you would like to test it, all feedback is welcome and more information can be found in the PR #675, 

There are something things that will require some work in the UI to select for example the version but at least is a good start.
