### ISSUE TITLE
CORS error for some api calls from UI

### ISSUE THREAD

**Issue by sigurdurf** [AzBuilder/terrakube#693]
### Bug description 🐞

Some PATCH requests from our deployed UI seem to fail due to a CORS error. I found examples of job approving/rejecting not working and also workspace updating failing as well.

I am wondering if this a bug with the underlying API or just configuration misstep on my part. Is there some configuration I can apply to the helm chart to set the allowed methods and/or origins?

CORS error from the JS console (URLs and UUIDs omitted for privacy and brevity)
```
Access to XMLHttpRequest at '<TERRAKUBE_API_URL>/api/v1/organization/<ID>/workspace/<ID>' from origin '<TERRAKUBE_UI_URL>' has been blocked by CORS policy: Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.
```

### Jobs
* Send an API request to create a new job (Make sure the job requires approval)
* Go to the UI and wait for the "approval pending" state to appear.
* Click either reject or approve 
* The javascript console will log out a cors error message 

### State locking
* Create a new workspace with an api driven workflow
* Open the workspace and press the "unlock" button 
* The javascript console will log out a cors error message

### Expected behavior

Patch requests should be allowed from the UI to update the state. 

### Anything else?

Our setup uses the offical AzBuilder helm chart inside a kubernetes cluster. 
We are using the newest release (Helm: 3.12.0 & terrakube: 1.29.0).

**Comment by alfespa17** [comment]
Hello @sigurdurf 

I was testing from the UI a small approval like this:

![image](https://github.com/AzBuilder/terrakube/assets/4461895/0fe8a945-1215-488e-b5de-98a235345152)

I dont see any cors error, the opstions request return 200 as you can see here

![image](https://github.com/AzBuilder/terrakube/assets/4461895/3b524fe1-0ffc-44a5-aba6-95693efa382a)

![image](https://github.com/AzBuilder/terrakube/assets/4461895/7015a422-a07d-449c-90fb-5589f133b293)

![image](https://github.com/AzBuilder/terrakube/assets/4461895/2a590118-bbc3-4ced-84d8-4ba5c52503f4)

If you want to approve a job make your use belongs to the approval team:

![image](https://github.com/AzBuilder/terrakube/assets/4461895/1d335efa-ebde-4dbb-ba32-ba6bc00858be)

![image](https://github.com/AzBuilder/terrakube/assets/4461895/7791a9f3-7f21-4aea-a9d2-6d9b39cfa10b)

Could you share an screenshot of your error?

**Comment by sigurdurf** [comment]
Yeah no problem.
Here is the cors error.
![Screenshot 2024-02-06 at 13 25 01](https://github.com/AzBuilder/terrakube/assets/7071670/69600fe8-9fae-424c-8a98-2acd935a079c)

I don't really think this is bug, more of a configuration issue but I cannot find any reference to configuring cross-domain communications in the docs.

The user is part of the TERRAKUBE_ADMIN group and the same request works fine via direct api access (postman)

![Screenshot 2024-02-06 at 13 32 40](https://github.com/AzBuilder/terrakube/assets/7071670/58990467-b183-4b19-8de6-f8833b86d8a1)

Same goes with the jobs endpoint, the error is just related to cors since communicating directly with the API works fine.

Are there any configuration considerations to have when the domains for the ui and api are different? i.e 
terrakube-api.example.com and terrakube-ui.example.com (both have the same root domain)


I don't expect you to solve my config problems so this likely shouldn't be marked as a bug so feel free to close this issue and I'll find a better place for finding a fix to this

**Comment by alfespa17** [comment]
You could check the API loads when the application is staring, you should be able to see something like the following the check the URL that will be allowed by CORS

```
2024-02-06 17:13:58.571  INFO 4968 --- [           main] o.t.r.c.a.dex.DexWebSecurityAdapter      : CORS for UI Domain https://3000-azbuilder-terrakube-bwbhy1nwt2d.ws-us108.gitpod.io
```
