### ISSUE TITLE
Unable to migrate state from Terraform Cloud to Terrakube using steps in documentation

### ISSUE THREAD

**Issue by dcopestake** [AzBuilder/terrakube#695]
### Bug description 🐞

I'm trying to following the [Terrakube documentation to migrate state from Terraform Cloud into Terrakube](https://docs.terrakube.io/user-guide/migrating-to-terrakube), however this doesn't appear possible as following the steps just results in the error:

```
Initializing Terraform Cloud...
╷
│ Error: Invalid command-line option
│
│ The -migrate-state option is for migration between state backends only, and is not applicable when using Terraform Cloud.
│
│ State storage is handled automatically by Terraform Cloud and so the state storage location is not configurable.
```

### Steps to reproduce

Assuming some existing config using a `cloud` configuration block which points to `app.terraform.io`:

1. Run `terraform init` to initialise against Terraform Cloud backend
2. Change the `cloud` block `hostname` to Terrakube API endpoint
3. Run `terraform init --migrate-state`

### Expected behavior

State is copied from Terraform Cloud workspace to the new workspace in Terrakube.

**Comment by dcopestake** [comment]
Looking at this a bit further, if you add an interim step so simple change from a `cloud` block to a `backend` block instead (but still using the `app.terraform.io` endpoint and _then_ try to `terraform init` you'll see the error:

```
Initializing the backend...
Migrating from Terraform Cloud to backend "remote".
╷
│ Error: Migrating state from Terraform Cloud to another backend is not yet implemented.
│
│ Please use the API to do this: https://www.terraform.io/docs/cloud/api/state-versions.html
```

So I'm somewhat surprised as to how the steps documented in the Terrakube documentation have ever worked as it seems as if migrating _from_ Terraform Cloud has never been a valid path? It seems the `--migrate-state` switch is just for moving between other backends (i.e. `s3` to `local` etc.)?

**Comment by alfespa17** [comment]
Hello @dcopestake 

I think we need to update the documentation,

 if you are using the "cloud block" backend  in terraform you can do a terraform pull to download the statefile from terraform cloud, and later you can do a terraform push to upload the state to Terrakube.

**Comment by alfespa17** [comment]
Yes you can only doing it manually, we are creating a feature to make it easier in the PR

https://github.com/AzBuilder/terrakube/pull/694

it will be available in the next version.

**Comment by dcopestake** [comment]
Amazing. I don't suppose you have any idea when that feature/the new version will be released @alfespa17? I've got about 320 workspaces to migrate so if there is any way I can avoid having to do that manually with a `pull` and `push` it would certainly be helpful!

**Comment by alfespa17** [comment]
We usually release a new stable version every 2 months but if we have some interesting feature like that we would like to test, we release a beta version every 1 or 2 weeks so we can receive feedback or if someone would like to try it.

Not sure when @jcanizalez will have time to finish that, I saw the PR yesterday , maybe he can give you a better idea when it will be ready if you would like to test it.

For now the only way to migrate is do it manually doing a lot of pull/push

**Comment by jcanizalez** [comment]
Hi @alfespa17 and @dcopestake, I am planning to release a beta version of this feature at the end of this week or the beginning of next week. It would be helpful if you could test it and provide feedback. I will let you know once it's ready.
Thank you

**Comment by dcopestake** [comment]
Absolutely @jcanizalez. I'll keep an eye out for it.

**Comment by jcanizalez** [comment]
@alfespa17 and @dcopestake, I have released a preview in version 2.20.0-beta and updated the documentation for both approaches to migrate to Terrakube. You can find the information here: https://docs.terrakube.io/user-guide/migrating-to-terrakube.

**Comment by dcopestake** [comment]
Excellent, thanks @jcanizalez. I'll give the importer a go 👍

**Comment by dcopestake** [comment]
Raised issue https://github.com/AzBuilder/terrakube/issues/705 relating to the new beta Workspace Importer feature @alfespa17.
