### ISSUE TITLE
No Terraform Version available

### ISSUE THREAD

**Issue by patsch9** [AzBuilder/terrakube#699]
Hey,

i have installed terrakube in a kubernetes env that working behind a corporate proxy server for internet traffic.

In my values.yaml is the following terraform url and proxy configuration:
`terraformReleasesUrl: https://releases.hashicorp.com/terraform/index.json
api:
  env:
  - name: http_proxy
    value: "http://XXX8080"
  - name: https_proxy
    value: "http://XXX:8080"
  - name: no_proxy
    value: "XXX,10.0.0.0/8,127.0.0.1,localhost"

executor:
  env:
  - name: http_proxy
    value: "http://XXX8080"
  - name: https_proxy
    value: "http://XXX:8080"
  - name: no_proxy
    value: "XXX,10.0.0.0/8,127.0.0.1,localhost"
`

The Terraform Version select box is empty in the interface
![image](https://github.com/AzBuilder/terrakube/assets/47031716/749e4f89-3702-486f-b0b1-57c074e2ca8c)

The log of the api container shows:
![image](https://github.com/AzBuilder/terrakube/assets/47031716/382ff9a6-a476-4c34-9413-b1ce0c87ca23)

but it looks like the sample data was loaded
![image](https://github.com/AzBuilder/terrakube/assets/47031716/0427ad05-b8a6-48e1-8fbf-0768f81ca0a9)

I have verified that the proxy is reachable from the containers.

can someone help so that i can select the version.

Best Regards,
Patrick

**Comment by alfespa17** [comment]
Hello @patsch9.

If for some network restriction you are not able to use https://releases.hashicorp.com/terraform/index.json, you can customize that URL and provide some internal URL, check [this](https://docs.terrakube.io/getting-started/deployment/custom-terraform-cli-builds).

In the helm chart you can customize the URL like this example

```
api:
  terraformReleasesUrl: "https://eov1ys4sxa1bfy9.m.pipedream.net/"
```

**Comment by patsch9** [comment]
> Hello @patsch9.
> 
> If for some network restriction you are not able to use https://releases.hashicorp.com/terraform/index.json, you can customize that URL and provide some internal URL, check [this](https://docs.terrakube.io/getting-started/deployment/custom-terraform-cli-builds).
> 
> In the helm chart you can customize the URL like this example
> 
> ```
> api:
>   terraformReleasesUrl: "https://eov1ys4sxa1bfy9.m.pipedream.net/"
> ```

a curl to https://releases.hashicorp.com/terraform/index.json is possible with the proxy envs

**Comment by alfespa17** [comment]
I am not sure how you could add he proxy settings at runtime when the container is starting I will have to do some research, we are using buildpack to generate the container I guess there should be a way to add it

**Comment by alfespa17** [comment]
Could you try adding this environment variable to the API, Registry and Executor

```
JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=your.proxy.net -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts=XXXXX"
```

It looks like for buildpacks at runtime you can use that environmen variable according to [this](https://paketo.io/docs/howto/java/#configure-the-jvm-at-runtime).

And to setup a proxy for a spring app you need to setup some parameters according to this [answer](https://stackoverflow.com/questions/30168113/spring-boot-behind-a-network-proxy).

JVM [Reference](https://docs.spring.io/spring-integration/reference/http/proxy.html#standard-java-proxy-configuration)

**Comment by patsch9** [comment]
`JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=your.proxy.net -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts=XXXXX -Dhttps.proxyHost=your.proxy.net -Dhttps.proxyPort=8080 -Dhttps.nonProxyHosts=XXXXX"
`
worked for me.

Thank you!

**Comment by alfespa17** [comment]
I am glad that it work for you, I think I will add that information to the documentation so if anyone else have the same problem the information will be available in our docs site
