### ISSUE TITLE
tofu outputs does not work with Terrakube's "cloud" backend

### ISSUE THREAD

**Issue by marcinwyszynski** [AzBuilder/terrakube#701]
### Bug description 🐞

Hello from OpenTofu land. A user reported this to us last week:

```
…/infrastructure/workloads/dev  feature/upcloud-tests *? 6s ❯ tofu output                                                                             
|
│ Error: could not read state version outputs: resource not found
```

I performed some investigation and figured out that:
- Terrakube does not implement the endpoint on which this calls depends for the cloud backend
  - proof - [Terrakube code](https://github.com/AzBuilder/terrakube/blob/ec6f3181040c26667a10a97ab51cb61e2d4aa9a9/api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java), [TFC API spec](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/state-version-outputs#show-current-state-version-outputs-for-a-workspace), [OpenTofu code](https://github.com/opentofu/opentofu/blob/main/internal/cloud/state.go#L522-L526);
- Terrakube returns 404 for an unknown path
  - this is just a theory, I don’t know where to find it for the Java web framework you're using;
- On receiving 404 from the web server, the TFE client version OpenTofu uses interprets it as a [“resource not found”](https://github.com/hashicorp/go-tfe/blob/v1.36.0/tfe.go#L906-L907);

### Steps to reproduce

Create a workspace with outputs using the `cloud` backend, try to retrieve these outputs with the `tofu outputs` command.
Most likely this error is going to appear with legacy Terraform at least as of the date of the fork because this call remains identical.

### Expected behavior

Outputs are shown correctly.

### Anything else?

As a workaround, the "remote" backend should work because its implementation simply pulls and parses the entire state.

**Comment by alfespa17** [comment]
Thank you @marcinwyszynski, you are correct that endpoint is not implemented yet, that is why you see the 404 error, I will add it in the following days.

**Comment by marcinwyszynski** [comment]
Thanks!

I'm curious though, do you think it would make sense to have the router middleware return something else than 404 for those "not implemented" scenarios? The problem is that 404 maps to this "resource not found" interpretation on the client, which often also indicates insufficient permissions. If the middleware returned something more explicit like [501 Not Implemented](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501) for the unknown API routes, folks would have an easier time understanding (and reporting) compatibility issues. This may be useful because you're working against a largely undocumented`*` API by a third party who don't necessarily wish you well.

`*` I mean, the documentation is there, but you would not know which of the API calls need to be implemented for the CLI to function properly.

**Comment by alfespa17** [comment]
Yeah I think that is a good idea, by default spring framework return 404 when a request is not mapped by any controller but I think I can change that behavior to return a htpñtp 501 implementing a default controller for those scenarios.

Thank you for the feedback @marcinwyszynski
