### ISSUE TITLE
Workspace Importer does not appear to import workspace tags from Terraform Cloud

### ISSUE THREAD

**Issue by dcopestake** [AzBuilder/terrakube#709]
### Bug description 🐞

It doesn't appear as if importing a workspace from Terraform Cloud using the new Workspace Importer also copies the tags. For example, in Terraform Cloud if I have:

<img width="828" alt="Screenshot 2024-02-14 180017" src="https://github.com/AzBuilder/terrakube/assets/5802381/cd44c624-d290-4d76-91d3-77159b4ce7f7">

(Note the tag `terrakube-test`)

After importing into Terrakube the tag doesn't appear to be on the workspace:

<img width="1424" alt="Screenshot 2024-02-14 180127" src="https://github.com/AzBuilder/terrakube/assets/5802381/d245585a-5a50-440c-920f-f0db43597e25">

### Steps to reproduce

1. Create a workspace in Terraform Cloud and add any tag
2. Use the Workspace Importer to import the workspace into Terrakube

### Expected behavior

Workspace tag(s) should be imported alongside the workspace.

**Comment by jcanizalez** [comment]
hi @dcopestake 
Currently, the importer only copies the workspace description, name, terraform version, VCS directory and branch, variables, and current state. Tags are not included at this time. I will check if I can add tags later this month, possibly by next week.
