### ISSUE TITLE
Resources and Outputs don't always show on state import

### ISSUE THREAD

**Issue by adamlc** [AzBuilder/terrakube#711]
### Bug description 🐞

I've been importing 50+ workspaces into Terrakube and mostly things have been OK. But there have been a few that whilst importing OK never seem to show ant resources or outputs. The state is there and everything else functions OK, including plans and applies etc.

It always seems to be the same workspaces. I've tried deleting them and re-adding them again, but the behaviour is always the same. Nothing obvious in the logs. These workspaces vary in size too, between small and large.

![image](https://github.com/AzBuilder/terrakube/assets/809944/d03a989f-a522-44a0-b934-748d1623dcb2)

### Steps to reproduce

Unknown at this time. Is there anything I can do to debug?

**Comment by alfespa17** [comment]
Could you check if there is any error in the browser console when you open the workspace?

The UI parse the state values to show the resources in the UI using this small logic.

https://github.com/AzBuilder/terrakube/blob/191689a34124232295816fad2de38294ffd71075/ui/src/domain/Workspaces/Details.jsx#L1225

**Comment by adamlc** [comment]
![image](https://github.com/AzBuilder/terrakube/assets/809944/fa018146-85b7-4fd9-9980-229760a486aa)

I get the above error on the broken workspaces.

Looking at the request I can see that the resources and outputs are actually returned by the API. So yes it does look like a UI issue!

**Comment by adamlc** [comment]
Looking at the code it looks like child modules are expected to have a [resources key](https://github.com/AzBuilder/terrakube/blob/191689a34124232295816fad2de38294ffd71075/ui/src/domain/Workspaces/Details.jsx#L1278). 

![image](https://github.com/AzBuilder/terrakube/assets/809944/add0674b-d9c9-427b-af67-3b18fbb92d94)

In the case of my resources theres other child modules that have further resources within. So I guess this needs to be a recursive function to go through X child modules and their resources (I think)!

![image](https://github.com/AzBuilder/terrakube/assets/809944/0ed83ead-274f-4c4e-af0e-dd99da2b4668)

**Comment by alfespa17** [comment]
Yes that is correct, I think the code will need some small adjustment in that part, it is quite difficult to parse the state correctly, we have done a lot of adjustment in that particular part over the last couple of months.

I could try to do the adjustment and maybe release a Hotfix later today but I will need some help to test it because I don't have a way to reproduce your state file

**Comment by adamlc** [comment]
Happy to help where possible. Looking at the structure I can imagine what a nightmare it must be!

**Comment by alfespa17** [comment]
I created the following [beta release](https://github.com/AzBuilder/terrakube/releases/tag/2.19.2-beta.1) so you can test the fix in the recursive logic, you will only need to override the UI version like this if you are using the helm chart

```yaml
ui:
  version: "2.19.2-beta.1"
```

**Comment by alfespa17** [comment]
I am glad that it work for you, I will create the hotfix version 2.19.2
