### ISSUE TITLE
Workspace Importer does not import execution mode

### ISSUE THREAD

**Issue by dcopestake** [AzBuilder/terrakube#723]
### Bug description 🐞

We have a lot of workspaces that are using local execution mode in Terraform Cloud (i.e. where we're just using it for state management), however I've noticed that regardless of what the value is set to in Terraform Cloud, when the workspace gets imported it always gets imported as execution mode of `remote`.

### Steps to reproduce

1. Create a workspace in Terraform Cloud with an execution mode set to Local
2. Use the Terrakube Workspace Importer to import the workspace using CLI-driven workflow
3. Check the execution mode in Terrakube and note it's set to `remote`

### Expected behavior

Execution mode in Terrakube should reflect that from the workspace in Terraform Cloud.

**Comment by jcanizalez** [comment]
You are right we are not importing it, I will check which is the field in the api result and will include it
