### ISSUE TITLE
Workspace Importer is not importing state

### ISSUE THREAD

**Issue by dcopestake** [AzBuilder/terrakube#725]
### Bug description 🐞

I've just noticed that whenever I use the Workspace Importer to import a workspace from Terraform Cloud to Terrakube whilst the actual operation gets reported as being successful, when I actually go to look at the workspace in Terrakube there is no state! Looking at the API log I can see:

```
INFO 1 --- [nio-8080-exec-8] o.t.a.p.i.t.services.WorkspaceService    : VCS ID:
ERROR 1 --- [nio-8080-exec-8] o.t.a.p.i.t.services.WorkspaceService    : URI is not absolute
```

But unfortunately no more information from the log.

The (sanitised) payload being sent to the `workspaces/` endpoint in this case was:

```
{
    "organizationId": "xxxxxxxx-8372-4fec-8500-xxxxxxxxxxxx",
    "vcsId": "",
    "id": "ws-49WuV6tyxxxxxxxx",
    "organization": "xxxxxx",
    "name": "xxxxxx-xxxxxxx-xxxxxxxxxx",
    "terraformVersion": "1.5.7",
    "description": null
}
```

I've tried this for a few of our workspaces and unfortunately I seem to get the same issue each time.

### Steps to reproduce

1. Import a workspace from Terraform Cloud using the Workspace Importer
2. Check the imported workspace and look at the empty state

### Expected behavior

State should be imported.

**Comment by dcopestake** [comment]
@jcanizalez let me know if there is anything I can help do/provide you to help fix this. I'm aware I haven't really been able to give much in the way of information to help you find the issue!

**Comment by jcanizalez** [comment]
Hi @dcopestake, I have a quick question. When you see the workspace overview page in Terrakube, can you see the resources and outputs or not?

**Comment by dcopestake** [comment]
Hi @jcanizalez. Nope I'm afraid not, both show as zero. This is the overview in Terraform Cloud:

<img width="610" alt="Screenshot 2024-02-18 191206" src="https://github.com/AzBuilder/terrakube/assets/5802381/1d41c138-c483-4009-a4fd-80e032bb20d4">

And in Terrakube after the import:

<img width="573" alt="Screenshot 2024-02-18 191227" src="https://github.com/AzBuilder/terrakube/assets/5802381/3d02bf37-e3ba-42fc-8336-b8f4b9348221">

Another thing I've noticed is that when I load the workspace I see the following error in the API log:

```
INFO 1 --- [nio-8080-exec-8] o.t.a.p.s.aws.AwsStorageTypeServiceImpl  : Searching: tfstate/61b97217-xxxx-xxxx-xxxx-xxxxxxxxxxxx/8cef7974-xxxx-xxxx-xxxx-xxxxxxxxxxxx/state/48a35222-xxxx-xxxx-xxxx-xxxxxxxxxxxx.json
ERROR 1 --- [nio-8080-exec-8] o.t.a.p.s.aws.AwsStorageTypeServiceImpl  : S3 Not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 4RT8R4EQxxxxxxxx; S3 Extended Request ID: GgYFGAddf2E1j3bPtMe6ReaLX084srk6f6axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=; Proxy: null)
```

Looking at the S3 bucket we're using for storage I do indeed see no state stored there (however there is other content from the registry etc. there, so I don't think it's an issue there).

**Comment by iam-take** [comment]
We experienced the same issue when trying to migrate state into Terrakube. We had used the Azure Storage Account as backend storage for Terrakube. When looking into the API log we see the same kind of logging as @dcopestake. One difference is that I did see the state file in the Azure Storage Account. It just shows as empty in Terrakube.

It seems not to matter where your orginal state is located the import goes wrong.

**Comment by jcanizalez** [comment]
Hello @dcopestake, I'm currently developing and testing the importer from Gitpod using local storage, and it's working well. Based on the feedback provided by you and @iam-take, I suspect the issue might be related to use the importer with a cloud storage. I need to create an Azure storage account or use S3 to test it in that environment. I will try to configure environment this week to debug

**Comment by alfespa17** [comment]
> Hello @dcopestake, I'm currently developing and testing the importer from Gitpod using local storage, and it's working well. Based on the feedback provided by you and @iam-take, I suspect the issue might be related to use the importer with a cloud storage. I need to create an Azure storage account or use S3 to test it in that environment. I will try to configure environment this week to debug

When you open gitpod you can use the following command in the terminal.

```shell
./scripts/setupDevelopmentEnvironmentMinio.sh
```

It will do all the setup so you can use MINIO as backend storage inside Gitpod, that is basically the same code that when you are using a S3 in AWS. I think that can help you to test

**Comment by dcopestake** [comment]
Thanks @jcanizalez. I'll deploy the new build temporarily so I can get the additional log output to help debug this and then revert I think as we're actively using the module registry.

**Comment by dcopestake** [comment]
@jcanizalez so using the `2.20.0-beta.3` build for the UI and API I now see this in the UI:

<img width="590" alt="Screenshot 2024-02-22 093034" src="https://github.com/AzBuilder/terrakube/assets/5802381/ab5a9484-9efc-4257-bc55-56a9fcb0c000">

From the API log I see:

```
WARN 1 --- [nio-8080-exec-4] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.context.request.async.AsyncRequestTimeoutException]
INFO 1 --- [nio-8080-exec-8] o.t.a.p.i.t.services.WorkspaceService    : url: https://app.terraform.io/api/v2/organizations/******/workspaces?page[size]=50&page[number]=1
INFO 1 --- [nio-8080-exec-8] o.t.a.p.i.t.services.WorkspaceService    : url: https://app.terraform.io/api/v2/organizations/******/workspaces?page[size]=50&page[number]=2
INFO 1 --- [nio-8080-exec-8] o.t.a.p.i.t.services.WorkspaceService    : url: https://app.terraform.io/api/v2/organizations/******/workspaces?page[size]=50&page[number]=3
INFO 1 --- [nio-8080-exec-8] o.t.a.p.i.t.services.WorkspaceService    : url: https://app.terraform.io/api/v2/organizations/******/workspaces?page[size]=50&page[number]=4
INFO 1 --- [nio-8080-exec-8] o.t.a.p.i.t.services.WorkspaceService    : url: https://app.terraform.io/api/v2/organizations/******/workspaces?page[size]=50&page[number]=5
INFO 1 --- [nio-8080-exec-8] o.t.a.p.i.t.services.WorkspaceService    : url: https://app.terraform.io/api/v2/organizations/******/workspaces?page[size]=50&page[number]=6
WARN 1 --- [io-8080-exec-10] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.context.request.async.AsyncRequestTimeoutException]
INFO 1 --- [nio-8080-exec-9] o.t.a.p.i.t.services.WorkspaceService    : Importing Workspace: *******-*********-*****
INFO 1 --- [nio-8080-exec-9] o.t.a.p.i.t.services.WorkspaceService    : Workspace created: ad27d466-****-****-836d-bf37348c69f1
INFO 1 --- [nio-8080-exec-9] o.t.a.p.i.t.services.WorkspaceService    : Variables imported: 0
INFO 1 --- [nio-8080-exec-9] o.t.a.p.i.t.services.WorkspaceService    : Tags imported: 0
INFO 1 --- [nio-8080-exec-9] o.t.a.p.i.t.services.WorkspaceService    : State download URL: https://app.terraform.io/api/state-versions/sv-eDCm********esBv/hosted_state
INFO 1 --- [nio-8080-exec-9] o.t.a.p.i.t.services.WorkspaceService    : State download JSON URL: null
INFO 1 --- [nio-8080-exec-9] o.t.a.p.i.t.services.WorkspaceService    : History created: 92ac0a0b-****-****-aac8-441b25b580ec
RROR 1 --- [nio-8080-exec-9] o.t.a.p.i.t.services.WorkspaceService    : URI is not absolute
```

Hopefully this helps. Let me know if I can provide anything else.

**Comment by dcopestake** [comment]
Ah okay, so I think I see the issue. For all the workspaces I've tried importing they would all have been created with Terraform binaries earlier than 1.3, and looking at [the API documentation on this](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/state-versions):

> `hosted-json-state-download-url` A URL from which you can download the state data in a [stable format](https://developer.hashicorp.com/terraform/internals/json-format) appropriate for external integrations to consume. Only available if the state was created by Terraform 1.3+.

So I think this explains why in we're seeing the `null` value for the `hosted-json-state-download-url` key in our `/api/v2/workspaces/<workspace-id>/current-state-version` responses @jcanizalez.

**Comment by alfespa17** [comment]
> hosted-json-state-download-ur

"hosted-json-state-download-ur" is an optional field that show the "json state representation" and we use that format to show the state in the UI.
As far as I remember there are no other way to get that json value using the TFC API, so I guess for worspaces using terraform version below 1.3 could be imported but the state history in the UI will be empty until an apply is executed that generated the "json state represetantion".

**Comment by dcopestake** [comment]
The slightly strange thing is, we have workspaces created recently using versions _above_ 1.3 and these are _also_ returning `null` for this field 🤔

**Comment by jcanizalez** [comment]
Thanks @dcopestake 
This information has been invaluable; finally, I succeeded in recreating the issue by using a workspace with Terraform versions earlier than 1.3. I have updated the importer to import the state, allowing its use even if the JSON state is not available. However, it will display a warning like this:

<img width="861" alt="image" src="https://github.com/AzBuilder/terrakube/assets/27365102/7ff8f4d8-f79e-403b-a3de-cbf3aa2695cf">

**Comment by jcanizalez** [comment]
I have added this to 2.20.0-beta.4  if you want to test it. However, it has a known issue, #733, due to which you won't be able to see the Modules in the Registry section. You can either try this version or wait for the next beta release, in which we will attempt to fix this issue.

**Comment by dcopestake** [comment]
Excellent. Thanks for the swift response fixing this @jcanizalez 👍

**Comment by dcopestake** [comment]
Hi @jcanizalez. Apologies I've only just been able to try this again as I'm now able to test using [2.20.0-beta.6](https://github.com/AzBuilder/terrakube/releases/tag/2.20.0-beta.6).

Whilst the process seems to complete (with the same warning you show above about not having the JSON state file):

<img width="598" alt="Screenshot 2024-02-24 143051" src="https://github.com/AzBuilder/terrakube/assets/5802381/3be58572-c3fe-4349-9b11-172978230089">

The imported workspaces still show like they don't have any resources when I actually view them:

<img width="550" alt="Screenshot 2024-02-24 143822" src="https://github.com/AzBuilder/terrakube/assets/5802381/0b951658-ec8b-4488-b6e5-90d9b6ff8340">

Is this expected given the fact the JSON state hasn't been imported?

One thing I have noticed is that I'm seeing 404 responses from the `AwsStorageTypeServiceImpl` in the API log when I view the imported workspaces:

```
INFO 1 --- [nio-8080-exec-1] o.t.a.p.s.aws.AwsStorageTypeServiceImpl  : Searching: tfstate/61b97217-****-****-8500-196861554237/54034722-****-****-9531-bb352a9e6111/state/5874cfef-****-****-bc52-61da45c879d2.json
ERROR 1 --- [nio-8080-exec-8] o.t.a.p.s.aws.AwsStorageTypeServiceImpl  : S3 Not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 4NM6Z******H2SXK; S3 Extended Request ID: 246/XjEM******P5/a8jklLh+mAj********************oG661I/nhkBf2FjYGNLqZxWNklESgQlc7liUFA==; Proxy: null)
```

Does this mean the resources list and count etc. won't be shown because there is no JSON state file? 🤷‍♂️

**Comment by alfespa17** [comment]
Yes that is correct, right now the UI is using the json state representation to parse the outputs, resources, etc. If there is no json state representation what you could do is run a remote apply with no changes that will generate a json state because it will run a terraform show -json after running the apply.

**Comment by dcopestake** [comment]
Unfortunately @alfespa17 with a lot of our workspaces we can't (currently) use remote applies I'm afraid because of some of the connectivity needed (bit of a long story).

Is there any other way of being able to generate the JSON state? I've noticed that doing a `terraform state pull` from Terraform Cloud and then a `terraform state push` to Terrakube doesn't seem to show this issue, even though the JSON state isn't there in Terraform Cloud 🤔

Unfortunately we have a large number of workspaces to migrate, so ideally I'd like to be able to use the importer to do that rather than manually pull/pushing each one if at all possible 🙏

**Comment by dcopestake** [comment]
Thanks for the response/explanation @alfespa17. I think fundamentally this bug as it originally stands is now fixed as the importer is no longer erroring. Unfortunately I think for my use case it means we won't really be able to use it though as we have so many workspaces created earlier than 1.3 and seeing the zero resources etc. is going to be confusing.

Thanks again to @jcanizalez for the help fixing this.
