### ISSUE TITLE
Cannot access internet if behind Web Proxy

### ISSUE THREAD

**Issue by SolomonHD** [AzBuilder/terrakube#744]
### Bug description 🐞

terrakube-api cannot access internet to download modules/templates when behind a web proxy. I've added the usual HTTP_PROXY,  HTTPS_PROXY, and NO_PROXY environment variables to no effect.

### Steps to reproduce

start terrakube-api behind web proxy and set env vars for it, error messages about timeouts to different modules will appear in the log.

### Expected behavior

terrakube-api uses http_proxy to access internet.

### Anything else?

Please let me know if any container in the stack besides tk-api needs internet access.

**Comment by alfespa17** [comment]
Hello @SolomonHD 

You can check this documentation:

https://docs.terrakube.io/getting-started/deployment/proxy-configuration

You can also check this issue.

https://github.com/AzBuilder/terrakube/issues/699

**Comment by SolomonHD** [comment]
Thank you!
