### ISSUE TITLE
Workspaces with no imported JSON formatted state show zero resources/outputs

### ISSUE THREAD

**Issue by dcopestake** [AzBuilder/terrakube#759]
### Bug description 🐞

This is closely related to https://github.com/AzBuilder/terrakube/issues/725.

For workspaces that were imported from a Terraform Cloud workspace created prior to Terraform 1.3 - and therefore do not include the JSON formatted state - when viewing the workspace the workspace overview page will show zero resources/outputs. This is a little confusing as the non-JSON state _is_ present and does contain resources.

### Steps to reproduce

1. Import a workspace _without_ JSON state available
2. Open the workspace overview page in Terrakube

### Expected behavior

Perhaps just not showing the resources/outputs table and instead showing a message to say that no JSON state is present would be the most simple option? Or better yet, driving this portion of things from the non-JSON state so the resources could be shown as with any other workspace, but I accept that this is probably not trivial!

**Comment by alfespa17** [comment]
Did some progress in #760

**Comment by alfespa17** [comment]
Hello @dcopestake  I think I got this working in version 2.20.0-beta.9, maybe when you have some time you could test with some of your workspaces

![image](https://github.com/AzBuilder/terrakube/assets/4461895/4c398bfc-c52c-482a-a17b-d758ca72e941)

![image](https://github.com/AzBuilder/terrakube/assets/4461895/b0ed0fd7-3533-41ce-9569-5f30c2a2ca04)

![image](https://github.com/AzBuilder/terrakube/assets/4461895/cb501975-82d3-4b09-aad0-3e3c2de5bc19)

All feedback is welcome
