### ISSUE TITLE
Support beta tags for terraform modules in terrakube registry

### ISSUE THREAD

**Issue by mishafeingold** [AzBuilder/terrakube#774]
### Feature description 💡

In terraform cloud, they [support a prerelease version](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#version-constraint-behavior). 
> A prerelease version is a version number that contains a suffix introduced by a dash, like 1.2.0-beta. A prerelease version can be selected only by an exact version constraint (the = operator or no operator). Prerelease versions do not match inexact operators such as >=, ~>, etc.

I tried pushing up a tag to github with the value `v1.0.0-beta.1` (I also tried v1.0.0-beta, and v1.0.0-0.0.1) and see that the module is in the terrakube registry. However when I try to upgrade the module from the callers code (ie `version = "v1.0.0-beta.1"`), it fails and states the version doesn't exist and shows the previous x.x.x semver version as the "Latest"
```
tfi -upgrade

Initializing Terraform Cloud...
Upgrading modules...
╷
│ Error: Unresolvable module version constraint
│
│   on cloud-sql.tf line 1:
│    1: module "pg_db" {
│
│ There is no available version of module "terrakube-reg.xxx.xxxx.xxxx/vtg-devops/terraform-google-sql-db/google" (cloud-sql.tf:1) which matches the given version constraint. The newest available version is 0.2.0.
```
![Screenshot 2024-03-20 at 3 37 41 PM](https://github.com/AzBuilder/terrakube/assets/7771369/981a9e5d-96ae-45da-8a96-06ca9126b975)

It would be great to have support for beta tags, as we can test the beta modules in other repos before making a full release.

**Comment by alfespa17** [comment]
I will check this tomorrow, not sure why is not working

**Comment by alfespa17** [comment]
Hello @mishafeingold  I did a small test and for me is working correctly.

# Terraform Module

![image](https://github.com/AzBuilder/terrakube/assets/4461895/5d3e8120-1d28-4c8b-a1e2-442458ec09fe)

![image](https://github.com/AzBuilder/terrakube/assets/4461895/5689b486-5481-41ce-bd23-db4a41fea8e7)


# Terraform Code
```terraform
module "rg" { 
  source = "8075-azbuilder-terrakube-sgx9hlsf66d.ws-us110.gitpod.io/simple/rg/azurerm" 
  version = "1.0.2-beta.1" 
  # insert required variables here 
}
```
# Terraform Init
```shell
user@pop-os:~/git/simple-terraform$ terraform init
Initializing modules...
Downloading 8075-azbuilder-terrakube-sgx9hlsf66d.ws-us110.gitpod.io/simple/rg/azurerm 1.0.2-beta.1 for rg...
- rg in .terraform/modules/rg
- time_module in module

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/time...
- Finding hashicorp/azurerm versions matching "3.5.0"...
- Finding latest version of hashicorp/random...
- Finding latest version of hashicorp/azuread...
- Finding latest version of hashicorp/null...
- Installing hashicorp/time v0.11.1...
- Installed hashicorp/time v0.11.1 (signed by HashiCorp)
- Installing hashicorp/azurerm v3.5.0...
- Installed hashicorp/azurerm v3.5.0 (signed by HashiCorp)
- Installing hashicorp/random v3.6.0...
- Installed hashicorp/random v3.6.0 (signed by HashiCorp)
- Installing hashicorp/azuread v2.47.0...
- Installed hashicorp/azuread v2.47.0 (signed by HashiCorp)
- Installing hashicorp/null v3.2.2...
- Installed hashicorp/null v3.2.2 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
``

**Comment by alfespa17** [comment]
I think I got the issue, the problem is when the module version starts with letter "v"

```
module "rg" { 
  source = "8075-azbuilder-terrakube-sgx9hlsf66d.ws-us110.gitpod.io/simple/rg/azurerm" 
  version = "v1.0.2-beta.2" 
  # insert required variables here 
}
```

I got the error:

```
user@pop-os:~/git/simple-terraform$ terraform init
Initializing modules...
- time_module in module
╷
│ Error: Error accessing remote module registry
│ 
│ Failed to retrieve available versions for module "rg" (main.tf:45) from
│ 8075-azbuilder-terrakube-sgx9hlsf66d.ws-us110.gitpod.io: host does not provide a modules service.
╵

╷
│ Error: Error accessing remote module registry
│ 
│ Failed to retrieve available versions for module "rg" (main.tf:45) from
│ 8075-azbuilder-terrakube-sgx9hlsf66d.ws-us110.gitpod.io: host does not provide a modules service.
╵

╷
│ Error: Error accessing remote module registry
│ 
│ Failed to retrieve available versions for module "rg" (main.tf:45) from
│ 8075-azbuilder-terrakube-sgx9hlsf66d.ws-us110.gitpod.io: host does not provide a modules service.

```

**Comment by jderieg** [comment]
Hi @alfespa17 just curious what version of Terrakube you're running your test on? We're running version 2.19.2, installed with helm chart version 3.14.2 (I work with @mishafeingold ). I wonder if it's a problem on a specific version?

**Comment by jderieg** [comment]
ah, I just saw your last comment. Yeah, we use 'v' at the beginning of pretty much all of our version tags.

**Comment by alfespa17** [comment]
hello @mishafeingold  @jderieg I did some test with the following:

Module:

![image](https://github.com/AzBuilder/terrakube/assets/4461895/d77b9fdb-480a-4bed-915a-8d486eed3928)

If you run the module like this it will fail.

```
module "rg" { 
  source = "8075-azbuilder-terrakube-sgx9hlsf66d.ws-us110.gitpod.io/simple/rg/azurerm" 
  version = "v1.0.2-beta.2" 
  # insert required variables here 
}
```

Checking the TF_LOGS=TRACE, I see one message 

```
2024-03-21T10:36:17.335-0600 [WARN]  ModuleInstaller: rg ignoring 1.0.2-beta.2 because the version constraints (v1.0.2-beta.2) could not be parsed: a "v" prefix should not be used when specifying versions
```

If I run the terraform like the following without using the letter "v" at the beginning , it will work:

```
module "rg" { 
  source = "8075-azbuilder-terrakube-sgx9hlsf66d.ws-us110.gitpod.io/simple/rg/azurerm" 
  version = "1.0.2-beta.2" 
  # insert required variables here 
}
```

By the way I was using terraform 1.5.7 to test it.

Not sure if this is a bug in terraform cli or a bug in terrakube when I implement the [registry protocol](https://developer.hashicorp.com/terraform/internals/module-registry-protocol)

**Comment by alfespa17** [comment]
It looks like it related to this part of the terraform cli code:

https://github.com/hashicorp/terraform/blob/ee58ac1851c8a433005df9863ed47796a9f6b5e7/internal/initwd/module_install.go#L453

**Comment by mishafeingold** [comment]
@alfespa17 I just testing terraform cloud and you are correct that it has the same issue. My mistake. I will go ahead and close this as it has feature parity with tf cloud. Thank you!
