### ISSUE TITLE
Plan Job stuck on pending

### ISSUE THREAD

**Issue by gdacal** [AzBuilder/terrakube#785]
### Bug description 🐞

The job remains in plan planning after being triggered by vcs.
![plan_pending](https://github.com/AzBuilder/terrakube/assets/146208139/062d4330-bc10-4bf4-bdd4-37de342fa19d)

The job remains in a queue state with no possibility of canceling the current job.

En los logs el siguiente output
```
terrakube-api-1       | 2024-03-26 17:39:00.391  INFO 1 --- [ryBean_Worker-2] o.t.api.plugin.scheduler.ScheduleJob     : Checking Job 203 Status queue
terrakube-api-1       | 2024-03-26 17:39:00.391  INFO 1 --- [ryBean_Worker-2] o.t.api.plugin.scheduler.ScheduleJob     : Checking previous jobs....
terrakube-api-1       | 2024-03-26 17:39:00.395  INFO 1 --- [ryBean_Worker-2] o.t.api.plugin.scheduler.ScheduleJob     : Job 203 Status queue`
```
Version 2.19.0 but updated to version 2.20.0

### Steps to reproduce

Configure a workspace with vcs integration and configure plan as default template.
Add a commit and wait for the job to run.

### Expected behavior

Workspace in queue state and job stuck in pending plan

**Comment by alfespa17** [comment]
Could you double check the Terrakube version because that was an error in version 2.19.0 that was fixed in 2.19.2 if I remember correctly

**Comment by alfespa17** [comment]
It was related to this [disscussion](https://github.com/orgs/AzBuilder/discussions/714).

**Comment by alfespa17** [comment]
By the way the job status "queue" only happens when the job is triggered and send to the "executor" component, could be the "executor" have some connectivity issue and did not receive the request too

**Comment by alfespa17** [comment]
I will close this issue, feel free to create a new one if you still have the same problem
