### ISSUE TITLE
Version number at the bottom of the page after upgrade to 2.20.0

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#787]
I'm still not seeing the version number at the bottom of the page after upgrade:
![2024-03-27_11-10](https://github.com/AzBuilder/terrakube/assets/63372114/cf0b64bd-16c3-4021-ba96-a7b519b7d92a)

_Originally posted by @jderieg in https://github.com/AzBuilder/terrakube/issues/751#issuecomment-2023339909_

**Comment by alfespa17** [comment]
I think the value REACT_APP_TERRAKUBE_VERSION is missing in [here](https://github.com/AzBuilder/terrakube/blob/main/ui/setupEnv.sh)

**Comment by alfespa17** [comment]
This should be fixed when we release version 2.20.1 using the helm chart 3.16.1

For now it can be tested using 2.20.1-beta.1

**Comment by jderieg** [comment]
Verified this works on 2.20.1-beta.1 using chart 3.16.1. Thanks!!
![2024-04-05_14-23](https://github.com/AzBuilder/terrakube/assets/63372114/f0121f03-6a4a-4cc8-9aeb-371b1069e72f)
