### ISSUE TITLE
Blank White page on workspaces

### ISSUE THREAD

**Issue by defenestration** [AzBuilder/terrakube#793]
### Bug description 🐞

I somehow hit a bug when trying to set up some repos and deleting some. ![image](https://github.com/AzBuilder/terrakube/assets/961130/a93ab801-e38c-42ad-97b2-025df7a1af0a)

### Steps to reproduce

Not quite sure what happened exactly. I was working on setting up workspaces using the same Github repo targeting different folders.  I had created and deleted a few.

I did notice when creating a VCS repo for github, it would auto-create the Workspace with the RepoName. However since i wanted terraform to run out of a subfolder, this was undesirable, though could be edited later. Possibly somehow I some collision in the workspace names is occuring? 

### Expected behavior

Functionality of Workspaces page

### Anything else?

No error is provided in the Network tab, everything is 200s there. i only get the errors in the javascript console shown above. 

I can get to the sample Organizations if i clear cache and first visit the organizations page without going into the organization with the bad workspace.

I can get to the settings page of the organization with the bad workspace via url as well. 

I was able to get to one of the workspaces by looking up the id in the postgres db via /workspaces/$id , but a different workspace does not seem to load so guessing that is the problem one.

I saw API docs but they detail how to connect to the Gitpod instance. Unclear to me if something similar can be done to the instance i deployed with a helm chart.

**Comment by alfespa17** [comment]
Not sure whay you did, but Terrakube does not automatically create a workspace when you crate a VCS Github connection

**Comment by alfespa17** [comment]
To setup the Github VCS connection you can use the following:

https://docs.terrakube.io/user-guide/vcs-providers/github.com

The GITPOD getting started is more developer orientated, but you could check for example this to deploy it in minikube to test with HTTPS support

https://docs.terrakube.io/getting-started/deployment/minikube-+-https

**Comment by jcanizalez** [comment]
@defenestration Is this happen only in one workspace if I understand correctly? Can you compare the record in the database from another workspace working?

Can you check the `source` field  in the database, maybe is not a correct url?

**Comment by defenestration** [comment]
> I did notice when creating a VCS repo for github, it would auto-create the Workspace with the RepoName. However since i wanted terraform to run out of a subfolder, this was undesirable, though could be edited later. Possibly somehow I some collision in the workspace names is occuring?


I made a mistake typing here, i was creating a new Workspace using Github VCS as the source. 

I was able to get the workspaces to display again by changing the record for the workspace to 'deleted' so thanks for the help.

I added the record and note it doesn't show the vcs_id anymore so not sure what happened there. Maybe having a folder set there caused an issue?

FWIW, this is the problem record before i switched it to deleted in the DB.

```
-[ RECORD 2 ]-----+-----------------------------------------------------------------------------------------------------------------------------------------
id                | 14ce7f84-f564-4625-a7a4-2f017be6439a
name              | terraform-user-test-dev
source            | empty
branch            | main
terraform_version | 1.6.0
organization_id   | bb4ab307-2b67-41b0-93ce-96acaa10f9bf
vcs_id            |
description       |
ssh_id            |
folder            | /tf/dev/
locked            | f
deleted           | f
created_date      | 2024-04-04 18:12:16.547
updated_date      | 2024-04-04 20:20:00.131
created_by        | me@my-biz.com
updated_by        | Internal
execution_mode    | remote
module_ssh_key    |
iac_type          | terraform
default_template  | 941c2173-01cb-44d8-b86c-d24d0297e0eb
agent_id          |
```

I appreciate you folks helping me out!

**Comment by defenestration** [comment]
I was actually able to update the `source` column for this workspace in the db, and set deleted back to false, and get this working again, so that seems to have been the problem.
