### ISSUE TITLE
Init, Plan, Apply running but nothing is being applied

### ISSUE THREAD

**Issue by MARVELMafia** [AzBuilder/terrakube#800]
### Feedback

I have managed to install terrakube and connect it to my VCS. However, when I am manually creating a job for Plan and Apply, I see that it is not applying or creating any infrastructure and give the following outputs. 

![image](https://github.com/AzBuilder/terrakube/assets/28630442/a8eca7e4-4b56-4966-9e00-5d12ce539977)

On the kubernets I only see error log on the terrakube-api component:

`2024-04-10 06:08:04.010 ERROR 1 --- [nio-8080-exec-9] o.t.a.p.s.aws.AwsStorageTypeServiceImpl  : S3 Not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 17C4D62C72564518; S3 Extended Request ID: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855; Proxy: null)`

which does not make sense since the init + plan + apply actually run via the Terrakube UI.

I also checked by applying the same repo locally with the same environment variables (including S3 creds) and the infrastructure is getting created as it should.

Also, when I say S3 I am using the [Ceph Object Gateway S3 API](https://docs.ceph.com/en/latest/radosgw/s3/) which is supported via Terraform.

So what am I missing?

**Comment by requiming** [comment]
I have been watching same behaviour sometimes during debugging my issue https://github.com/AzBuilder/terrakube/issues/766, it started to make any real interactions after force pushing previous terraform state.

**Comment by MARVELMafia** [comment]
I did, it all aligns with the o/p I get in Terrakube UI

![image](https://github.com/AzBuilder/terrakube/assets/28630442/0ebe0e85-042d-4fd9-a7c6-f95f70ac5d32)

**Comment by alfespa17** [comment]
> Sure. It aligns with what I see in the Terrakube UI. Here it is:
> 
> ![image](https://private-user-images.githubusercontent.com/28630442/321438702-0ebe0e85-042d-4fd9-a7c6-f95f70ac5d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTYwNDgsIm5iZiI6MTcxMjc5NTc0OCwicGF0aCI6Ii8yODYzMDQ0Mi8zMjE0Mzg3MDItMGViZTBlODUtMDQyZC00ZmQ5LWE3YzYtZjk1ZjcwYWM1ZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAwMzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZjFjZDYzNzBkMDBlMjQ4ODNkNzkwZDgyZTQ2M2ZlNTFhMGY5OTE3Y2Q5MGNjZTM1NjI4MzFhYTJkZDAyZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qLvpiTU6OTEM12UGohpjoTNueWvnCywhjJpLoqFoW28)

Could You check the logs before the message running terraform apply You should see información about the git clone operation

**Comment by MARVELMafia** [comment]
> I have been watching same behaviour sometimes during debugging my issue #766, it started to make any real interactions trought provider after force pushing previous terraform state.
@requiming Thanks. I will try this out. But I am starting from scratch and want to be able to create something from the get go...eventhough I do have statefiles but being able to create infrastructure from scratch is sort of a requirement or else it makes the process rather redundant. :/

**Comment by MARVELMafia** [comment]
> > Sure. It aligns with what I see in the Terrakube UI. Here it is:
> > ![image](https://private-user-images.githubusercontent.com/28630442/321438702-0ebe0e85-042d-4fd9-a7c6-f95f70ac5d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTYwNDgsIm5iZiI6MTcxMjc5NTc0OCwicGF0aCI6Ii8yODYzMDQ0Mi8zMjE0Mzg3MDItMGViZTBlODUtMDQyZC00ZmQ5LWE3YzYtZjk1ZjcwYWM1ZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAwMzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZjFjZDYzNzBkMDBlMjQ4ODNkNzkwZDgyZTQ2M2ZlNTFhMGY5OTE3Y2Q5MGNjZTM1NjI4MzFhYTJkZDAyZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qLvpiTU6OTEM12UGohpjoTNueWvnCywhjJpLoqFoW28)
> 
> Could You check the logs before the message running terraform apply You should see información about the git clone operation

thanks @alfespa17 
I can see there is and unauthorized error 
`[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - vcsType: BITBUCKET
[threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.workspace.SetupWorkspaceImpl - https://bitbucket.org/x/src/main/: not authorized`

However, I have added Terrakube as an OAuth consumer to my repo.

**Comment by alfespa17** [comment]
> > > Sure. It aligns with what I see in the Terrakube UI. Here it is:
> > > ![image](https://private-user-images.githubusercontent.com/28630442/321438702-0ebe0e85-042d-4fd9-a7c6-f95f70ac5d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTYwNDgsIm5iZiI6MTcxMjc5NTc0OCwicGF0aCI6Ii8yODYzMDQ0Mi8zMjE0Mzg3MDItMGViZTBlODUtMDQyZC00ZmQ5LWE3YzYtZjk1ZjcwYWM1ZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAwMzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZjFjZDYzNzBkMDBlMjQ4ODNkNzkwZDgyZTQ2M2ZlNTFhMGY5OTE3Y2Q5MGNjZTM1NjI4MzFhYTJkZDAyZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qLvpiTU6OTEM12UGohpjoTNueWvnCywhjJpLoqFoW28)
> > 
> > 
> > Could You check the logs before the message running terraform apply You should see información about the git clone operation
> 
> thanks @alfespa17 I can see there is and unauthorized error `[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - vcsType: BITBUCKET [threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.workspace.SetupWorkspaceImpl - https://bitbucket.org/x/src/main/: not authorized`
> 
> However, I have added Terrakube as an OAuth consumer to my repo.

I understand that you are currenyly testing, are You stopping the cluster ? Because there is an internal job that updates the auth token every hour or two hours if i remenber correctly, if You stop the clúster maybe the job that update the token was not triggered años could You check the vcs connection status in the ui?

**Comment by MARVELMafia** [comment]
> > > > Sure. It aligns with what I see in the Terrakube UI. Here it is:
> > > > ![image](https://private-user-images.githubusercontent.com/28630442/321438702-0ebe0e85-042d-4fd9-a7c6-f95f70ac5d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTYwNDgsIm5iZiI6MTcxMjc5NTc0OCwicGF0aCI6Ii8yODYzMDQ0Mi8zMjE0Mzg3MDItMGViZTBlODUtMDQyZC00ZmQ5LWE3YzYtZjk1ZjcwYWM1ZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAwMzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZjFjZDYzNzBkMDBlMjQ4ODNkNzkwZDgyZTQ2M2ZlNTFhMGY5OTE3Y2Q5MGNjZTM1NjI4MzFhYTJkZDAyZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qLvpiTU6OTEM12UGohpjoTNueWvnCywhjJpLoqFoW28)
> > > 
> > > 
> > > Could You check the logs before the message running terraform apply You should see información about the git clone operation
> > 
> > 
> > thanks @alfespa17 I can see there is and unauthorized error `[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - vcsType: BITBUCKET [threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.workspace.SetupWorkspaceImpl - https://bitbucket.org/x/src/main/: not authorized`
> > However, I have added Terrakube as an OAuth consumer to my repo.
> 
> I understand that you are currenyly testing, are You stopping the cluster ? Because there is an internal job that updates the auth token every hour or two hours if i remenber correctly, if You stop the clúster maybe the job that update the token was not triggered. could You check the vcs connection status in the ui?

Yes I am just testing at the moment. I dont see any info on the connection on the UI. Should I delete the VCS and re-create it?

![image](https://github.com/AzBuilder/terrakube/assets/28630442/1a3cf64f-6efc-4b0b-b938-df5889e3316f)

**Comment by alfespa17** [comment]
> > > > > Sure. It aligns with what I see in the Terrakube UI. Here it is:
> > > > > ![image](https://private-user-images.githubusercontent.com/28630442/321438702-0ebe0e85-042d-4fd9-a7c6-f95f70ac5d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTYwNDgsIm5iZiI6MTcxMjc5NTc0OCwicGF0aCI6Ii8yODYzMDQ0Mi8zMjE0Mzg3MDItMGViZTBlODUtMDQyZC00ZmQ5LWE3YzYtZjk1ZjcwYWM1ZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAwMzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZjFjZDYzNzBkMDBlMjQ4ODNkNzkwZDgyZTQ2M2ZlNTFhMGY5OTE3Y2Q5MGNjZTM1NjI4MzFhYTJkZDAyZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qLvpiTU6OTEM12UGohpjoTNueWvnCywhjJpLoqFoW28)
> > > > 
> > > > 
> > > > Could You check the logs before the message running terraform apply You should see información about the git clone operation
> > > 
> > > 
> > > thanks @alfespa17 I can see there is and unauthorized error `[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - vcsType: BITBUCKET [threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.workspace.SetupWorkspaceImpl - https://bitbucket.org/x/src/main/: not authorized`
> > > However, I have added Terrakube as an OAuth consumer to my repo.
> > 
> > 
> > I understand that you are currenyly testing, are You stopping the cluster ? Because there is an internal job that updates the auth token every hour or two hours if i remenber correctly, if You stop the clúster maybe the job that update the token was not triggered. could You check the vcs connection status in the ui?
> 
> Yes I am just testing at the moment. I dont see any info on the connection on the UI. Should I delete the VCS provider and re-create it? Also, are you talking about the Kubernetes cluster? I did upgrade the helm deployment with a new values.yaml file for adding my custome CA bundle. Could that have affected the internal service that you are talking about?
> 
> ![image](https://private-user-images.githubusercontent.com/28630442/321454764-1a3cf64f-6efc-4b0b-b938-df5889e3316f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDAzNDIsIm5iZiI6MTcxMjgwMDA0MiwicGF0aCI6Ii8yODYzMDQ0Mi8zMjE0NTQ3NjQtMWEzY2Y2NGYtNmVmYy00YjBiLWI5MzgtZGY1ODg5ZTMzMTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAxNDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZDQ5ZjU1NGI0NTEyZTc0YmQwZDlkN2QwMjExOTRkZDA2NDBiZjgwM2MxZjIyMzkyYWQ4OWYzNjE3Y2EzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2FdlU1JjBmoT8XWascvuSwnS88u4JgIPGxGqF2t7qDI)

The button "connect to bitbucket ", should not be there...... I think you didn't authenticate correctly to bitbucket, it should look like the image we show here

https://docs.terrakube.io/user-guide/vcs-providers/bitbucket.com

Can you create a new VCS connection? And make sure to put all the correct parameters, once you have create the connection you should be redirected to bitbucket to approve the connection as we explain in the above link

**Comment by MARVELMafia** [comment]
> > > > > > Sure. It aligns with what I see in the Terrakube UI. Here it is:
> > > > > > ![image](https://private-user-images.githubusercontent.com/28630442/321438702-0ebe0e85-042d-4fd9-a7c6-f95f70ac5d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTYwNDgsIm5iZiI6MTcxMjc5NTc0OCwicGF0aCI6Ii8yODYzMDQ0Mi8zMjE0Mzg3MDItMGViZTBlODUtMDQyZC00ZmQ5LWE3YzYtZjk1ZjcwYWM1ZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAwMzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZjFjZDYzNzBkMDBlMjQ4ODNkNzkwZDgyZTQ2M2ZlNTFhMGY5OTE3Y2Q5MGNjZTM1NjI4MzFhYTJkZDAyZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qLvpiTU6OTEM12UGohpjoTNueWvnCywhjJpLoqFoW28)
> > > > > 
> > > > > 
> > > > > Could You check the logs before the message running terraform apply You should see información about the git clone operation
> > > > 
> > > > 
> > > > thanks @alfespa17 I can see there is and unauthorized error `[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - vcsType: BITBUCKET [threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.workspace.SetupWorkspaceImpl - https://bitbucket.org/x/src/main/: not authorized`
> > > > However, I have added Terrakube as an OAuth consumer to my repo.
> > > 
> > > 
> > > I understand that you are currenyly testing, are You stopping the cluster ? Because there is an internal job that updates the auth token every hour or two hours if i remenber correctly, if You stop the clúster maybe the job that update the token was not triggered. could You check the vcs connection status in the ui?
> > 
> > 
> > Yes I am just testing at the moment. I dont see any info on the connection on the UI. Should I delete the VCS provider and re-create it? Also, are you talking about the Kubernetes cluster? I did upgrade the helm deployment with a new values.yaml file for adding my custome CA bundle. Could that have affected the internal service that you are talking about?
> > ![image](https://private-user-images.githubusercontent.com/28630442/321454764-1a3cf64f-6efc-4b0b-b938-df5889e3316f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDAzNDIsIm5iZiI6MTcxMjgwMDA0MiwicGF0aCI6Ii8yODYzMDQ0Mi8zMjE0NTQ3NjQtMWEzY2Y2NGYtNmVmYy00YjBiLWI5MzgtZGY1ODg5ZTMzMTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAxNDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZDQ5ZjU1NGI0NTEyZTc0YmQwZDlkN2QwMjExOTRkZDA2NDBiZjgwM2MxZjIyMzkyYWQ4OWYzNjE3Y2EzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2FdlU1JjBmoT8XWascvuSwnS88u4JgIPGxGqF2t7qDI)
> 
> The button "connect to bitbucket ", should not be there...... I think you didn't authenticate correctly to bitbucket, it should look like the image we show here
> 
> https://docs.terrakube.io/user-guide/vcs-providers/bitbucket.com
> 
> Can you create a new VCS connection? And make sure to put all the correct parameters, once you have create the connection you should be redirected to bitbucket to approve the connection as we explain in the above link

Thank you! I created a vew VCS connection and it all seems to be working well together now. Thank you for your help 🙏
