### ISSUE TITLE
Cannot run parallel jobs in the UI

### ISSUE THREAD

**Issue by calvinbui** [AzBuilder/terrakube#804]
### Bug description 🐞

When a run is already pending/running, starting a new job via the UI will result in a 403 error in the console.

![image](https://github.com/AzBuilder/terrakube/assets/3604363/a540352b-b045-4b49-9c86-ffd47b9b5635)

![image](https://github.com/AzBuilder/terrakube/assets/3604363/1185af06-9929-4c68-9dc4-023e45188522)

### Steps to reproduce

1. Run a job
2. While the job is running, running another one via the UI via the 'Start a new job' modal

### Expected behavior

Ideally, queue the next run. Otherwise, provide an error in the UI that a job is already running

### Anything else?

I am evaluating terrakube via the minikube helm deployment.

**Comment by alfespa17** [comment]
This can be change. It will only happen when you are using the UI, if you trigger the job using the CLI driven workflow or using a push to the repository it will create a queue of jobs internally

**Comment by alfespa17** [comment]
I will fix this one for 2.20.1

**Comment by alfespa17** [comment]
I created the release that fixes this issue.

https://github.com/AzBuilder/terrakube/releases/tag/2.20.1

**Comment by calvinbui** [comment]
I can confirm it works
