### ISSUE TITLE
Runs with no changes do not need confirmation

### ISSUE THREAD

**Issue by calvinbui** [AzBuilder/terrakube#805]
### Bug description 🐞

When a CLI run has no changes, there shouldn't be any prompts and the plan should complete.

![image](https://github.com/AzBuilder/terrakube/assets/3604363/a50c38ad-2dc5-41fa-bcee-251b8e401903)

![image](https://github.com/AzBuilder/terrakube/assets/3604363/ab9be29a-29e9-4288-9e25-16c0f272de47)

### Steps to reproduce

1. Apply a run with no changes
2. View the CLI or UI

### Expected behavior

No prompt. This is how terraform cloud does it:

![image](https://github.com/AzBuilder/terrakube/assets/3604363/4fcadae8-ac12-4979-b510-7cb2e900285f)

### Anything else?

I am evaluating terrakube via the minikube helm deployment.

**Comment by alfespa17** [comment]
This can be an improvement I will find out how to add this validation.
