### ISSUE TITLE
'Plan and apply' from the UI should prompt for approval

### ISSUE THREAD

**Issue by calvinbui** [AzBuilder/terrakube#806]
### Feature description 💡

Running a 'Plan and apply' job from the UI should prompt for approval after the plan completes.

Instead, it plans and applies the changes instantly, which can be unsafe.

![image](https://github.com/AzBuilder/terrakube/assets/3604363/ffdd75da-f654-492c-8adf-04bf63f0dbd5)

![image](https://github.com/AzBuilder/terrakube/assets/3604363/2442aa79-7d3b-4ff2-8656-c45cceb419fa)

Compare this to a CLI run:

![image](https://github.com/AzBuilder/terrakube/assets/3604363/6cc19060-39b3-4453-816d-88b47872b0da)

**Comment by jcanizalez** [comment]
Hi @calvinbui 

You can modify the default Plan and Apply template to add approvals.

Check this for more details https://docs.terrakube.io/user-guide/organizations/templates

More examples:

https://github.com/AzBuilder/terrakube-extensions?tab=readme-ov-file#advance-example

**Comment by alfespa17** [comment]
You can change that configuration adding the following yo your templates

```
- type: "approval"
  step: 250
  team: "AZB_ADMIN
```

Just make sure that the "team" information will depend on you dex configuration and how dex handle the groups name internally.

**Comment by calvinbui** [comment]
thanks that works. i reckon it should be the default if possible too.

**Comment by alfespa17** [comment]
> thanks that works. i reckon it should be the default if possible too.

The issue to leave an approval by default is that the approval group name will change depending on your dex configuration

**Comment by calvinbui** [comment]
> > thanks that works. i reckon it should be the default if possible too.
> 
> The issue to leave an approval by default is that the approval group name will change depending on your dex configuration

not necessarily

```
  - type: "approval"
    name: "Approval"
    step: 150
```

**Comment by alfespa17** [comment]
> > > thanks that works. i reckon it should be the default if possible too.
> > 
> > 
> > The issue to leave an approval by default is that the approval group name will change depending on your dex configuration
> 
> not necessarily
> 
> ```yaml
> flow:
>   - type: "terraformPlan"
>     name: "Plan"
>     step: 100
>   
>   - type: "approval"
>     name: "Approval"
>     step: 150
> 
>   - type: "terraformApply"
>     name: "Apply"
>     step: 200
> ```

Now I get your point, an approval step that is open to any user, this could be a new feature
