### ISSUE TITLE
Run status in UI is slow to update

### ISSUE THREAD

**Issue by calvinbui** [AzBuilder/terrakube#807]
### Bug description 🐞

I have found that the state is slow to update in a run.

For example, the `simple_sample` can complete it's `Plan` and a `Apply` stages and sit in a `pending` or `running` for ~1 minute before the next stage or status updates.

### Steps to reproduce

Video link: https://drive.google.com/file/d/19tCgUHCKce9UA8JbQjNP0Mek3SMcVZ0c/view?usp=sharing

### Anything else?

I am evaluating terrakube via the minikube helm deployment.

**Comment by alfespa17** [comment]
There is an explanation for this, when you triggered a run internally terrakube create an internal job using quartz library that executed every 60 seconds

**Comment by calvinbui** [comment]
[is this the code that's responsible for this?](https://github.com/AzBuilder/terrakube/blob/3f9589f775e755d7cb739410f57514e3bd479646/api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJobService.java#L25)

for comparison, creating 2 x `null resources` and 1 x `random_integer` through a CLI run:
- Terrakube: 1m 55s
- [OTP/TofuTF](https://github.com/tofutf/tofutf): 11s
- Terraform Cloud: 23s

**Comment by jcanizalez** [comment]
I think should be better to run the job immediately instead of adding a delay. Using something like this https://stackoverflow.com/questions/9890212/java-quartz-scheduler-fire-a-new-job-immediately

**Comment by alfespa17** [comment]
> I think should be better to run the job immediately instead of adding a delay. Using something like this https://stackoverflow.com/questions/9890212/java-quartz-scheduler-fire-a-new-job-immediately

Maybe I can use something similar to the above stackoverflow reference so I can change the job that is schedule every minute

**Comment by jcanizalez** [comment]
an idea is to use distributed collections with redis:

https://github.com/redisson/redisson/wiki/7.-distributed-collections/#78-queue


Then the Quartz job should be running 

 ```
while ((item = queue.poll()) != null) {
  // process jobs
}
```

**Comment by alfespa17** [comment]
I did a few improvements for this and the new job trigger logic can be tested with this version.

https://github.com/AzBuilder/terrakube/releases/tag/2.22.0-beta.1
