### ISSUE TITLE
Change URLs to link directly to page being viewed

### ISSUE THREAD

**Issue by calvinbui** [AzBuilder/terrakube#808]
### Feature description 💡

When within a organization > workspace, moving between the different tabs (Overview/Runs/States/Variables) does not update the URL, it always sticks to the format `https://terrakube-ui/workspaces/<uuid>`

If I share the link with someone else, they must firstly be already in the right organization for the workspace to show, or they get a `Data loading...` page:

![image](https://github.com/AzBuilder/terrakube/assets/3604363/a610b606-9fc1-40ef-a885-07f247406a16)

This is handy in situations when I want to share a specific Run with other users for approval for example.

This even happens when I use the link from the CLI, it only takes me to the workspace: `https://terrakube-api/app/simple/sample_simple/runs/17` will take me to `https://terrakube-api/workspaces/5ed411ca-7ab8-4d2f-b591-02d0d5788afc`

**Comment by jcanizalez** [comment]
Hello @calvinbui,

I recently added a this feature please check out this PR: https://github.com/AzBuilder/terrakube/pull/797.

This feature will be available in version 2.21 We'll release a beta version in the upcoming days if you'd like to try it.
This will change also the url when you change between tabs.

**Comment by jcanizalez** [comment]
I think I still need to add organization context to url so will keep this issue open

**Comment by calvinbui** [comment]
> Hello @calvinbui,
> 
> I recently added a this feature please check out this PR: #797.
> 
> This feature will be available in version 2.21 We'll release a beta version in the upcoming days if you'd like to try it. This will change also the url when you change between tabs.

I can confirm this works

**Comment by jcanizalez** [comment]
I've added the organization ID to the URL path to fix the loading issue. I'm closing this issue; it will be released in v2.21. You can test it in the next beta if you want a preview.
