### ISSUE TITLE
New job triggers stopped working and stuck in queue state and transitioned to failed state after 6 hours

### ISSUE THREAD

**Issue by kspradheep** [AzBuilder/terrakube#819]
### Bug description 🐞

New job triggers stopped working and stuck in queue state and transitioned to failed state after 6 hours.

Terrakube version: 2.19.2

API pod logs:
2024-04-19 18:38:00.051  INFO 1 --- [ryBean_Worker-5] o.t.api.plugin.scheduler.ScheduleJob     : Checking Job 401 Status queue
2024-04-19 18:38:00.051  INFO 1 --- [ryBean_Worker-5] o.t.api.plugin.scheduler.ScheduleJob     : Checking previous jobs....
2024-04-19 18:38:00.053  INFO 1 --- [ryBean_Worker-5] o.t.api.plugin.scheduler.ScheduleJob     : Job 401 Status queue
2024-04-19 18:38:25.410 ERROR 1 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

io.jsonwebtoken.UnsupportedJwtException: Signed JWSs are not supported.

Executor pod logs:
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Creating new SSH folder for organization 00cc49f5-4f9f-432c-b296-e74402819a5a wordkspace c27fe704-2db7-44d3-a763-b36212895713
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Git clone: ssh://git@xxxxxxx/devops/devops.terraform.aws.git Branch: feature/devops-99-blue-gree-testing Folder /home/cnb/.terraform-spring-boot/executor/00cc49f5-4f9f-432c-b296-e74402819a5a/c27fe704-2db7-44d3-a763-b36212895713
[threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.workspace.security.WorkspaceSecurityImpl - Generate Dex Authentication Private Token
[threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.executor.ExecutorJobImpl - /home/cnb/.terraform-spring-boot/executor/00cc49f5-4f9f-432c-b296-e74402819a5a/c27fe704-2db7-44d3-a763-b36212895713/commitHash.info (No such file or directory)
[threadPoolTaskExecutor-1] ERROR org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(org.terrakube.executor.service.mode.TerraformJob)
feign.FeignException$InternalServerError: [500 ] during [GET] to [http://terrakube-api-service:8080/api/v1/organization/00cc49f5-4f9f-432c-b296-e74402819a5a/job/400?include=step] [TerrakubeClient#getJobById(String,String)]: [{"timestamp":"2024-04-19T13:34:00.391+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/organization/00cc49f5-4f9f-432c-b296-e74402819a5a/job/400"}]

No error logs in Dex pod.

### Steps to reproduce

Trigger a new plan job from UI

### Expected behavior

Terraform init and plan operations should run within the job

### Anything else?

The workspaces have been working fine but suddenly stopped working.

**Comment by alfespa17** [comment]
Check inside the database the job table for that particular workspace id, if you find some old job you can mark those as cancelled status

**Comment by alfespa17** [comment]
You could also check here

https://github.com/orgs/AzBuilder/discussions/714

**Comment by kspradheep** [comment]
Okay, will check job status in database. It's not just one workspace. I tried on 2 workspaces and both of them having same issue. There are no pending jobs in each workspace.

**Comment by kspradheep** [comment]
<img width="284" alt="image" src="https://github.com/AzBuilder/terrakube/assets/68883779/d33e2544-68b1-4807-a651-b26f7291fab0">

Doesn't seem it's an issue with Job status. Every job id has either completed, failed, cancelled or rejected.

I see errors for JSON Web Token and DEX token errors in api and executor pod logs. Could it be an issue with tokens?

**Comment by kspradheep** [comment]
<img width="1370" alt="image" src="https://github.com/AzBuilder/terrakube/assets/68883779/7119412c-bed1-4898-bf60-50d53fc821b0">

Also, noticed when job marked failed post 6 hours the lock id is not being released on workspace.

**Comment by alfespa17** [comment]
> <img alt="image" width="1370" src="https://private-user-images.githubusercontent.com/68883779/324114019-7119412c-bed1-4898-bf60-50d53fc821b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NjEzNDYsIm5iZiI6MTcxMzU2MTA0NiwicGF0aCI6Ii82ODg4Mzc3OS8zMjQxMTQwMTktNzExOTQxMmMtYmVkMS00ODk4LWJmNjAtNTBkNTNmYzgyMWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDIxMTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTk5OGZiYWZiYjk0ZjBjNDZiNDNhMDIzMjE5ODQ3Nzg1NDRhOWQwMzBiY2FkZTIyNzZmNjQ3ODZjNzE0ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zQKNFRwN6kwcl85HXeOUHv_alrGh8z4P7hR5B6yDlTw">
> Also, noticed when job marked failed post 6 hours the lock id is not being released on workspace.

i think you can change that inside the workspace settings manually

**Comment by kspradheep** [comment]
> > <img alt="image" width="1370" src="https://private-user-images.githubusercontent.com/68883779/324114019-7119412c-bed1-4898-bf60-50d53fc821b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NjEzNDYsIm5iZiI6MTcxMzU2MTA0NiwicGF0aCI6Ii82ODg4Mzc3OS8zMjQxMTQwMTktNzExOTQxMmMtYmVkMS00ODk4LWJmNjAtNTBkNTNmYzgyMWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDIxMTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTk5OGZiYWZiYjk0ZjBjNDZiNDNhMDIzMjE5ODQ3Nzg1NDRhOWQwMzBiY2FkZTIyNzZmNjQ3ODZjNzE0ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zQKNFRwN6kwcl85HXeOUHv_alrGh8z4P7hR5B6yDlTw">
> > Also, noticed when job marked failed post 6 hours the lock id is not being released on workspace.
> 
> i think you can change that inside the workspace settings manually

yes, i can unlock manually. Any ideas why job is stuck in queue state?

**Comment by alfespa17** [comment]
Check the logs maybe the executor component is failing

**Comment by kspradheep** [comment]
[threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.workspace.security.WorkspaceSecurityImpl - Generate Dex Authentication Private Token
[threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.executor.ExecutorJobImpl - /home/cnb/.terraform-spring-boot/executor/00cc49f5-4f9f-432c-b296-e74402819a5a/c27fe704-2db7-44d3-a763-b36212895713/commitHash.info (No such file or directory)
[threadPoolTaskExecutor-1] ERROR org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(org.terrakube.executor.service.mode.TerraformJob)
feign.FeignException$InternalServerError: [500 ] during [GET] to [http://terrakube-api-service:8080/api/v1/organization/00cc49f5-4f9f-432c-b296-e74402819a5a/job/403?include=step] [TerrakubeClient#getJobById(String,String)]: [{"timestamp":"2024-04-19T21:23:00.491+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/organization/00cc49f5-4f9f-432c-b296-e74402819a5a/job/403"}]

**Comment by kspradheep** [comment]
Thanks @alfespa17 Restarting executor pod fixed the issue. I didn't see following log in working executor pod:
[threadPoolTaskExecutor-1] ERROR org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(org.terrakube.executor.service.mode.TerraformJob)
feign.FeignException$InternalServerError: [500 ] during [GET] to [http://terrakube-api-service:8080/api/v1/organization/00cc49f5-4f9f-432c-b296-e74402819a5a/job/403?include=step] [TerrakubeClient#getJobById(String,String)]: [{"timestamp":"2024-04-19T21:23:00.491+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/organization/00cc49f5-4f9f-432c-b296-e74402819a5a/job/403"}]

we ran job today after 14 days. Do we need to restart exector periodically? Maybe need enhancement to executor liveness probe?

Is it a bug or normal workspace lock id is not being released after job expired idle time set?

**Comment by alfespa17** [comment]
> Thanks @alfespa17 Restarting executor pod fixed the issue. I didn't see following log in working executor pod: [threadPoolTaskExecutor-1] ERROR org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(org.terrakube.executor.service.mode.TerraformJob) feign.FeignException$InternalServerError: [500 ] during [GET] to [http://terrakube-api-service:8080/api/v1/organization/00cc49f5-4f9f-432c-b296-e74402819a5a/job/403?include=step] [TerrakubeClient#getJobById(String,String)]: [{"timestamp":"2024-04-19T21:23:00.491+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/organization/00cc49f5-4f9f-432c-b296-e74402819a5a/job/403"}]
> 
> we ran job today after 14 days. Do we need to restart exector periodically? Maybe need enhancement to executor liveness probe?
> 
> Is it a bug or normal workspace lock id is not being released after job expired idle time set?

Maybe the issue was related to the lock that was not release after 6 hours so the executor was not able to update the workspaces, I will check may be I can find something

**Comment by kspradheep** [comment]
The previous job completed successfully that ran 14 days ago and it was unlocked. I would think there are 2 issues:
1. Executor stopped working and throwing 500 status code as shown error above. Never recovered itself until restart the service.
2. The discard logic is not releasing workspace lock id if job idle time expired.
