### ISSUE TITLE
UI alerts for Registry errors when adding modules

### ISSUE THREAD

**Issue by aacuadras** [AzBuilder/terrakube#829]
### Bug description 🐞

Currently, when adding a module via the UI to the registry and an error happens the API is the only service to report the failure. The UI won't do any actions, the only way to see the errors is by navigating to the browser console, however the error shown there is very basic, so the only place so far that I was able to find the issue is in the API console logs. For example, by trying to set up a module name bigger than 32 characters, the UI will remain the same and the following error will be thrown in the browser's console:
<img width="1440" alt="Screenshot 2024-05-02 at 11 19 55 AM" src="https://github.com/AzBuilder/terrakube/assets/35941251/746c8695-647b-404e-b08a-fc9748b7b55d">

The only place where I could see the errors were in the api debug logs:
```
2024-05-02T16:19:17.473Z ERROR 7642 --- [         task-9] c.y.e.d.j.t.AbstractJpaTransaction       : Caught entity manager exception during flush

org.hibernate.exception.DataException: could not execute statement [Value too long for column "NAME CHARACTER VARYING(32)": "'a-very-long-name-for-a-tf-module-1' (34)"; SQL statement:
insert into module (created_by,created_date,description,download_quantity,folder,name,organization_id,provider,source,ssh_id,tag_prefix,updated_by,updated_date,vcs_id,id) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [22001-214]] [insert into module (created_by,created_date,description,download_quantity,folder,name,organization_id,provider,source,ssh_id,tag_prefix,updated_by,updated_date,vcs_id,id) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)]
```

It would be good to bubble up those errors in model validations all the way to the UI.

### Steps to reproduce

1. Navigate to organization registry
2. Add a module with a name longer than 32 characters
3. Investigate browser console and api debug logs

### Expected behavior

I should expect seeing an error in the UI explaining that the name is too long.

**Comment by alfespa17** [comment]
Maybe adding some validation in the UI that shows that it support up to 32 characters should be enough.

**Comment by aacuadras** [comment]
@alfespa17 I see that there is a model representing the `module` table. Any thoughts on adding validation to the models in order to report any kind of validation error in the UI instead of just covering this case?

**Comment by alfespa17** [comment]
We are using [elide](https://github.com/yahoo/elide) to expose the module endpoint, I think it will only return 423 error by default in those cases, not sure if there is a way to return some more data.
