### ISSUE TITLE
Module has no versions

### ISSUE THREAD

**Issue by gdacal** [AzBuilder/terrakube#831]
### Bug description 🐞

When running a plan or apply using Terrakube's private registry, the following error occurs randomly:

`***************************************
Running Terraform PLAN
***************************************
���
��� Error: Module has no versions
��� 
���  on main.tf line 5:
���   5: module "aws-workload-container" {
��� 
��� Module "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
��� (main.tf:5) has no versions available on xxxxxxxxxxxxxxxxxxxxxx
���

���
��� Error: Module not installed
��� 
���  on main.tf line 5:
���   5: module "aws-workload-container" {
��� 
��� This module is not yet installed. Run "terraform init" to install all
��� modules required by this configuration.
���
`

### Steps to reproduce

The error occurs randomly.

**Comment by alfespa17** [comment]
Can you double check if the git repository that you are using for that particular module has the tag for the version of the module that you are using?

Are you using the remote execution or the local execution mode?
