### ISSUE TITLE
CLI Workspace with Local Execution or Remote mode ignores workspace lock

### ISSUE THREAD

**Issue by iam-take** [AzBuilder/terrakube#834]
### Bug description 🐞

When running a workspace in local execution mode and enabling a state/workspace lock on that workspace wont result in a block on running the workspace either Terraform Plan or Apply. 

Instead Terrakube will remove the lock on the workspace and allowing either the plan or apply to continue. The whole purpose of locking the state is preventing a workspace to be ran. This should make no difference between local or remote execution mode. 

For the remote cli workspace configuration the setting in the portal stays on locked when a plan is ran, although a plan should also already be blocked when locking the state. When running a apply Terrakube will also unlock the state and allow a apply to be ran. 

### Steps to reproduce

Create a cli workspace with either remote or local execution
For a local execution mode workspace run a terraform plan and the state/workspace will be unlocked, same for Terraform Apply
For a remote execution mode workspace run a Terraform Apply and the state/workspace will be unlocked

### Expected behavior

The state / workspace should remain locked until the user removes the lock either through the portal or api call.

**Comment by iam-take** [comment]
Can somebody confirm if this is currently expected or unexpected behaviour of Terrakube? Would like to know if my assumptions are correct on this matter.

**Comment by alfespa17** [comment]
Hello @iam-take this is a bug that I need to fix, I will have to do some research to find out what is causing that unexpected behavior

**Comment by iam-take** [comment]
Thanks for confirming it's good to know it's an actual bug. We will work with it for now. If I can help in any way or test anything let me know!

**Comment by alfespa17** [comment]
I did some progress with this issue, now terraform/tofu correctly validate the lock in the workspace before processing when you are running the CLI driven workflow as show in this image until you change the lock setting in the UI.

![image](https://github.com/AzBuilder/terrakube/assets/4461895/13112ec4-4146-4d69-b685-23decbfbe46b)

I still need to do some changes but maybe next week I could finish to refactor all the lock logic that was wrong

**Comment by alfespa17** [comment]
Improved lock logic can be tested in the following version:

https://github.com/AzBuilder/terrakube/releases/tag/2.22.0-beta.1

**Comment by iam-take** [comment]
@alfespa17 I've upgraded our instance to the latest version (2.22.0) which by the release notes contains this solution however when testing this the logic still doesn;t work. A plan will remove the lock same as before :(

**Comment by alfespa17** [comment]
> @alfespa17 I've upgraded our instance to the latest version (2.22.0) which by the release notes contains this fix however when testing this the logic still doesn;t work. A plan will remove the lock same as before :(
> 
> Did you only test this with the remote execution mode or also with the local mode? I've switched or Local execution mode to remote and than the lock is adhered to but not on the local mode. And this is just the mode that we require on all our workspaces. I've created a new issue for this #1248

I think I only tested with the remote execution,  I will check the terraform code to see how it works with the local execution I guess I will have to add some missing validation like I did with the remote execution
