### ISSUE TITLE
Include hostname in example cloud / remote backend block of a workspace. 

### ISSUE THREAD

**Issue by iam-take** [AzBuilder/terrakube#835]
### Feature description 💡

In each workspace Terrakube contains a bit of example code for the backend / cloud block if the workspace isn't configured yet. This is very helpful the only thing currently is that it is missing the required hostname = %api_url% without this the backend configuration won't work. For the users whom have less knowledge this is some key information missing. 

It would be very helpful if this example code included the actual hostname of the terrakube api that is configured for the instance the workspace is running.

**Cloud Block example**
```terraform
terraform { 
  cloud { 
    hostname      = terrakube-api.example.com
    organization  = "terrakube-example" 
    workspaces { 
      name = "example-workspace-sbx" 
    } 
  } 
} 
```

**Remote Backend Block example**

```terraform
terraform { 
  backend "remote" { 
    hostname      = terrakube-api.example.com
    organization  = "terrakube-example" 

    workspaces { 
      name = "example-workspace-sbx" 
    } 
  } 
} 
```

**Comment by alfespa17** [comment]
Thank you for the suggestion @iam-take
