### ISSUE TITLE
"subject_token must be nonempty" from dynamic GCP Credentials

### ISSUE THREAD

**Issue by tomwardill-payoneer** [AzBuilder/terrakube#839]
### Bug description 🐞

When attempting to use the new GCP Dynamic Credentials feature, I get:
```
Post "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/<redacted service account>:generateAccessToken": oauth2/google: status code 400: {"error":"invalid_request","error_description":"subject_token must be nonempty."}
```

I believe that I have configured it correctly, but got very confused with the docs, around which aspects are placeholder values and which need to be copied exactly.
Also, granting the service account access appears to be missing a step and details about the Principals and Attribute Names that appear to be required

### Steps to reproduce

Configure the workload identity in GCP, following example as best understood

### Expected behavior

A terraform plan should retrieve dynamic credentials

### Anything else?

I realise it's more work, and if I had a working config I would be happy to contribute the docs, but a fully populated set of example configuration strings would be useful to avoid confusion about placeholders vs attribute names.

While I've just filed this bug report, I'd like to voice my appreciation for the addition of this feature, it will be extremely useful to us as service account keys are hard to manage.

**Comment by alfespa17** [comment]
Hello @tomwardill-payoneer 

Did you mount your public and private key to the container?

**Comment by alfespa17** [comment]
Inside your logs for the API you should see two messages with the following:

- TERRAKUBE_GCP_CREDENTIALS_FILE:
- TERRAKUBE_GCP_CREDENTIALS_CONFIG_FILE:

> By the way I will remove those logs once we release an stable version, but for now those are useful for testing

Maybe you can check the generated token and check with https://jwt.io/ the subject field

**Comment by alfespa17** [comment]
By the way I think it will be easier to do the setup with Terraform like in this [example](https://github.com/hashicorp/terraform-dynamic-credentials-setup-examples/tree/main/gcp), I will create a similar folder for the terrakube configuration so it will be easier to reproduce

**Comment by alfespa17** [comment]
I created a small terraform code to do all the setup in gcp and create the workspace in terrakube to test, I hope this can help

https://github.com/AzBuilder/terrakube/tree/main/dynamic-credential-setup/gcp

**Comment by tomwardill-payoneer** [comment]
Hi,
Many thanks for the extra documentation and the sample terraform.
I've used the terraform to configure the provider, and the private/public key are mounted in my API pod.

However, there is no change in the error I get.

```
 TERRAKUBE_GCP_CREDENTIALS_FILE: {
    "access_token": ""
} 
```
This does not look correct?

Immediately preceeding that is:
```
2024-05-10T10:07:20.710Z  INFO 1 --- [ryBean_Worker-3] o.t.a.p.s.j.t.executor.ExecutorService   : Loading default env variables to job
2024-05-10T10:07:20.738Z ERROR 1 --- [ryBean_Worker-3] o.t.a.p.t.d.DynamicCredentialsService    : Illegal base64 character 2d
```

Have I got something not base64 encoded that I should?

**Comment by tomwardill-payoneer** [comment]
Ah, I think I see what's going on, at least for this issue :)

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/plugin/token/dynamic/DynamicCredentialsService.java#L162

That replace doesn't match if you've generated the PEM via terraform:
```
resource "tls_private_key" "dynamic-credentials-private-key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}
```
which generates a key with the header:
```
-----BEGIN RSA PRIVATE KEY-----
```

**Comment by tomwardill-payoneer** [comment]
Yep, that did it!

Thanks so much for your support, I had a bunch of stuff wrong in the identity pool setup that the sample terraform fixed up for me.

**Comment by alfespa17** [comment]
I am glad that it work, I will update our documentation with the Terraform example ( it is easier to do the setup like this)

By the way if you would like to test it with AWS I created a similar example here:

https://github.com/AzBuilder/terrakube/blob/main/dynamic-credential-setup/aws/README.md
