### ISSUE TITLE
Bug: Get latest job for workspace

### ISSUE THREAD

**Issue by ilkerispir** [AzBuilder/terrakube#841]
### Bug description 🐞

Hello @alfespa17, @jcanizalez;

Unfortunately, the jobs in the response returned from the grapql request in the graphql/api/v1 path in the terrakube API do not sort in order for jobid or date. I shared the relevant code and link below. 

```
//get latest job for workspace
var lastJob = element.node.job.edges?.slice(-1)?.pop()?.node;
```

https://github.com/AzBuilder/terrakube/blob/2e47fe5ed37b5c34a46d7301037c24a32684713a/ui/src/domain/Organizations/Details.jsx#L550

Even though this javascript function finds the last element, as I said above, jobs come completely randomly from the backend API. In this case, the statuses appear incorrectly in the UI. We can solve this issue by changing the function in Javascript, but I think the most logical solution would be to fix the backend API. In my opinion, there is no need to respond to the client for all jobs in this API. Replying to the last job will be sufficient.

Unfortunately, since my knowledge of Java and Elide is limited, I could not understand exactly where it works, even if I debugged the code in detail. If you can help me with this issue, I can make the relevant fix.

Sample response from my API:
```
{
  "data": {
    "organization": {
      "edges": [
        {
          "node": {
            "id": "xxxx-xxxx-xxxx-xxxx-xxxx",
            "name": "xxxx",
            "workspace": {
              "edges": [
                {
                  "node": {
                    "id": "246",
                    "status": "completed",
                    "updatedDate": "2024-02-10T15:05Z"
                  }
                },
                {
                  "node": {
                    "id": "247",
                    "status": "completed",
                    "updatedDate": "2024-02-10T15:21Z"
                  }
                },
                {
                  "node": {
                    "id": "335",
                    "status": "completed",
                    "updatedDate": "2024-02-22T04:07Z"
                  }
                },
                {
                  "node": {
                    "id": "334",
                    "status": "failed",
                    "updatedDate": "2024-02-22T03:34Z"
                  }
                },
                {
                  "node": {
                    "id": "332",
                    "status": "failed",
                    "updatedDate": "2024-02-22T03:16Z"
                  }
                },
                {
                  "node": {
                    "id": "329",
                    "status": "failed",
                    "updatedDate": "2024-02-22T03:10Z"
                  }
                },
                {
                  "node": {
                    "id": "328",
                    "status": "failed",
                    "updatedDate": "2024-02-22T03:08Z"
                  }
                },
                {
                  "node": {
                    "id": "331",
                    "status": "failed",
                    "updatedDate": "2024-02-22T03:14Z"
                  }
                },
                {
                  "node": {
                    "id": "333",
                    "status": "failed",
                    "updatedDate": "2024-02-22T03:27Z"
                  }
                },
                {
                  "node": {
                    "id": "330",
                    "status": "failed",
                    "updatedDate": "2024-02-22T03:12Z"
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

### Steps to reproduce

-

### Expected behavior

-

### Example repository

-

### Anything else?

-

**Comment by alfespa17** [comment]
Hello @ilkerispir

I am not good in graghql but I think this could be solved adding some "sort property" in this request

https://github.com/AzBuilder/terrakube/blob/2e47fe5ed37b5c34a46d7301037c24a32684713a/ui/src/domain/Organizations/Details.jsx#L227

**Comment by alfespa17** [comment]
There is one "sort" example in elide documentation here inside the section "Sort All Books" 

https://elide.io/pages/guide/v7/11-graphql.html

**Comment by ilkerispir** [comment]
@alfespa17, I don't think the problem is caused by grapql. When I run a DB query for the job table, the records are sorted without ID. 

Example query:
![image](https://github.com/AzBuilder/terrakube/assets/37123041/2b32f4c5-a53e-4c0b-8bcf-3b0fa426044a)

**Comment by ilkerispir** [comment]
@alfespa17, thank you for you feedback, I think the PR I have created below will fix this situation. Could you please review it when you are available?

PR: https://github.com/AzBuilder/terrakube/pull/845

**Comment by alfespa17** [comment]
> @alfespa17, thank you for you feedback, I think the PR I have created below will fix this situation. Could you please review it when you are available?
> 
> PR: #845

Sure I will check later today

**Comment by ilkerispir** [comment]
@alfespa17, thank you for reviewing and merging. Could you please release a new beta version for this change?

**Comment by alfespa17** [comment]
> @alfespa17, thank you for reviewing and merging. Could you please release a new beta version for this change?

I have created the new beta release it should be ready in some minutes.
