### ISSUE TITLE
Show API Tokens which are generated through terraform login

### ISSUE THREAD

**Issue by iam-take** [AzBuilder/terrakube#900]
### Feature description 💡

When running Terraform login and generating a API Token to use for connecting to the Terrakube instance  this works. The thing missing is that this token isn't showing in the users settings > Tokens page. So the user in the UI has no traceability of this token nor the lifetime the token has. 

It would be great if these token(s) would be shown there as well.

**Comment by iam-take** [comment]
Hi @alfespa17, I now understand the technical reasoning behind it. We indeed are now mainly using API Tokens as these are more easy to configure and keep track of. Is this something that you want to keep open for now or shall I close it?

**Comment by alfespa17** [comment]
I think we can close it because there is no way to keep track of those tokens
