### ISSUE TITLE
I keep getting You are not authorized to create Organizations.

### ISSUE THREAD

**Issue by jezenith** [AzBuilder/terrakube#927]
### Feedback

Hi, i keep getting this 

You are not authorized to create Organizations.
Please contact your administrator and request to include you in the Terrakube Administrator group

even after creating a github team in my organisation TERRAKUBE_ADMIN and adding my github user to that team.
 
 
 here is my deployment i am using helm/argocd
 
 what i am i doing wrong
 
 `application: terrakube
clusterConfig:
  namespace: terrakube
chart:
  name: terrakube
  releaseName: terrakube
  repoURL: https://AzBuilder.github.io/terrakube-helm-chart
  targetRevision: 3.17.1
  values: |
    name: "terrakube"
    
    ## Terrakube Security
    security:
      adminGroup: "my-github-org-name:TERRAKUBE_ADMIN"
      patSecret: ""
      internalSecret: ""
      dexClientId: "github"
      dexClientScope: "email openid profile offline_access groups"

    ## Terraform Storage
    storage:
      defaultStorage: true
      s3:
        bucket: ""
        key: ""
        region: ""
        accessKeyID: ""
        secretAccessKey: ""

    dex:
      enabled: true
      config:
        issuer: https://mydomain/dex
        storage:
          type: memory
        oauth2:
          responseTypes: ["code", "token", "id_token"]
          skipApprovalScreen: true
        web:
          allowedOrigins: ["*"]

        staticClients:
        - id: github
          redirectURIs:
          - 'https://mydomain'
          - 'http://localhost:10001/login'
          - 'http://localhost:10000/login'
          - '/device/callback'
          name: 'github'
          public: true

        connectors:
        - type: github
          id: github
          name: gitHub
          config:
            clientID: ""
            clientSecret: ""
            redirectURI: "https://mydomain/dex/callback"
            loadAllGroups: true

    ## Ingress properties
    ingress:
      useTls: true
      ui:
        enabled: true
        domain: "mydomain"
        path: "/"
        pathType: "Prefix"
        ingressClassName: "alb"
        annotations:
          alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
          alb.ingress.kubernetes.io/group.name: alb-deployment
          alb.ingress.kubernetes.io/cors-allow-origin: '*'
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
          alb.ingress.kubernetes.io/target-type: ip
          kubernetes.io/ingress.class: alb
          external-dns.alpha.kubernetes.io/hostname: mydomain

      api:
        enabled: true
        domain: "mydomain"
        path: "/api/v1/"
        pathType: "Prefix"
        ingressClassName: "alb"
        annotations:
          alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
          alb.ingress.kubernetes.io/group.name: alb-deployment
          alb.ingress.kubernetes.io/cors-allow-origin: '*'
          alb.ingress.kubernetes.io/enable-cors: "true"
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
          alb.ingress.kubernetes.io/target-type: ip
          kubernetes.io/ingress.class: alb
          external-dns.alpha.kubernetes.io/hostname: mydomain

      registry:
        enabled: true
        domain: "mydomain"
        path: "/registry/"
        pathType: "Prefix"
        ingressClassName: "alb"
        annotations: 
          alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
          alb.ingress.kubernetes.io/group.name: alb-deployment
          alb.ingress.kubernetes.io/cors-allow-origin: '*'
          alb.ingress.kubernetes.io/enable-cors: "true"
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
          alb.ingress.kubernetes.io/target-type: ip
          kubernetes.io/ingress.class: alb
          external-dns.alpha.kubernetes.io/hostname: mydomain

      dex:
        enabled: true
        domain: "mydomain"
        path: "/dex/"
        pathType: "Prefix"
        ingressClassName: "alb"
        annotations: 
          alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
          alb.ingress.kubernetes.io/group.name: alb-deployment 
          alb.ingress.kubernetes.io/cors-allow-origin: '*'
          alb.ingress.kubernetes.io/enable-cors: "true"
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
          alb.ingress.kubernetes.io/target-type: ip
          kubernetes.io/ingress.class: alb
          external-dns.alpha.kubernetes.io/hostname: mydomain/dex
`

**Comment by alfespa17** [comment]
Hello @jezenith 

You can open your browser developer console and copy the access token to check the token information in the UI

![image](https://github.com/AzBuilder/terrakube/assets/4461895/2ce347c5-6a5e-4259-9b20-3b0cdaeffa87)

You could use https://jwt.io/ to check the groups inside the bearer token, those groups and check if the names match the one that you use when you use the helm chart 

![image](https://github.com/AzBuilder/terrakube/assets/4461895/9052bec5-2372-4d85-b65e-2714e3a1be8f)

By default the helm chart is using this group, depending of the groups that you have in your Azure AD:

```yaml
security:
  adminGroup: "TERRAKUBE_ADMIN"
```

I hope this can help you

**Comment by Jonathan-Emmanuel-deel** [comment]
Hi @alfespa17 thank you for replying i just did this and yes i can see myself part of the Team

i am using github OAuth

**Comment by jezenith** [comment]
Hi @alfespa17 thank you for replying i just did this and yes i can see myself part of the Team

i am using github OAuth

**Comment by jezenith** [comment]
![image](https://github.com/AzBuilder/terrakube/assets/88687066/439f4921-791d-47b0-903b-cc0a88995730)

**Comment by alfespa17** [comment]
Instead of this in your example values above

```
## Terrakube Security
security:
  adminGroup: "my-github-org-name:TERRAKUBE_ADMIN"
```

You should use 
```
## Terrakube Security
security:
  adminGroup: "zumo:TERRAKUBE_ADMIN"
```

**Comment by jezenith** [comment]
yes i did that, i just put that as a dummy placeholder when i was creating the github issue

**Comment by alfespa17** [comment]
Can you check the network response code to see if you are getting 401 or 403 in your browser console?

**Comment by jezenith** [comment]
i get 403 Forbidden

**Comment by alfespa17** [comment]
Try adding this environment variable 

```yaml
## API properties
api:
  env:
  - name: JAVA_TOOL_OPTIONS
    value: "-Dlogging.level.org.terrakube.api.plugin.security.groups.dex=DEBUG"
```

You should see something like this in the logs

```shell
2024-06-05T14:11:47.128Z DEBUG 1 --- [         task-2] o.t.a.p.s.g.dex.DexGroupServiceImpl      : Lester is member TERRAKUBE_ADMIN true
2024-06-05T14:11:47.129Z DEBUG 1 --- [         task-2] o.t.a.p.s.g.dex.DexGroupServiceImpl      : Lester is member TERRAKUBE_ADMIN true
2024-06-05T14:11:47.129Z DEBUG 1 --- [         task-2] o.t.a.p.s.g.dex.DexGroupServiceImpl      : Lester is member TERRAKUBE_ADMIN true
```

It is just doing a string compare, maybe you have some typo and you should see it from this part of the code

https://github.com/AzBuilder/terrakube/blob/adc227fde6c7a791f1b888dc06dd7e031b2b7f33/api/src/main/java/org/terrakube/api/plugin/security/groups/dex/DexGroupServiceImpl.java#L22

**Comment by jezenith** [comment]
Thank you, i see this logs now 
`2024-06-05T18:15:35.467Z DEBUG 1 --- [         task-8] o.t.a.p.s.g.dex.DexGroupServiceImpl      : Jonathan Emmanuel is member GCP_DEVELOPERS false
2024-06-05T18:15:38.348Z DEBUG 1 --- [         task-1] o.t.a.p.s.g.dex.DexGroupServiceImpl      : Jonathan Emmanuel is member Zumo:TERRAKUBE_ADMIN false
2024-06-05T18:15:44.211Z DEBUG 1 --- [         task-2] o.t.a.p.s.g.dex.DexGroupServiceImpl      : Jonathan Emmanuel is member Zumo:TERRAKUBE_ADMIN false`

**Comment by alfespa17** [comment]
You have a typo error @jezenith ,  in your helm chart  values you put "Zumo:TERRAKUBE_ADMIN" but in your token is "zumo:TERRAKUBE_ADMIN"

![image](https://github.com/AzBuilder/terrakube/assets/4461895/26dcb4d2-6992-4f10-8ba9-0129d3198cfe)

**Comment by jezenith** [comment]
🤦🏽‍♂️ missed that, Thank you so much, it works now
