### ISSUE TITLE
Unable to Create workspace

### ISSUE THREAD

**Issue by jezenith** [AzBuilder/terrakube#930]
### Feedback

Hi, i am unable to create workspace, i keep getting a blank page on the terraform version side and when i add a new VCS (github) it redirects me to a blank page. attached screenshots, please help am i doing anything wrong?
![image](https://github.com/AzBuilder/terrakube/assets/88687066/b82051dc-1b40-4146-a083-143bb2818e59)
![image](https://github.com/AzBuilder/terrakube/assets/88687066/f3c7efa4-cedd-4902-bdf3-90a58f80fef5)

**Comment by alfespa17** [comment]
I guess is a network issue, double check if you have connectivity to this endpoint from inside the API pod.

https://releases.hashicorp.com/terraform/index.json

**Comment by jezenith** [comment]
yeah. am using the correct call back redirect, i cant reach the terraform url

cnb@terrakube-api-884969c8c-bbz5q:/workspace$ wget -qO- https://releases.hashicorp.com/terraform/index.json
bash: wget: command not found
cnb@terrakube-api-884969c8c-bbz5q:/workspace$

**Comment by alfespa17** [comment]
wget command is not installed in the API container but if you are deploying the executor in the same k8s you could try running curl in the executor just to double check

`cnb@terrakube-executor-5d74845c5f-gxsz2:/workspace$ curl https://releases.hashicorp.com/terraform/index.json`

Maybe you can share some API pod logs when you are creating the workspace to check if you see some network issue

**Comment by jezenith** [comment]
curl works on the executor pod, i am using same k8s cluster and no log from the api pod when i am trying to create a workspace

![image](https://github.com/AzBuilder/terrakube/assets/88687066/3eaf94a3-dd73-4027-810d-c223df842e20)


![image](https://github.com/AzBuilder/terrakube/assets/88687066/36956d39-0817-415c-a8a1-c4b534b3d51d)
