### ISSUE TITLE
Allow to configure OpenTofu custom versions and binaries endpoint

### ISSUE THREAD

**Issue by FelipeAFV** [AzBuilder/terrakube#961]
### Feature description 💡

Just as you can now create a custom versions endpoint for Terraform, it would be helpful to have the ability to define a custom endpoint for OpenTofu releases. This would allow you to explicitly specify which versions are available in the Terrakube app. Additionally, you would need to define the value in the Terrakube Chart to specify the URL of the custom endpoint, similar to the terraformReleasesUrl value.

**Comment by alfespa17** [comment]
I will add it for the next release, I can add this in the following weeks

**Comment by alfespa17** [comment]
This feature can be tested using version 2.22.0-beta.2
